### ISSUE TITLE
u+1F3B1 BILLIARDS

### ISSUE THREAD

**Issue by pauldhunt** [Ranks/emojione#106]
There are some who feel that using the 8 ball to denote billiards is restrictive to pool specifically and should not be used for this purpose. A racked set of colored balles (with or without cue stick) would probably be more appropriate.

**Comment by wp9015362** [comment]
Hello,

I am against this.

Please do not change the "Billiards" Emoji.

Other popular Emoji sets, like the Apple Emoji set and the Twitter "Twemoji" set for example, are also using a very similar 8 ball for the "Billiards" Emoji, see the family tree for comparison:

http://emoji.codes/family?c=objects

So, changing the 8 ball to something else would hurt the interoperability with other popular Emoji sets.

This topic has also been discussed in:

https://github.com/Ranks/emojione/issues/68

And from what I understood from @kevinranks comments, one of the main goals of Emoji One is to be as interoperable with other popular Emoji sets as possible.

I hope it will stay like that.

So please don't change it.

Regards

**Comment by pauldhunt** [comment]
There is currently some discussion about creating a new/separate Unicode character for the express purpose of showing the 8 ball (because it has popularly 'poached' the billiards code point), but IF that happens, it probably won't make it into the standard until Unicode 9.0, which is still probably another year out.

**Comment by wp9015362** [comment]
> @pauldhunt wrote:
> 
> There is currently some discussion about creating a new/separate Unicode character for the express purpose of showing the 8 ball

It would have been nice if you would have provided a source for that.

Anyway, as far as I understand, the situation is actually a bit different.

With "discussion", I assume you were referring to this page:

http://www.unicode.org/review/pri294/feedback.html

As far as I can tell, this page merely presents some public feedback.

And the feedback is in regard to this:

http://www.unicode.org/review/pri294/pri294-emoji-image-background.html

And it clearly says:

> [...] The following is a list of proposed Unicode chart glyph and/or annotations changes for many emoji characters​, to promote better interchange across platforms.
> 
> [...]
> 
> Code: 1F3B1
> Name, 7.0 annotations: BILLIARDS
> Proposed annotation additions for 8.0
(unless otherwise noted): commonly depicted using just an 8-ball
> Notes: Change the chart glyph to show just an 8 ball. Lends itself to more usage.
> [...]

So, as far as I can tell, the plan for Unicode 8.0 actually is to change the "billards" glyph to just show an 8 ball.

And the "discussion" you are talking about is simply a private individual which has complained about this plan via the feedback form.

So, Emoji One using an 8 ball for the "billiards" Emoji is perfectly fine and actually goes hand in hand with the plans for Unicode 8.0.

At least as far as I can tell.

Regards

**Comment by pauldhunt** [comment]
the discussion i was referring to was on the Unicore list, which i have access to as a member of the Unicode consortium (which is a relatively new thing so i’m still learning). i didn’t realize it was a closed list until i checked just now. at any rate, this will sort itself out, but as a font developer it is generally agreed upon that Unicode poaching is bad practice and it is usually preferable to ‘do the right thing’, where the right thing is representing glyphs as described in the standard. this is not to say there is not room for interpretation of how best to represent an emoji (or a letter for that matter), but sometimes people get it wrong, even if it’s Apple or Twitter.

**Comment by pauldhunt** [comment]
just a snippet from that convo:
The Japanese carrier emoji were clearly about the game (“ビリヤード” 「biriyaado」) and not an 8 ball with its fateful or bad luck connotations.
You can view the original Japanese carrier artwork here (entry 470): 
http://trialgoods.com/emoji/?career=au&page=all
to me using the 8 ball is a very US-centric approach to representing this character.

**Comment by wp9015362** [comment]
> @pauldhunt wrote:
> 
> just a snippet from that convo:
> ‘The Japanese carrier emoji were clearly about the game (“ビリヤード” 「biriyaado」) and not an 8 ball with its fateful or bad luck connotations.’

But Apple, Twitter and LG still use an 8 ball to depict the "billiards" Emoji.

Those are very popular Emoji sets.

And as far as I understand, Emoji One was designed around the idea to be as interoperable with other popular Emoji sets as possible.

This is a very good design decision IMHO.

Everything else would lead to the issue that Emojis can get lost in translation, as described in the following article for example:

http://www.huffingtonpost.com/2014/06/27/emoji-meaning_n_5530638.html

So, I really like that Emoji One tries to be as interoperable with other popular Emoji sets as possible.

I hope it won't change.

Personally, I don't really care about the Unicode standard and about if the "billiards" Emoji shows an 8 ball or a racket set of colored balls.

What I care about is that different Emoji sets are as interoperable with each other as possible and that Emojis can't get lost in translation.

The current Emoji situation is a total mess IMHO (http://www.huffingtonpost.com/2014/06/27/emoji-meaning_n_5530638.html).

Currently there are  so many different Emoji sets out there which all look different from each other.

How is that a "standard"?

If I were to decide, then there should only be one single Emoji set and not so many different Emoji sets.

So, I really think that it is a wise decision from Emoji One to make the Emoji One Emoji set as interoperable with other popular Emoji sets as possible.

The fact is that the arguably most popular Emoji sets currently are using an 8 ball to depict the "billiards" Emoji. So Emoji One doing the same was the best they could have done IMHO.

> @pauldhunt wrote:
> 
> FYI, You can view the original Japanese carrier artwork here (entry 470):
> http://trialgoods.com/emoji/?career=au&page=all

Unicode also has it's own chart showing (and comparing) them, see:

http://www.unicode.org/emoji/charts/full-emoji-list.html

:wink:

Regards

**Comment by pauldhunt** [comment]
what you are wishing for (complete interoperability/one emoji set to rule them all) is nonsense, but I will refrain from engaging further because I feel like we have already ventured into trolling territory. i��ve said my $.02, and I��ll leave it at that.

**Comment by mikebe11** [comment]
Some good points made here. The 8 ball has somewhat solidified it's place in the billiards space so we won't be making a change, even if it doesn't quite fit the standard description. It's not our intention to promote bad practices but sometimes we do follow the herd, at least in this case, for now.
Hopefully there is a dedicated 8 ball emoji someday soon, so not only us but every large set out there will be representing the Unicode standard.
