### ISSUE TITLE
U+1F42E COW FACE is indistinct

### ISSUE THREAD

**Issue by pauldhunt** [Ranks/emojione#108]
Even as someone who grew up on a dairy farm, I do not see a strong enough resemblance.

**Comment by wp9015362** [comment]
Hello,

the "cow face" Emoji One Emoji:

![Image](https://github.com/Ranks/emojione/raw/master/assets/png/1F42E.png)

indeed is not that easy to recognize as a cow.

Suggestions:

- Maybe changing the fur color from solid gray to a black and white mottling could help.
- Maybe changing the color of the horns from orange to something more realistic like gray for example could help. Cows do not have orange horns in reality.

Regards
