### ISSUE TITLE
U+1F645 NO GOOD 

### ISSUE THREAD

**Issue by puiterwijk** [Ranks/emojione#109]
The no_good (U+1F645) icon looks more like \o/ in Emoji One to me if represented small as the mouth is very hard, to impossible, to see: it looks more like a very enthusiastic person to me.

When looking at other implementations of this character (http://emoji.codes/family?c=objects), I think only the Emoji One version is unclear.

**Comment by wp9015362** [comment]
> @puiterwijk wrote:
> 
> http://emoji.codes/family?c=objects

The link to the emoticons category is:

http://emoji.codes/family?c=emoticons

> @puiterwijk wrote:
> 
> The no_good (U+1F645) icon looks more like \o/ in Emoji One to me if represented small as the mouth is very hard, to impossible, to see: it looks more like a very enthusiastic person to me.
> 
> When looking at other implementations of this character (http://emoji.codes/family?c=objects), I think only the Emoji One version is unclear.

I agree.

In pretty much all the other Emoji sets, the "no good" Emoji has crossed arms.

But in Emoji One it has open arms, see for example:

Apple:

:no_good:

Emoji One:

![Image](https://github.com/Ranks/emojione/raw/master/assets/png/1F645.png)

Regards

**Comment by mcfiredrill** [comment]
It looks like maybe they were intended to be drawn crossed, since the hands kind of look like the palms are on the outside? Regardless, its hard to tell. 

Maybe it would be easier to recognize as crossed arms if the angle of the arms was changed slightly.
