### ISSUE TITLE
seahorse emoji suggestion

### ISSUE THREAD

**Issue by diomed** [Ranks/emojione#111]
i'd like to suggest a seahorse emoji

blue, per chance

looking something like this. or maybe 2 versions (left & right side).

![+](http://ak1.polyvoreimg.com/cgi/img-thing/size/l/tid/24974632.jpg)

**Comment by mikebe11** [comment]
Thanks for the suggestion. The emoji we use in our collection are part of the Unicode standard and are found in their charts. The seahorse is not included in there. In trying to maintain an interoperable set we prefer to stay away from adding custom items. Although we do encourage users to customize our package for their project's needs.
A seahorse emoji would look pretty cool. You may want to suggest it to the Unicode Consortium for a future release.

**Comment by Crissov** [comment]
https://github.com/Crissov/unicode-proposals/issues/176
