### ISSUE TITLE
Any plans for :simple_smile:?

### ISSUE THREAD

**Issue by jeberly** [Ranks/emojione#114]
Hi all,

Any plans to support :simple_smile: ?  All the other smileys are too smiley imo :)

**Comment by waldyrious** [comment]
See discussion at #50. For the record, I agree that a simple smile emoji is needed.

**Comment by mikebe11** [comment]
@jeberly  The closest plan for that would be the Unicode 7 addition of 'SLIGHTLY SMILING FACE' (U+1F642). It may be the simple smiling smiley that many people desire. That will be included in a future release.

**Comment by jeberly** [comment]
Thanks guys. Any timeline on Unicode 7 addition?  You can close this issue I guess.

**Comment by mikebe11** [comment]
Hard to say exactly when. We're shooting for sometime this summer. We started to update some of the emoji and then made a decision to update some more, then some more. As soon as everything has been polished up we'll release it. Thanks jeberly.
