### ISSUE TITLE
emoji.codes source?

### ISSUE THREAD

**Issue by stuartpb** [Ranks/emojione#119]
Is the source for emoji.codes on GitHub? I wanted to write pull requests for a few useful features:

- Preserving the search filter when jumping from the cheat sheet to the family page and vice versa
- Linking on the Family Tree page (I was looking to show somebody how :smiling_imp: isn't smiling in the Google version)
- Converting the main page to copy using Unicode code points when toggled from Emoji One to Apple mode

**Comment by wp9015362** [comment]
The answer to your question is in:

https://github.com/Ranks/emojione/issues/58

Regards

**Comment by mikebe11** [comment]
@stuartpb No, we don't have the source for emoji.codes on GitHub. Currently emoji.codes has some db integration in it. We don't have time and resources at the moment to strip it and package it up. Perhaps someday. It's not on the current list of plans. Right now we have updates to incorporate into the repo files and into the websites.
We greatly appreciate the interest and the offer. The features you mention are good ideas.
