### ISSUE TITLE
emojione python/django library

### ISSUE THREAD

**Issue by kavirajk** [Ranks/emojione#120]
It is good to have python/django library for emojione.

**Comment by kavirajk** [comment]
What is unicode regexp to include all emojis in python? I have tried same unicodeRegexp used in javascript lib, But seems like not working.

**Comment by mikebe11** [comment]
Sorry, but we don't know python. I looked into the python regex a little and also messed around with some online regex testers. I was unable to get anything working on them. Hopefully someone more experienced with python can assist here.

**Comment by kavirajk** [comment]
unicode_regex = u'[\U0001f300-\U0001f5ff\U0001f600-\U0001f64f\U0001f680-\U0001f6ff\u2600-\u26ff\u2700-\u27bf]+'

This seems to be working for most the emojis I tested so far..

**Comment by mikebe11** [comment]
Great. Looks very similar to what was suggested here. 
http://stackoverflow.com/questions/393843/python-and-regular-expression-with-unicode
The \U000 bit is new to me.

**Comment by kavirajk** [comment]
But still this regex fails for emojis like u'0\u20e3', u'8\u20e3', u'9\u20e3', u'9\u20e3', u'1\u20e3', u'2\u20e3'. I just used the same regex used in javascript library after changing that regex to unicode string. It works for all emoji present in emojione.👍

**Comment by mikebe11** [comment]
excellent :+1:

**Comment by mikebe11** [comment]
@kavirajk Gonna close this issue since you've submitted a python library. I know it hasn't been merged yet but once it's all set we'll bring it in.
