### ISSUE TITLE
Moon looks like Sun  🌝

### ISSUE THREAD

**Issue by ck-on** [Ranks/emojione#122]
This is supposed to be the moon 🌝  FULL MOON WITH FACE 

Looks like the sun in emojione

In fact all the moon symbols in emojione use bright yellow instead of grey like twitter set, etc.

🌝🌓🌔🌕🌖🌗🌘🌜🌛🌙

**Comment by wp9015362** [comment]
No, I disagree.

Please do not make the moon gray.

Yes, in the Twitter "Twemoji" Emoji set, the moon is gray. But there actually is an open issue on the Twemoji GitHub issue tracker which explicitly asks for the moon to be changed from gray to yellow, see:

https://github.com/twitter/twemoji/issues/72

And all other popular Emoji sets have the moon yellow, see:

http://emoji.codes/family

So, it should stay yellow in Emoji One as well IMHO.

**Comment by ck-on** [comment]
@wp9015362 The moon is a cold rock, it doesn't produce light like the sun. It should not be yellow.

Go outside some night with a full moon and look at the reflected light and see if you can spot ANY yellow.

Just because Apple made a dumb design decision doesn't mean everyone should copy it.

Twitter had the right idea.

**Comment by ck-on** [comment]
Oh wait a minute, I just realized Ranks was cool enough to include the SVG files.

I can write an optional patch for anyone to use to turn the moons silver/grey or leave them as is, and then just re-render the png via inkscape or imagemagick.

This is definitely the best emoji set so far, hope they go all the way with Unicode 8 support after August and include the skin tones (but even that could be done right now via a SVG patch too)

**Comment by mikebe11** [comment]
Thanks for the design note. At this time we aren't updating the current collection so this moon's color won't be changed. We're in the process of creating an entire new collection due out late this year. We'll keep the grey moon in mind for it. I'm glad to hear you found the SVGs and were able to put something together to meet your needs. Thanks so much for sharing the SVG patch.
