### ISSUE TITLE
Emoji One 2.0 (Emoji Two)?

### ISSUE THREAD

**Issue by wp9015362** [Ranks/emojione#126]
Hello,

in some recent comments, you wrote that you have stopped development for the current Emoji One 1.5 set and that you are working on an entirely new set due to be released in Q4 2015, see for example:

https://github.com/Ranks/emojione/issues/123#issuecomment-127505506
https://github.com/Ranks/emojione/issues/122#issuecomment-127456144

May I ask what's the goal of this new Emoji set?

What's going to be different about it? 

And will it be called Emoji Two? Or just Emoji One 2.0?

Any chance we could see a preview of it (even if it might still be a work in progress)?

Regards

**Comment by wp9015362** [comment]
PS:

Oops!

I just had a look at:

http://emojione.com/

and saw the preview images for "The 2016 Collection" including a link to:

https://instagram.com/emojione/

I also saw that you have joined the Unicode Consortium:

http://emojione.com/blog/emoji-one-joins-unicode-consortium/

But "The 2016 Collection" seems to look rather different now...

A design goal of Emoji One was to look similar to the Apple set, see:

https://github.com/Ranks/emojione/issues/68#issuecomment-93861096

Is that no longer being the case for "The 2016 Collection"?

Regards

**Comment by wp9015362** [comment]
Sorry, but I already had to submit the first issue for "The 2016 Collection" before it has even been released, see:

https://github.com/Ranks/emojione/issues/127

It's rather disappointing that Emoji One does no longer seem to have a design goal to look similar to other popular Emoji sets.

It was the main reason I liked Emoji One.

Regards

**Comment by mikebe11** [comment]
Hello,
The founder has an interest in participating more in the development of emoji at the standards level, hence Emoji One has joined The Unicode Consortium. He'd also like to continue developing the brand. Part of that is with a new collection with a different style. Those are the general goals at the moment.
There are no plans for a name change. The new art will most likely be V2.0.

**Comment by mikebe11** [comment]
Going to close this issue now that v2 has been released. We ended up just going with a version bump to v2.0.0. Anyone reading this looking for our emoji from v1.5.2 can find them in this repository.

https://github.com/Ranks/emojione-legacy
