### ISSUE TITLE
"Heart eyes" Emoji from "The 2016 Collection" looks somewhat horny, but doesn't look horny in other popular Emoji sets

### ISSUE THREAD

**Issue by wp9015362** [Ranks/emojione#127]
Hello,

the "heart eyes" Emoji from ["The 2016 Collection"](https://github.com/Ranks/emojione/issues/126) (source: http://emojione.com/):

![Image](https://cloud.githubusercontent.com/assets/7558360/9832039/d8cdc4fe-596e-11e5-921d-2612f3f5b08a.png)

looks somewhat horny.

But it does not look horny in other popular Emoji sets. In other Emoji sets, the "heart eyes" Emoji simply seems to be in love.

IMHO it looks horny because it shows it's tongue.

The tongue is not shown in any other popular Emoji sets

Apart from that, it still suffers from the following issue:

https://github.com/Ranks/emojione/issues/64

Could you please fix it?

Regards

**Comment by wp9015362** [comment]
PS:

As already mentioned in https://github.com/Ranks/emojione/issues/128, I have edited the Emoji a bit (with Paint :laughing: ) to do a comparison:

Before:

![Image](https://cloud.githubusercontent.com/assets/7558360/9832039/d8cdc4fe-596e-11e5-921d-2612f3f5b08a.png)

After:

![Image](https://cloud.githubusercontent.com/assets/7558360/9832348/135b5c9a-5978-11e5-9431-576130adf359.png)

As you can see, I have removed the tongue, which already looks better (IMHO).

I think the teeth could also be removed, but then the mouth also would need to be made a bit smaller IMHO.

And, as already mentioned in https://github.com/Ranks/emojione/issues/128, I have also changed the colors a bit (with Paint :laughing: ).

I have used the colors from the Google Material Design Color Palette, see:

https://www.google.com/design/spec/style/color.html#color-color-palette

I think it looks better.

What do you think?

Regards

**Comment by mikebe11** [comment]
Hello,
Thank you for the suggestion. There's no guarantee suggestions will be adopted but the designers do see them and take them into consideration. The emoji mentioned here, and all the other smileys, were run through another round of revisions. Here's the final, unless it gets another pass before launch (probably not).

![heart_eyes](https://cloud.githubusercontent.com/assets/9707818/10028847/9b4d5bb4-6123-11e5-89ea-923082b1cc42.png)

**Comment by mikebe11** [comment]
@wp9015362  Just a heads up that this issue and the next design issue are being closed. The designers saw them both as they were submitted. Here's what we have for the final. It did change a little from the last final. As unlikely as it is there's always a possibility for further change.
Thanks for the suggestions.
![screen shot 2015-10-14 at 4 48 12 pm](https://cloud.githubusercontent.com/assets/9707818/10501266/701a5456-7294-11e5-9ef7-48a40e604228.png)
