### ISSUE TITLE
Colors of Emoji faces in "The 2016 Collection" are quite pale (suggestion for improvement inside)

### ISSUE THREAD

**Issue by wp9015362** [Ranks/emojione#128]
Hello,

the colors of the Emoji faces from ["The 2016 Collection"](https://github.com/Ranks/emojione/issues/126) as depictured on the preview on http://emojione.com/:

![Image](https://cloud.githubusercontent.com/assets/7558360/9832039/d8cdc4fe-596e-11e5-921d-2612f3f5b08a.png)

are quite pale IMHO.

I have changed the colors a bit (with Paint :laughing: ), which I think looks better, see:

![Image](https://cloud.githubusercontent.com/assets/7558360/9832348/135b5c9a-5978-11e5-9431-576130adf359.png)

I have used the colors from the Google Material Design Color Palette, see:

https://www.google.com/design/spec/style/color.html#color-color-palette

I think it looks better.

What do you think?

PS:

The edited picture also has it's tongue removed, as discussed in issue https://github.com/Ranks/emojione/issues/127.

Regards

**Comment by wp9015362** [comment]
PS:

For the record:

For the edited picture, I have used the following colors from the [Google Material Design Color Palette](https://www.google.com/design/spec/style/color.html#color-color-palette):

- Face: Yellow 700 (#FBC02D)
- Heart eyes: Red 700 (#D32F2F)
- Mouth: Brown 700 (#5D4037)
- Teeth: White (#FFFFFF)

Regards

**Comment by mikebe11** [comment]
Hello,
Thanks again for the input. The final smileys did get an overall color change. This is a sample of what was chosen. It could still change before launch but probably not.

![heart_eyes](https://cloud.githubusercontent.com/assets/9707818/10029155/4bba4650-6125-11e5-91fa-cda1561cd8ab.png)

**Comment by mikebe11** [comment]
As mentioned in #127 this suggestion's been viewed and this issue's being closed too.
The current final:
![screen shot 2015-10-14 at 4 48 12 pm](https://cloud.githubusercontent.com/assets/9707818/10501359/7ed37288-7295-11e5-99a1-89d881bf6151.png)
Thanks for all the support.
