### ISSUE TITLE
Meteor package not found

### ISSUE THREAD

**Issue by lieuwex** [Ranks/emojione#129]
`meteor add emojione:emojione` doesn't work since the package hasn't yet been published to Atmosphere (https://atmospherejs.com/emojione/emojione also gives a 404).

Am I missing anything, or hasn't the packaged been [published](https://atmospherejs.com/i/publishing) yet?

**Comment by mikebe11** [comment]
It hasn't been published yet. That should be taken care of soon. For now, the following should still be good.
```meteor add qnub:emojione```

**Comment by lieuwex** [comment]
Alright, thanks!

**Comment by mikebe11** [comment]
You're welcome. Once the package is published our readme will be updated with the new command.
