### ISSUE TITLE
JS not processing on HTML

### ISSUE THREAD

**Issue by selfagency** [Ranks/emojione#130]
i'm trying to use emojione in my rails application and installed it via the gem from @dimelo. unfortunately, i can't seem to get it working for the life of me.

presently, in my code, i am loading the `emojione.js` after `jquery.js` and before `global.js` where i am invoking the [html conversion class](http://git.emojione.com/demos/1.5.0/class-convert.html).

```HTML
<script src="/assets/jquery.js?body=1" type="text/javascript"></script>
...
<script src="/assets/emojione.js?body=1" type="text/javascript"></script>
...
<script src="/assets/global.js?body=1" type="text/javascript"></script>
...
<script src="/assets/application.js?body=1" type="text/javascript"></script>
```

here is my conversion code (which is wrapped in a larger document ready function).

```javascript
$(".convert-emoji").each(function() {
  var original = $(this).html();
  var converted = emojione.shortnameToImage(original);
  $(this).html(converted);
});
```

and here is my html.

```HTML
<div class="main convert-emoji">
  <p>:poop:</p>
</div>
```

i simply do not understand why my :poop: stays `:poop:` on the frontend no matter what i do. there are no related js errors in my console. why isn't this :poop: working?!

**Comment by mikebe11** [comment]
I'm not sure what's going on. The code is clear. Is the conversion code definitely getting called? I took your pieces, dropped them into a very stripped down page and the conversion worked fine. I didn't mimic the `<script>` structure you have there though.
My only recommendation is to drop a breakpoint in your browser inspector or add `debugger;` and step through it. While debugging check _emojione_ in the console and make sure you have an object.
```javascript
$(".convert-emoji").each(function() {
  debugger;
  var original = $(this).html();
  var converted = emojione.shortnameToImage(original);
  $(this).html(converted);
});
```

**Comment by selfagency** [comment]
I figured this one out. I think I just needed to restart my rails server.

**Comment by mikebe11** [comment]
That's great to hear. Thanks for the follow up.
