### ISSUE TITLE
Normalize filenames to be compatible with Twemoji and gemoji

### ISSUE THREAD

**Issue by JoshyPHP** [Ranks/emojione#133]
[Twemoji](https://github.com/twitter/twemoji/tree/gh-pages/36x36)'s filenames are lowercase without leading zeroes, e.g. [23-20e3.png](https://github.com/twitter/twemoji/blob/gh-pages/36x36/23-20e3.png)
[gemoji](https://github.com/github/gemoji/tree/master/images/emoji/unicode)'s filenames are lowercase with leading zeroes, e.g. [0023-20e3.png](https://github.com/github/gemoji/blob/master/images/emoji/unicode/0023-20e3.png)
Emoji One's filenames are uppercase with leading zeroes, e.g. [0023-20E3.svg](https://github.com/Ranks/emojione/blob/master/assets/svg/0023-20E3.svg)

If you use new URLs for the next major version I think it would make sense to normalize the filenames to lowercase, to be somewhat compatible with Twemoji and gemoji. I think that dropping the leading zeroes would be nice too. With identical filenames (basenames) the difference between a Twemoji image and an Emoji One image would only be in the path to the file and it would make it a bit easier for an application to support both sets.

That's only if the next version comes with new URLs though. Otherwise I'm not sure this is worth the hassle.

**Comment by rodrigopolo** [comment]
That is an easy one!

**Comment by rodrigopolo** [comment]
Here... a list of commands to rename the SVG and PNG assets:
http://pastebin.com/iuCS5dKu
http://pastebin.com/1pCDmPJ5

**Comment by mikebe11** [comment]
@JoshyPHP That's not a bad idea to change filenames to lowercase. I don't think we'd go with dropping the leading zeros. For that we'd probably prefer to stick with names as close to the formal Unicode code point as possible. But the case change is worth considering.
We haven't really thought about what's happening for the new release yet. We need to make sure everything is covered in a filename change, like considering current sites/apps that use the CDN assets. We don't want to break things on their end.
This is good. We'll most likely try to squeeze it in on the next big update. Thanks.

**Comment by mikebe11** [comment]
@rodrigopolo Thanks for the list of commands. It'll be handy in the near future.

**Comment by robin0van0der0v** [comment]
'Somewhat compatible' is a weird statement. The filenames can be compatible or they can be incompatible, they cannot be somewhat compatible. I would say that the current filesnames are perfect, this is exactly the same way as Unicode documents in in their documentation: leading zeros and uppercase.

**Comment by JoshyPHP** [comment]
You're arguing about semantics with a false dichotomy. As I recall, there are about ~12 emoji whose filenames start with a zero, out of thousands. The other 99% of the filenames would be identical in lowercase. I don't have the exact percentage because different versions of Twemoji and Emoji One support a slightly different set of emoji. And since every other library and program support a slightly different set emoji, should we say that none of them are compatible with any other? Is there a single emoji set that support 100% of the Unicode standard? I don't think so. Are we to say that there is no library of emoji set compatible with Unicode's emoji standard? Of course not, that would be ridiculous.

> the same way as Unicode documents in in their documentation: leading zeros and uppercase.

Is this the part where I pointlessly argue that the [Unicode Data for UTR \#51](http://unicode.org/Public/emoji/1.0/emoji-data.txt) uses spaces and not dashes, making it incompatible as per your interpretation of the word?

**Comment by JoshyPHP** [comment]
There is no two emoji set that are 100% compatible with each other. I am not aware of any emoji set that covers 100% of UTR \#51.

> this is exactly the same way as Unicode documents in in their documentation: leading zeros and uppercase.

Not *exactly*. [The files published by Unicode](http://www.unicode.org/Public/emoji/2.0/emoji-sequences.txt) use spaces to separate codepoints, not dashes.

**Comment by robin0van0der0v** [comment]
> Not *exactly*. [The files published by Unicode](http://www.unicode.org/Public/emoji/2.0/emoji-sequences.txt) use spaces to separate codepoints, not dashes.
Then the filenames are currently not completely like the Unicode filesname, but if we change all dashes to spaces, then it is fully in line with the Unicode specification.

**Comment by JoshyPHP** [comment]
> not completely like

Or "somewhat compatible" if you will.

**Comment by robin0van0der0v** [comment]
> Or "somewhat compatible" if you will.

Okay then. The filenames are currently ~~not completely like~~ *somewhat compatible with* the Unicode filesnames, but if we change all dashes to spaces, then it is fully ~~in line~~ *compatible* with the Unicode specification.

**Comment by JoshyPHP** [comment]
*Fully* compatible? Sure, if you accept that filenames don't contain the VS16 (U+FE0F) and ZWJ (U+200D) joiners that are required in [some emoji sequences](http://unicode.org/emoji/charts/emoji-zwj-sequences.html).

**Comment by mikebe11** [comment]
Despite the discussion we're going to close this issue. The naming convention is now set. Thanks everyone for their input here.
