### ISSUE TITLE
Emoji not working with questionmark in the end

### ISSUE THREAD

**Issue by fabianschwarzfritz** [Ranks/emojione#137]
Hola,

On In Rocket.Chat, there is an issue describing https://github.com/RocketChat/Rocket.Chat/issues/967 a string that does not convert to an emoji.

However, this is not a RocketChat, problem, but a functionality that is not working with emojione. I thinks it's better to track that issue here.

Cheers,
Fabian

**Comment by mikebe11** [comment]
Hi Fabian,
This isn't an Emoji One problem. Our library is functioning with the ascii conversion. ":D?" is not in our ascii list. We don't have ":D!" either. If you want to support that ascii smiley in RocketChat you'd have to include it in your program's list of supported ascii combinations.

**Comment by S4KH** [comment]
Hi Mike,

In emojione shortnameToImage function regex replace is not working for :D? but working for ":D!"

**Comment by mikebe11** [comment]
@S4KH  I got it now. Was looking at the ? as a component of the ascii smiley and not as sentence punctuation.

**Comment by mikebe11** [comment]
Should be good here. #135 added the ?
Thanks
