### ISSUE TITLE
shortnameToImage() does not always work in latest release

### ISSUE THREAD

**Issue by bendiksolheim** [Ranks/emojione#143]
Hello,

Your latest release, 1.5.1, breaks `shortnameToImage()` for at least the shortname `:+1:`. I have not tested all of the emojis, but quite a few, and this is the only one I have found not working. I have tried to locate where this error has been introduced, and found the following:
- It works in commit 7ece56c
- Commit 0cbead1 breaks `shortnameToImage()` for all emojis
- Commit b8ed1a8 fixes `shortnameToImage()` again, but it no longer works for the emoji `:+1:`

This specific shortname is still in `emojione.emojioneList`, so it has not been removed. Other similar emojis, like `:-1:`, works just fine. I am guessing that this might have something to do with the character `+`, as this has a very specific meaning in regular expressions.

**Comment by bendiksolheim** [comment]
Testing some more, it does indeed seem like it is the plus sign that gives you trouble. Swapping line 7 in `emojione.js` with the following seems to fix the issue:
```
ns.shortnames = Object.keys(ns.emojioneList).map(function(emoji) {
        if (emoji.indexOf('+') >= 0) {
            emoji = emoji.replace('+', '\\+');
        }
        return emoji;
    }).join('|');
```

I don't think it would create any other problems, but I don't really know your code base either :) I would be happy to provide a pull request if this seems like an OK solution to you.

**Comment by mikebe11** [comment]
@bendiksolheim Thanks for bringing this to light. We gotta get some better JS tests in here. I'd hold off on the PR until all shortnames have been checked. Your fix might be a good start but not cover everything.

**Comment by bendiksolheim** [comment]
A valid point. My fix does not really feel like the "correct" solution either, it seems more like a "hack" to get it working. I have a feeling there must be a better way to do this.

Anyway, keep up the good work, and please don't hesitate to ask if you need input. I'd be happy to contribute.

**Comment by mikebe11** [comment]
I ran through all of the shortnames and aliases. Everything else was fine. The only other non-alphabetic character we use in them is "-". I don't anticipate the community introducing more non-alphabetic chars into them, at least I hope they don't. I will test the diversity shortnames we have as well. They aren't in 1.5.1. I don't believe they'll be an issue. Their composition is simple.

Do you have any thoughts about a more general fix? If you've got the time we'd love your input. User input/assistance is always appreciated and valuable to us.

MDN offers a snippet to check out. It covers more than probably needed but could easily be thinned out.
```
function escapeRegExp(string){
  return string.replace(/[.*+?^${}()[\]\\]/g, "\\$&");
}
```

**Comment by bendiksolheim** [comment]
If it was found on MDN (more precisely here, it seems: https://developer.mozilla.org/en/docs/Web/JavaScript/Guide/Regular_Expressions), I don't see any reason not to trust it. It covers a bit more characters than needed, but I doubt that really will be a problem. You could always test, but I doubt there will be any real performance differences between checking for all of those characters and just the plus sign. The good thing is that you'll be more or less future proof if you use that one.

**Comment by mikebe11** [comment]
@bendiksolheim I couldn't agree more. I tested it with a version of your first fix, using the map() function and it worked well, just removing the indexOf() check and stripping out the other characters except "+". Nice and clean, just takes one line. And you're right, it covers new characters added in the future.
Since you found the bug would you like to revise your first fix and submit a PR? If not, no problem, just let me know and I'll take care of it.
Thanks

**Comment by bendiksolheim** [comment]
If you have the time, I think it's best if you fix it. My week looks quite busy, so I won't have the time to come up with a PR the first few days.

Thanks for the quick responses!

**Comment by mikebe11** [comment]
I pushed the fix so I'm closing this issue. Thanks for the help!
