### ISSUE TITLE
emoji picker and emoji preview on textarea ?

### ISSUE THREAD

**Issue by leizard** [Ranks/emojione#144]
Hi,
I want to have an emoji picker and live preview emoji on textarea input. In short, like this one:
http://one-signal.github.io/emoji-picker/
Does anyone have an idea to implement ?
Thank you.

**Comment by mikebe11** [comment]
Hi,
Any reason not to use and alter that product for your needs? I didn't look deep into it but if the license is acceptable you could swap out their sprite sheets, tweak some code and use that. It looks pretty good.

**Comment by mikebe11** [comment]
@leizard  Going through some issues here and checking in. Any progress on implementing this?

**Comment by leizard** [comment]
Hi. Sorry for late reply. I just make my own emoji picker with a simple dropdown panel. Does not implement live preview yet

**Comment by mikebe11** [comment]
Take a look here. Maybe one of the extras will help out.
http://git.emojione.com/demos/2.0.0/

**Comment by mikebe11** [comment]
@leizard This issue has been in-active so I'm going to close it. We've offered all we have with respect to a picker or live preview. 
Here's one of many React pickers that may be helpful to you.
https://github.com/tommoor/emojione-picker

**Comment by joelcuevas** [comment]
I found this very useful: http://mervick.github.io/emojionearea/.

**Comment by kamov** [comment]
Thanks @joelcuevas looks good that

**Comment by leizard** [comment]
Thank you @joelcuevas  I will try that
