### ISSUE TITLE
Release work-in-progress assets on GitHub

### ISSUE THREAD

**Issue by metavida** [Ranks/emojione#150]
I'd love if you'd consider releasing your work-in-progress emoji on GitHub in order to enable community members to help actively build the Emoji One project.

I really want/wanted to help contribute design and development time to improve the Emoji One project. Specifically, I'm interested in helping ensure that [Unicode 8.0 Diversity features](www.unicode.org/reports/tr51/#Diversity) are supported. 

Unfortunately, what I discovered (after an hour+ of digging) is that there is very active development work on a "v2" collection of emoji and that work is happening in some private space, completely absent on GitHub. Because that work is happening in private:

1. I have no way of knowing what progress you've made with the new v2 Emoji (in my case, specifically Re: diversity)
2. I have no way of contributing, because I only have access to the v1 assets which apparently are soon to be obsolete [[1]]
3. It took actively searching outside of GitHub to finally figure out that v2 Emoji were a thing (I eventually looked at your Twitter feed)

Honestly, to me the whole experience felt like a waste of time. I thought I might be able to contribute because this is an open source project with an active bug tracker and previously merged Pull requests, but ended up wasting my time working to discover that all of your active, core development is not (yet) open.

I know that design by committee is painful/horrible. I'm sure it'd be less easy to market the new Emoji One release if all the new assets were already public. Still, if you're able to figure out some way of pushing your work-in-progress assets to GitHub as quickly as possible it would solve all of the above problems, and I (and other potential contributors) will be able to potentially open a Pull request to aid in the work you're actively doing.

[1]:https://github.com/Ranks/emojione/issues/124#issuecomment-152290765

**Comment by metavida** [comment]
Emoji One's reply to me on Twitter [[1]]

> We appreciate the desire to contribute! We've found that it's most efficient to have a couple in house designers to work an a style that was desired for this set

That's fair. Perhaps this suggestion could be re-purposed then. I suggest you add and maintain a CONTRIBUTING.md file in this GitHub project to clarify which types of contributions you're currently looking for & which aren't as helpful. This document could be updated in the future if/when you begin work on v3 emoji and larger contributions to the currently available emoji versions are not actively needed.

[1]:https://twitter.com/emojione/status/659816254513901568

**Comment by mikebe11** [comment]
@metavida Thank you for sharing your thoughts on the current development. Your idea is pretty fun overall, and I’d love to see something like that created personally, but it’s just not the direction we are headed with Emoji One at this time. There are several reasons that we don't foresee opening up a branch for art development. You hit a couple right on the head. Design by committee is not efficient or desirable here. We don't have the resources to manage such an undertaking or the time to take that on and reach our desired release date. Marketing/licensing is another detail. We own copyright to the collection and will be licensing it in different formats. How that works with multiple contributors is unclear and possibly quite muddy. These are primary reasons we can't fulfill your request.

With regards to the diversity emoji those are already complete. You can see some samples have been posted on our social media accounts. The entire collection is already more than 90% complete. The remaining emoji are some 8.0 emoji that were just recently released. After completing over 1800 already our designers will breeze through those relatively quickly.

I like your idea of adding a CONTRIBUTING.md file to the repo. I am going to leave this issue up as a reminder to compose and add that file.

I’m sorry I didn’t have better news, but we do appreciate you sharing your views. We wish you the best in finding a project that can utilize your skills.

**Comment by wp9015362** [comment]
@metavida :

I definitely understand you, I also think there should have been a bit more communication/transparency from the devs.

But instead of searching on Twitter, you could also have had a look at the following issues:

https://github.com/Ranks/emojione/issues/126
https://github.com/Ranks/emojione/issues/127
https://github.com/Ranks/emojione/issues/128

:wink:

> @mikebe11 wrote:
> 
> The entire collection is already more than 90% complete. The remaining emoji are some 8.0 emoji that were just recently released. After completing over 1800 already our designers will breeze through those relatively quickly.

So, November 2015 still stands as the release date :wink:?

Regards

**Comment by mikebe11** [comment]
@wp9015362  At this moment, yes, November still stands as the release date.

**Comment by mikebe11** [comment]
CONTRIBUTING.md has been added.

**Comment by metavida** [comment]
Thanks for adding that CONTRIBUTING.md file! It definitely resolves the ambiguities that confused me when I first found this project. Also, congrats on the release of the v2 emoji set! They're awesome & I look forward to using them in future projects.

**Comment by mikebe11** [comment]
Thank you for the idea and for the support of our project.
Cheers
