### ISSUE TITLE
Contruction site should be construction site

### ISSUE THREAD

**Issue by morinted** [Ranks/emojione#151]
I was using the strategy and a dictionary to build a tool, and the tool noticed that "construction_site" is entered as "contruction_site". Just an innocent typo that I thought you should know about!

Cheers,
Ted

**Comment by mikebe11** [comment]
Good catch Ted. Thanks for taking the time to let us know about it. We'll get that fixed across all files very soon.
Cheers

**Comment by mikebe11** [comment]
@morinted Fixed. Thanks again!
