### ISSUE TITLE
Categorization 

### ISSUE THREAD

**Issue by grydstedt** [Ranks/emojione#152]
Is categorization that's at http://emoji.codes/ available programmatically somehow (so that someone could implement something similar) ?

**Comment by mikebe11** [comment]
The emoji.json file in this repo has a category property that matches what's on that site.

**Comment by grydstedt** [comment]
Thank you, that helps. When I use that list to render all the emojis, it seems that some that exist in `emoji.json` does not convert to an image. hand_splayed_reverse among others.

**Comment by mikebe11** [comment]
Yeah, you've encountered some that we no longer support. We initially released a larger set of Unicode 7.0. Afterwards the actual list of supported emoji was reduced. Those others are still listed in certain files, like emoji.json. The emoji are still included in the assets. They'll eventually be pulled from here.
The list of supported emoji are the ones you've seen on http://emoji.codes
