### ISSUE TITLE
Improve performance by storing compiled RegEx and reusing

### ISSUE THREAD

**Issue by cs-NET** [Ranks/emojione#154]
The regular expressions used in shortnameToImage, shortnameToUnicode, and shortnameToAscii are currently not stored after being compiled and are recreated \ recompiled with each call.

After updating the library I had noticed a huge performance hit as it was taking over 5 seconds to convert 2000 strings. 

By storing the RegEx in a variable and reusing it resulted in over a 100X increase in performance as it went down to 50 ms. The regexp mentioned are static; only the replaceAll one is dynamic.

     ns.regShortNames = new RegExp("<object[^>]*>.*?<\/object>|<span[^>]*>.*?<\/span>|<(?:object|embed|svg|img|div|span|p|a)[^>]*>|(" + ns.shortnames + ")", "gi");
     ns.regAscii = new RegExp("<object[^>]*>.*?<\/object>|<span[^>]*>.*?<\/span>|<(?:object|embed|svg|img|div|span|p|a)[^>]*>|((\\s|^)" + ns.asciiRegexp + "(?=\\s|$|[!,.?]))", "g");
     ns.regUnicode = new RegExp("<object[^>]*>.*?<\/object>|<span[^>]*>.*?<\/span>|<(?:object|embed|svg|img|div|span|p|a)[^>]*>|(" + ns.unicodeRegexp + ")", "gi");

     ns.shortnameToAscii = function (str) {
     ...
     str = str.replace(ns.regShortNames, function (shortname) { ...

Am I missing something obvious as to why they are not currently stored and reused?

**Comment by mikebe11** [comment]
I'll ask about this, but there's no reason that I'm aware of. You've got me curious now. I'll have to benchmark those two versions and see what the performance difference is.
Most users probably don't convert that many strings at one time, particularly with the js library. Perhaps that was the thought in the initial stages of development.

**Comment by mikebe11** [comment]
@cs-NET  Tested your note here with a regular loop and also benchmark.js. You're right, the performance difference is significant with a large amount of conversions. I still haven't come across a reason why this isn't already implemented.
Since you brought this to our attention would you like to put this change together in a pull request and submit it? Your variable names used in your example would be good. If not, no problem, just let us know and we'll take care of it.
Thanks

**Comment by cs-NET** [comment]
@mikebe11 I created pull request #184 look forward to seeing it implemented!

**Comment by mikebe11** [comment]
@cs-NET Just merged it. Thanks a lot for the submission!
