### ISSUE TITLE
Error in the bower.json file

### ISSUE THREAD

**Issue by monttda** [Ranks/emojione#156]
There is an error in the bower.json file in the main declaration it has an extra ':' in it.

It has 

```
"main:": [
    "assets/css/emojione.css",
    "lib/js/emojione.js"
  ]
```
and it should be

```
"main": [
    "assets/css/emojione.css",
    "lib/js/emojione.js"
  ]
```
https://github.com/rails-assets/rails-assets/issues/256

**Comment by mikebe11** [comment]
@monttda  Thank you very much for bringing that to our attention. The extra semicolon has been removed.
