### ISSUE TITLE
Composer example is wrong on website

### ISSUE THREAD

**Issue by Soullivaneuh** [Ranks/emojione#162]
http://emojione.com/developers

Actually:

```json
"require": { "emojione/emojione": "dev-master" }
```

Should be: 

```bash
$ composer require emojione/emojione
```

* Use command line
* dev-master is unsafe
* Do not specify version. According to [semver](http://semver.org/), composer will choose the best one automatically.

**Comment by mikebe11** [comment]
@Soullivaneuh Thanks for mentioning that. It came just a bit before the launch of our new site so that message is now gone. We appreciate you taking the time to help out though.

**Comment by Soullivaneuh** [comment]
You're welcome. Nice new design BTW! :+1:
