### ISSUE TITLE
Normalize filename case in 'png' directory

### ISSUE THREAD

**Issue by mimecuvalo** [Ranks/emojione#163]
Currently, there's mixed case which makes it difficult to work with these files on OSes that are case-sensitive.  This happens in this directory: https://github.com/Ranks/emojione/tree/master/assets/png

<img width="523" alt="screenshot 2015-12-17 19 21 07" src="https://cloud.githubusercontent.com/assets/469604/11888532/5c33a6d6-a4f3-11e5-82ea-9fc67ebdd66b.png">

**Comment by mikebe11** [comment]
Our apologies. In the hectic time preparing for release today across sites and this repository the care we would have preferred to take here wasn't possible.
The filenames have been normalized. Thank you.

**Comment by mimecuvalo** [comment]
Absolutely no worries!  Thank **you** and congrats on the 2.0 release - you've done incredible work!!  😄
