### ISSUE TITLE
Changes and inconsistencies in assets/* file names (upper/lower cases)

### ISSUE THREAD

**Issue by ping** [Ranks/emojione#164]
I noticed the assets file names have changed between v1.5 and v2. In this recent commit 2861b0aa4f258500fb1771c839a242fc4c0ae5ed the file name in ``assets/png/`` have been changed to lower case.

I'm concerned how this affects the hosted CDN version. For v1.5, the file names are in uppercase and the assets/ path on jsdelivr is not versioned, example ``//cdn.jsdelivr.net/emojione/assets/png/``. If this lowercased names version is pushed to the CDN, I'm concerned this will break sites using v1.5 which expects uppercased file names. Perhaps @jimaek can chime in on this for jsdelivr.

Also, while ``assets/png/*`` are lowercased, ``assets/svg/*`` are uppercased. I haven't tested it, but a cursory look at the js lib tells me that this will break things.

**Comment by jimaek** [comment]
Right now both cases are present, so nothing will break. There would be problems if they decided to remove files. Adding files is safe.

**Comment by mikebe11** [comment]
@ping The decision to change all files to the new collection was made but we did put both cases up on the CDN as @jimaek mentioned. This repository's assets have also been normalized. In the rush of launch day we did encounter a period where there were mixed cases.
