### ISSUE TITLE
Unable to Install TTF

### ISSUE THREAD

**Issue by GaryMilne** [Ranks/emojione#167]
The TTF file will not install on either a Windows or MAC machine.  Is this expected behavior?  I have tried the TTF from both your site (zipped) and GitHub with the same result.

**Comment by nclm** [comment]
I believe the TTF uses Google’s [embedded PNG in OpenType](https://github.com/googlei18n/color-emoji) format, which is roughly only compatible with Android.

To be compatible with Windows, it would need to be in Microsoft’s [layered glyphs format](http://typography.guru/journal/windows-color-fonts/), and for Mac OS and iOS in Apple’s own embedded PNG format.

The state of colour font formats is still a mess!

**Comment by GaryMilne** [comment]
O.K. Thanks for the response.  I plan to use it on Android but it's nice to
be able to view them in other ways.

Great job by the way.

On Sat, Dec 19, 2015 at 2:16 AM, nicolas <notifications@github.com> wrote:

> I believe the TTF uses Google’s embedded PNG in OpenType
> <https://github.com/googlei18n/color-emoji> format, which is roughly only
> compatible with Android.
>
> To be compatible with Windows, it would need to be in Microsoft’s layered
> glyphs format <http://typography.guru/journal/windows-color-fonts/>, and
> for Mac OS and iOS in Apple’s own embedded PNG format.
>
> The state of colour font formats is still a mess!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Ranks/emojione/issues/167#issuecomment-165960089>.
>



-- 
Gary Milne
E-Mail: GaryJMilne@gmail.com

**Comment by thinkrick** [comment]
Closing this one.  Thanks for helping out @nclm !
