### ISSUE TITLE
Linux font?

### ISSUE THREAD

**Issue by nclm** [Ranks/emojione#169]
Hi,

[font/README.md](/Ranks/emojione/blob/master/assets/font/README.md) mentions upcoming Linux fonts. What is the plan for these, which format is considered?

I’m quite [interested](http://probablement.net/txt/emojilinux) in getting full colour Emoji working on Linux, Emoji One would be a great choice as a default set in distributions, and I’m wondering how this could work.

**Comment by thinkrick** [comment]
Hi there.  We're very interested in working with Linux companies or developers who can create compatible fonts.  It's beyond our capabilities in-house, but we do plan on contacting them to see about packaging Emoji One as an optional emoji font or even default.

Stay tuned.  :)

**Comment by nclm** [comment]
Hi Rick,  
Thanks for your answer :)

I’m really looking forward to this ! The state of emoji support on Linux quite lags behind comparing to Mac OS or Windows; I like to believe Emoji One could be a solution. Thanks for doing this!

**Comment by mavit** [comment]
I tried `emojione-android.ttf` and `emojione-apple.ttf` on Fedora 22, and both worked, albeit in greyscale.  This is expected, since upstream Cairo lacks support for full-colour fonts (see, e.g., https://lists.fedoraproject.org/pipermail/fonts/2014-January/001663.html).

I'd like to look at packaging Emoji One for Fedora if I find time.  How are these TTF files built from the images?

**Comment by eosrei** [comment]
I'm excited, I've been learning and working on this for weeks. I just pushed it live a few minutes ago: https://github.com/eosrei/emojione-color-font A color emoji SVGinOT Unicode font with full support for skin tone modifiers and country flags tested to work in Linux, OS X and Windows.

**Comment by eosrei** [comment]
Download: https://github.com/eosrei/emojione-color-font/releases/download/v1.0-beta/EmojiOneColor-SVGinOT.ttf.zip

Install and set as default on Linux: https://github.com/eosrei/emojione-color-font#usage---linux

**Comment by eosrei** [comment]
@thinkrick I hope it's ok to use the Emoji One name, I think I've made it clear this is a separate project heavily based on EmojiOne. There are three separate links to emojione.com in the readme and another in the font's metadata.

Should I submit the font file as a PR to fix this issue?

**Comment by nclm** [comment]
Thank you for this! It works perfectly!
(in Mozilla apps only of course, as they’re the only ones to support SVGinOT)

I did some tests, it seems like you actually don’t need to do the `fonts.conf` thing if this EmojiOne font is the only one covering the emoji range installed on the system. If you also have Symbola, or Windows’ Segoe for instance, you need to override the priority indeed. And it’s nicer to have these alternatives side to side with EmojiOne anyway, so you get a monochrome fallback in non-Mozilla apps.

I wonder why is Symbola or Segoe selected first for emoji display when you have this EmojiOne font installed too.

**Comment by eosrei** [comment]
@nclm You're welcome!

The regular B&W outline glyphs I generated work everywhere else for now. The google, microsoft, and adobe/firefox color font formats are all in the new opentype standard, so I don't expect this cleared up with "one true way" any time soon or maybe ever.

> I did some tests, it seems like you actually don’t need to do the fonts.conf thing if this EmojiOne font is the only one covering the emoji range installed on the system.

Yes, you won't need `font.conf` if your distribution doesn't include any fonts with emoji. Both Ubuntu and Fedora (my testbeds) include the `DejaVu` family, so I need the `font.conf` to override `DejaVu`. It doesn't surprise me some distributions don't include some default emoji. What are you running? This what it looks like without the `font.conf` on both Ubuntu and Fedora:
![ohnoitsdejavu](https://cloud.githubusercontent.com/assets/195061/13363855/89a29428-dc80-11e5-8c93-7d56194c97bc.png)

**Comment by jpfleury** [comment]
@eosrei It works great on Xubuntu 15.10 with the file `font.conf`. Thanks a lot!

**Comment by mikebe11** [comment]
@eosrei Thanks for the offer but you needn't submit the font file in a PR. We see you've generously mentioned us in your readme file. Your taking the time to add the credit is much appreciated.
Great work on this font. I'll be closing this issue and updating our font readme with a mention of your font and link to your repo.

**Comment by eosrei** [comment]
Great! Thanks! The font actually works well in Windows/OSX also, although still the color emoji only show in Firefox.
