### ISSUE TITLE
Improve sprite rendering in FF

### ISSUE THREAD

**Issue by emitstop** [Ranks/emojione#17]
PNG sprite display in Firefox pales in comparison to Chrome. They will sometimes look _okay_, but then other times will look downright awful. Leading to weird distortions, and bizarrely inconsistent anti-aliasing, this seems to be most apparent when the computed width and height of the sprite isn't an exact pixel value: 
(Firefox on the left, Chrome on the right )
![Emoji One firefox, before adding image-rendering rules](http://puu.sh/bJYmP/d4c50ac932.png)

This was improved (though really more of a trade-off) by adding
```image-rendering: optimizeQuality; ```
After which they look more like this: 
![after image-rendering.](http://puu.sh/bJYIh/59763638b2.png)
Which is a hell of a lot better, but still pretty bad in comparison to chrome. Lots of clipped sides, and I'd say this looks a little overly crisp with too many hard edges. Display in firefox is kind of all over the board, varying from looking pretty good to looking downright awful depending on the both the individual emoji, and the size its being displayed at. 

I'm hoping to find out whether this just comes down to Firefox having a worse image rendering engine than Chrome, or if there's more that can be done to keep things looking half decent.

[I've setup a quick codepen here](http://codepen.io/emitstop/pen/boKeq), which i used to take the screenshots above. 
The issue here seems to stem from the fact that these sprites are resizeable, and positioned/sized from a combination of percentage based background offsets, and background-size. 

Our actual sprite files are located under /assets/sprites.

**Comment by driver-by** [comment]
@emitstop  
```
transform: rotate(0deg);
```
Maybe this would help a little.
[stackoverflow](http://stackoverflow.com/a/14308227/1707258)

**Comment by mikebe11** [comment]
Hey Z. Going through some issues. Gonna close this one. Not much input on it. FF apparently considers their rendering issue fixed and looks like all the CSS workarounds have been explored.
Hope all's well with you.
