### ISSUE TITLE
8 people emoji without skin tone modifier support

### ISSUE THREAD

**Issue by robin0van0der0v** [Ranks/emojione#170]
There are currently 8 people emoji without skin modifier support and some of them are in the white race and not in neutral yellow.

1. ![👯](https://raw.githubusercontent.com/Ranks/emojione/master/assets/png/1f46f.png) Currently only in neutral yellow, not in different colors.
2. ![🏌](https://raw.githubusercontent.com/Ranks/emojione/master/assets/png/1f3cc.png) Currently only available in the white race.
3. ![⛷](https://raw.githubusercontent.com/Ranks/emojione/master/assets/png/26f7.png) Currently only in neutral yellow, not in different colors.
4. ![🏂](https://raw.githubusercontent.com/Ranks/emojione/master/assets/png/1f3c2.png) Currently only available in the white race.
5. ![🕴](https://raw.githubusercontent.com/Ranks/emojione/master/assets/png/1f574.png) Currently only available in the white race.
6. ![🏍](https://raw.githubusercontent.com/Ranks/emojione/master/assets/png/1f3cd.png) Currently only available in the white race.
7. ![🎢](https://raw.githubusercontent.com/Ranks/emojione/master/assets/png/1f3a2.png) - Currently only available in the white race.
8. ![🎎](https://raw.githubusercontent.com/Ranks/emojione/master/assets/png/1f38e.png) - Currently only available in the white race... Well they are dolls though, but still white dolls.

**Comment by thinkrick** [comment]
Thanks for the report.

Unfortunately none of the emoji listed have been officially supported by Unicode under their modifier style rules.  You can which emoji are compatible at this Default Style Values page (see modifier table):
http://www.unicode.org/emoji/charts/emoji-style.html

However, you're right that we have a couple emoji with the yellow skin.  You have a good eye and we'll be sure to correct this in our next seasonal update (approx March).

I'll leave this as open for now, but may close it later to keep things tidy.

**Comment by robin0van0der0v** [comment]
> Unfortunately none of the emoji listed have been officially supported by Unicode under their modifier style rules. You can which emoji are compatible at this Default Style Values page (see modifier table):
> http://www.unicode.org/emoji/charts/emoji-style.html

I understand that we can't just invent completely new emoji and add them to the set, but why can't we just support those emoji with colors? It will not break anything, since other platforms will keep showing the correct emoji with another character signalling the skin color.

> However, you're right that we have a couple emoji with the yellow skin. You have a good eye and we'll be sure to correct this in our next seasonal update (approx March).

With the yellow skin? Didn't you meant to say 'with the white skin', since I would assume yellow is the default color for all emoji (regardless if they do or do not support skin colors).

Also, why don't we give the 'RACING MOTORCYCLE' (U+1F3CD) gloves, this way it does not show any skin any more and I also think all motorcyclists wear those in the first place.

**Comment by nclm** [comment]
The skier and the snowboarder could also wear snow goggles (which are quite unavoidable anyway) and scarves, so these two glyphs would also be more race-neutral, and gender-neutral too.

**Comment by miguelsousa** [comment]
@thinkrick technically, there's nothing preventing a font from supporting skin tones on **any** character. In fact, Emoji One currently supports skin tones for &#x1F3C7; (U+1F3C7) which is not included in the [Unicode data](http://www.unicode.org/emoji/charts/emoji-style.html#modifier). The real limitation will probably come from Input Methods (e.g. keyboard widgets) as these may implement only the Unicode set.

**Comment by robin0van0der0v** [comment]
> technically, there's nothing preventing a font from supporting skin tones on **any** character

Then why not support it for every character that has skin? I don't think it would be that much work, it is literally only two colors (skin and hair) that needs to be changed each time.

**Comment by mikebe11** [comment]
hey @miguelsousa , regarding the horse racing emoji (U+1F3C7), that one was at one time being included in Unicode's set of emoji subject to modification. You can see it in a previous version of their technical report : http://www.unicode.org/reports/tr51/tr51-3.html  They've made changes many times throughout our development, smileys were subject to modification, then weren't. That one slipped by us. Just wanted to make it known that horse racing wasn't just chosen arbitrarily to get skin tone support.

**Comment by miguelsousa** [comment]
@mikebe11 I understand. Apple's emoji font supports it too. I think that skin tone support doesn't have to be limited to what Unicode prescribes. Expanding the skin tone support in Emoji One may actually influence the Unicode committee to expand the official list.

**Comment by mikebe11** [comment]
Good point.
