### ISSUE TITLE
Missing Emoji

### ISSUE THREAD

**Issue by samantha-cruz** [Ranks/emojione#171]
Here are the emoji that still needs to be completed:

Regional Indicators A-Z (Unicode numbers in tooltips):

U+1F1E0: ![emoji_u1f1e6](https://cloud.githubusercontent.com/assets/16244324/11919523/90899d06-a790-11e5-9e39-b5d9e4bd902a.png)
U+1F1E1: ![emoji_u1f1e7](https://cloud.githubusercontent.com/assets/16244324/11919524/908bd828-a790-11e5-8851-6e2282d89b45.png)
U+1F1E2: ![emoji_u1f1e8](https://cloud.githubusercontent.com/assets/16244324/11919525/908e0094-a790-11e5-8b83-3cb770f45dc1.png)
U+1F1E3: ![emoji_u1f1e9](https://cloud.githubusercontent.com/assets/16244324/11919526/90916ad6-a790-11e5-85c6-4c693b8b3022.png)
U+1F1E4: ![emoji_u1f1ea](https://cloud.githubusercontent.com/assets/16244324/11919527/90946b0a-a790-11e5-9239-6f23cc8762f8.png)
U+1F1E5: ![emoji_u1f1eb](https://cloud.githubusercontent.com/assets/16244324/11919528/90963f2a-a790-11e5-8348-51203ee190d6.png)
U+1F1E6: ![emoji_u1f1ec](https://cloud.githubusercontent.com/assets/16244324/11919529/90b24ef4-a790-11e5-9159-468e88b99000.png)
U+1F1E7: ![emoji_u1f1ed](https://cloud.githubusercontent.com/assets/16244324/11919530/90b74c2e-a790-11e5-928b-29d243ecaac1.png)
U+1F1E8: ![emoji_u1f1ee](https://cloud.githubusercontent.com/assets/16244324/11919531/90b7bdd0-a790-11e5-8bef-36b967e03b23.png)
U+1F1E9: ![emoji_u1f1ef](https://cloud.githubusercontent.com/assets/16244324/11919532/90bbd992-a790-11e5-9d4b-c6b8b6ff6408.png)
U+1F1EA: ![emoji_u1f1f0](https://cloud.githubusercontent.com/assets/16244324/11919533/90bfb06c-a790-11e5-9fa4-c5a5656e1209.png)
U+1F1EB: ![emoji_u1f1f1](https://cloud.githubusercontent.com/assets/16244324/11919534/90c015de-a790-11e5-8c5a-725864ed8c0b.png)
U+1F1EC: ![emoji_u1f1f2](https://cloud.githubusercontent.com/assets/16244324/11919535/90db17da-a790-11e5-9dc1-4d66895d67f3.png)
U+1F1ED: ![emoji_u1f1f3](https://cloud.githubusercontent.com/assets/16244324/11919536/90dfbd26-a790-11e5-96df-771ed1299769.png)
U+1F1EE: ![emoji_u1f1f4](https://cloud.githubusercontent.com/assets/16244324/11919537/90e1d840-a790-11e5-9e62-0bdf56d6e918.png)
U+1F1EF: ![emoji_u1f1f5](https://cloud.githubusercontent.com/assets/16244324/11919538/90e70f68-a790-11e5-850a-6953faf649a5.png)
U+1F1F0: ![emoji_u1f1f6](https://cloud.githubusercontent.com/assets/16244324/11919539/90eb1a90-a790-11e5-9584-2c2c4dbfa4b5.png)
U+1F1F1: ![emoji_u1f1f7](https://cloud.githubusercontent.com/assets/16244324/11919540/90ec7304-a790-11e5-91ab-d450503ea4c3.png)
U+1F1F2: ![emoji_u1f1f8](https://cloud.githubusercontent.com/assets/16244324/11919541/9106891a-a790-11e5-8993-a2647acc6f21.png)
U+1F1F3: ![emoji_u1f1f9](https://cloud.githubusercontent.com/assets/16244324/11919542/91087dba-a790-11e5-9ed3-99227b6f5ad3.png)
U+1F1F4: ![emoji_u1f1fa](https://cloud.githubusercontent.com/assets/16244324/11919543/910b026a-a790-11e5-8865-cde6bb1969f4.png)
U+1F1F5: ![emoji_u1f1fb](https://cloud.githubusercontent.com/assets/16244324/11919544/9111703c-a790-11e5-9ab8-5105827fe662.png)
U+1F1F6: ![emoji_u1f1fc](https://cloud.githubusercontent.com/assets/16244324/11919545/91144a46-a790-11e5-890b-6acc767eccf1.png)
U+1F1F7: ![emoji_u1f1fd](https://cloud.githubusercontent.com/assets/16244324/11919546/911986d2-a790-11e5-9a27-a8cdd9f39258.png)
U+1F1F8: ![emoji_u1f1fe](https://cloud.githubusercontent.com/assets/16244324/11919547/91301e88-a790-11e5-96dd-fcb79e2d5601.png)
U+1F1F9: ![emoji_u1f1ff](https://cloud.githubusercontent.com/assets/16244324/11919548/9130db48-a790-11e5-9262-e1e16bd533c0.png)

LEFT SPEECH BUBBLE (U+1F5E8)
![emoji_u1f5e8](https://cloud.githubusercontent.com/assets/16244324/11919563/d232d6a0-a790-11e5-8435-f5f48a095532.png)

EJECT SYMBOL (U+23CF)
![emoji_u23cf](https://cloud.githubusercontent.com/assets/16244324/11919566/eb1aceac-a790-11e5-92b4-a73a1ed34852.png)

DIGIT ZERO to DIGIT NINE + ASTERISK + POUND SYMBOL (codes on tooltips)
U+0030: ![emoji_u0030](https://cloud.githubusercontent.com/assets/16244324/11919571/fe9db250-a790-11e5-919d-0bc44978fde8.png)
U+0031: ![emoji_u0031](https://cloud.githubusercontent.com/assets/16244324/11919570/fe9cd704-a790-11e5-8521-e498c4ccd3bc.png)
U+0032: ![emoji_u0032](https://cloud.githubusercontent.com/assets/16244324/11919572/fea14e42-a790-11e5-8a3a-f38c46407439.png)
U+0033: ![emoji_u0033](https://cloud.githubusercontent.com/assets/16244324/11919574/fea3dcf2-a790-11e5-87d3-e044140b4769.png)
U+0034: ![emoji_u0034](https://cloud.githubusercontent.com/assets/16244324/11919573/fea2d668-a790-11e5-9727-e2e593ae77e7.png)
U+0035: ![emoji_u0035](https://cloud.githubusercontent.com/assets/16244324/11919575/fea5a62c-a790-11e5-8a21-58b2a7113b4c.png)
U+0036: ![emoji_u0036](https://cloud.githubusercontent.com/assets/16244324/11919576/fec6e832-a790-11e5-8d33-44e7298e5c2d.png)
U+0037: ![emoji_u0037](https://cloud.githubusercontent.com/assets/16244324/11919578/feec2de0-a790-11e5-9599-0493760fed30.png)
U+0038: ![emoji_u0038](https://cloud.githubusercontent.com/assets/16244324/11919579/fef36d6c-a790-11e5-990e-1555daabe029.png)
U+0039: ![emoji_u0039](https://cloud.githubusercontent.com/assets/16244324/11919577/fecf2e0c-a790-11e5-93b7-a951daa19a70.png)
U+002A: ![emoji_u002a](https://cloud.githubusercontent.com/assets/16244324/11919590/4fc4c3d0-a791-11e5-85be-c4a293565642.png)
U+0023: ![emoji_u0023](https://cloud.githubusercontent.com/assets/16244324/11919591/4fc5d400-a791-11e5-8f53-61907eed3181.png)

**Comment by thinkrick** [comment]
Hi Samantha,

We use this table to define which emoji to support, based on Unicodes "standard additions":
http://www.unicode.org/emoji/charts/full-emoji-list.html

The left speech bubble and eject button weren't included in this release but will be included in our next seasonal update.  Appreciate you looking out!  :)

**Comment by miguelsousa** [comment]
@samantha-cruz the regional indicators are in the range U+1F1E6 thru U+1F1FF, not U+1F1E0 thru U+1F1F9.

@thinkrick the left speech bubble and the eject button were included in the Android font. As for the other characters, even though they are not standalone-listed in the Unicode data, they're necessary as a means to encode the sequences, so the fonts have to support them. Currently the Android font has these characters blank, since there's no artwork for them.
I think it might be worth making artwork for these characters — especially for the regional indicators — because in environments that cannot process the sequences (e.g. the flag for Antarctica &#x1F1E6;&#x1F1F6;) nothing will be shown. If artwork is added to the characters, at least each element of the sequence will be displayed.

**Comment by Naudiz** [comment]
2.1 update of EmojiOne is still lacking all of the above.

**Comment by eosrei** [comment]
This fixed in V2.2.0
