### ISSUE TITLE
Change hair color of default emoji

### ISSUE THREAD

**Issue by samantha-cruz** [Ranks/emojione#174]
Hi, would like to suggest changing the default hair color of the default people emoji to something else in your next quarterly update not only to make the default non-human appearance more distinct but also because the yellow skin/brown eyes/black hair /combination/ (not the yellow skin per se because I understand that's the de facto color for the default skin) looks like yellowface, which defeats the purpose of diversity because it's racist towards Asians (East Asians, specifically).

I was one of the beta testers during the time Apple released their implementation of the multiple skintones and I remember there was backlash during the initial implementation, which has the exact same skin/eye/hair color combo. Probably the reason why Apple changed the hair color of the default people emoji to yellow as well.

http://qz.com/349561/asians-are-not-impressed-with-apples-diverse-yellow-emoji/

A good color replacement would be the hair color of the current princess emoji, which is neutral enough.

![1f469](https://cloud.githubusercontent.com/assets/16244324/11965034/e6bd709c-a92c-11e5-9dd7-70741f885df6.png)

Hope this is something to consider.

**Comment by Undeterminant** [comment]
:+1: for red hair. It's sufficiently neutral, but also stands out for small icons.

**Comment by mikebe11** [comment]
Thanks for the suggestion. The hair color for default emoji was changed in the latest quarterly release. In case you haven't seen it here's a sample. 
![1f469](https://cloud.githubusercontent.com/assets/9707818/12741999/81ec1a9a-c936-11e5-9ac0-a29c2fadc06a.png)
