### ISSUE TITLE
Document shortnameToUnicode functions

### ISSUE THREAD

**Issue by Undeterminant** [Ranks/emojione#179]
Right now, these are missing from the documentation in the `README`.

**Comment by mikebe11** [comment]
The js and php libraries both have the function, shortnameToUnicode. Is there a different implementation of this that you're suggesting?

**Comment by Undeterminant** [comment]
…somehow I missed this. I was looking at the documentation and didn't see this, so, it's a documentation bug.

**Comment by mikebe11** [comment]
The demos have been updated.

**Comment by Undeterminant** [comment]
Thank you!
