### ISSUE TITLE
Missing emoji

### ISSUE THREAD

**Issue by rgustavsson** [Ranks/emojione#180]
This emoji is missing from your CDN.
http://cdn.jsdelivr.net/emojione/assets/png/1F58E.png

**Comment by mikebe11** [comment]
Thank you for the notice. That emoji has been restored. We suggest upgrading your product to use the latest version of the library, if possible. That particular emoji is one of a group that is no longer part of Unicode's standard set. We had it in there before it was removed from v7. It's no longer included in the collection or being updated.
