### ISSUE TITLE
Emoji randomly changed?

### ISSUE THREAD

**Issue by EddieOne** [Ranks/emojione#181]
Hi,

Thanks for the emoji. We use EmojiOne at id.net and recently noticed all the default icons are different. What's the deal with that?

cheers

**Comment by mikebe11** [comment]
Hello,
Do you mean the category icons or are you referring to the major update we just released?

**Comment by EddieOne** [comment]
I believe it was the major update. I noticed before emojieone had the same icons as GitHub but now they're different. We are currently hotlinking the js file using the jsdelivr.net cdn. Though we are on the 1.5.0 release.

**Comment by mikebe11** [comment]
I see. Yes, the new collection completely replaced v1.5.2. We still offer the original collection in our legacy repository,  https://github.com/Ranks/emojione-legacy
We also set up a CDN link for individual PNGs and SVGs, `//cdn.jsdelivr.net/emojione/assets/1.5.2/(png or svg)/` A simple change of the location link in the js file should get you back on the original assets if that's what you prefer.

**Comment by EddieOne** [comment]
Alright. I think I will just stay with the new images. I was more curious about why it changed. Thank you for the response.
