### ISSUE TITLE
racehorse is retired?

### ISSUE THREAD

**Issue by bmcorser** [Ranks/emojione#183]
I love the :racehorse: emoji, it denotes swiftness and elegance. The emojione version looked similar:
![racehorse](https://raw.githubusercontent.com/Ranks/emojione-legacy/master/png/1F40E.png)
I looked at something I had written where the racehorse was used to denote swiftness and elegance after updating to emojione 2.0.0 and saw my point was undermined by the replacement of my swift and elegance racehorse with a rather stationary nag, as below:
![racehorse](https://raw.githubusercontent.com/Ranks/emojione/master/assets/png/1f40e.png) 

please give us back our galloping equine!

**Comment by richtier** [comment]
I too favour magnificent bounding thoroughbreds.

**Comment by mikebe11** [comment]
Thanks for the suggestion. It's been decided that this emoji will be changed to a galloping horse, following the active style found in version 1. The revision will be in the next art update.

**Comment by bmcorser** [comment]
Joy!

**Comment by mikebe11** [comment]
The quarterly update has been posted and the "galloping equine" has been added. Thank you supporting our project.
![racehorse](https://raw.githubusercontent.com/Ranks/emojione/master/assets/png/1f40e.png)

**Comment by bmcorser** [comment]
She's majestic.
