### ISSUE TITLE
[Android] Fallback to B+W emojis in Android 5.1.1 (CM12.1)

### ISSUE THREAD

**Issue by aphirst** [Ranks/emojione#185]
I tested EmojiOne 2016 on my mum's Android 4.4.4 (CM11) device (both with a manual copy of the ttf, and with the .zip provided in a PR by @samantha-cruz, and everything seemed to work fine. There were of course some emoji "missing" but that's due to not using an appropriately updated keyboard - all emoji that rendered did so correctly using the one from EmojiOne.

I then tested on my own 5.1.1 device (CM12.1), in both ways, and what I get is a couple of the emoji showing up as those ugly little B+W icons. The ones which do so were consistent from when I tested with the ttf and the aforementioned .zip, and the ones I can find when I skim through now are:

* standard red love heart, the one before the blue one
* two fingers making the peace symbol (V for victory)
* the envelope, just before the envelope with speed lines behind it
* the pencil, just before the emoji of the pencil writing on a piece of paper
* the icon of the sun which just comes before the rainbow
* snowflake
* aeroplane
* the Java symbol just before the love letter
* most of the arrows
* most of the geometric shapes

I'll try to post the emoji somewhere so that I know their actual character codes, and also screenshots in an empty chat. Bear with me. :)
![Here we go.](https://a.pomf.cat/okzzxi.png)

✌❤️⭐️☀️❄️☎️✉️✂️✒️✏️✈️⬆️⬇️⬅️➡️↗️↖️↘️↙️↔️↕️◀️▶️↩️↪️⤵️⤴️✳️❇️✴️⭕️❗️‼️⁉️✖️♠️♥️♣️♦️✔️◼️◻️◾️◽️▪️▫️⬜️⬛️⚫️⚪️
... and ♨️

I haven't tested any other keyboards yet, but I get this behaviour in the AOSP default keyboard and in Telegram-FOSS, though those two keyboards seem to put some things in different orders.

If there's any information I can provide, I'd be happy to try to help.

**Comment by Naudiz** [comment]
The problem is not with EmojiOne or with the keyboard, it is with Android.
You need to reconfigure it to give the Emoji One font a higher priority.
Here's how to do it for Android 5.1.1 and 6.0.1, assuming you overwrote NotoColorEmoji.ttf with EmojiOne font:

Open /system/etc/fonts.xml
Search for:
```
<family>
       <font weight="400" style="normal">NotoColorEmoji.ttf</font>
</family>
```
cut it out, scroll up and paste it right under:
```
    <!-- fallback fonts -->
```
(it should be somewhere around line 95)

Next open /system/etc/fallback_fonts.xml
Search for:
```
    <family>
        <fileset>
            <file>NotoColorEmoji.ttf</file>
        </fileset>
    </family>
```
cut it out, scroll up and paste it right under
```
<familyset>
```
(it is right at the top, directly after the introduction comment)

Reboot and it should work now :)

**Comment by mikebe11** [comment]
@aphirst Checking in on this. Did the suggestion by @Naudiz solve your B&W fallback issue?

**Comment by aphirst** [comment]
@mikebe11 Ah hi, sorry, it did work! I just totally forgot to close the issue. Thanks for checking back up!

**Comment by mikebe11** [comment]
Glad to hear it! Thanks @Naudiz

**Comment by aphirst** [comment]
Are there likely to be any plans to make installer .zips for Android users (presumably of various versions) to ease installation for non-Google-Play users, or anything similar?

**Comment by aphirst** [comment]
It seems that when installing EmojiOne using "EmojiSwitcher", the same bug is encountered. I'm going to go and report that to them now.
