### ISSUE TITLE
class conversion

### ISSUE THREAD

**Issue by areejayy** [Ranks/emojione#186]
hi! if i use this:
--p class="convert-emoji">
{{text}}
</p--
will it convert the emoji names in the 'text' that is produced by handlebars?

p.s: ignore --p, im using p tag

**Comment by mikebe11** [comment]
As we package it, that conversion is done after the jQuery's `$(document).ready()`. If your template has rendered `{{text}}` before the call to `$(document).ready()` I would say that it will but if your project is more dynamic then it appears like no, it won't. By default it's not bound to any subsequent events after loading.
The good thing about that conversion is that it could easily be altered to make the conversion after a change event or even be performed manually after the template has been executed.

**Comment by mikebe11** [comment]
hi @areejayy  Just following up to see if you've tested the class conversion with handlebars yet?

**Comment by areejayy** [comment]
Yeah. It worked fine

**Comment by mikebe11** [comment]
Glad to hear that. Thanks for the response. I'll close this issue then.

**Comment by areejayy** [comment]
Yes. You can. Thanks

**Comment by imromain** [comment]
hi @areejayy  , how did you do to make it work with handlebars?
