### ISSUE TITLE
Umbrella stem in ☂ is too light/thin

### ISSUE THREAD

**Issue by ping** [Ranks/emojione#187]
The stem of the umbrella in the umbrella emoji ☂ is too light/thin. Except at fairly large font sizes, the umbrella stem is almost invisible.

![umbrella](https://cloud.githubusercontent.com/assets/104607/12380570/e085a364-bdb0-11e5-8fd1-c85223366e16.png)

https://jsfiddle.net/33njp31h/

**Comment by mikebe11** [comment]
It does get harder to see as it gets smaller. The designers have seen your note and will take it into consideration for a future update. Thanks for the note on it.

**Comment by mikebe11** [comment]
The umbrella was updated in the latest quarterly release. The designers changed the stem to the degree they felt was appropriate. Thank you for bringing that to our attention.
![2602](https://cloud.githubusercontent.com/assets/9707818/12742086/5c9e0892-c937-11e5-8c9c-c6f8bf0f67db.png)
