### ISSUE TITLE
Mapping of :)

### ISSUE THREAD

**Issue by kylemeier** [Ranks/emojione#188]
I don't think anyone expects an open mouthed emoji to appear when they type :) (or the other ones mapping to 1f604), especially when :D is an option. Is there a reason they aren't mapping to something like 1f642 (slight_smile) that more closely resembles the ASCII?

**Comment by waldyrious** [comment]
:+1: :+1: :+1:

**Comment by mikebe11** [comment]
Thanks for the question. It's understandable that one would ask it. Those mappings were acquired from different sources when the repository was originally created. We didn't match them ourselves but tried to stay in line with what the general standard appeared to be. Unfortunately there is no actual standard so there's a lot or room for opinion. I do agree with you that there are better ways to put some of the codes together but I don't see us changing these soon. Right now we're not looking to shake up what people have been used to and expect. Plus it's just low on the list of priorities. Instead we tried to make the JS and PHP libraries flexible and simple enough so someone could map :) to 1f642, which I personally agree is better, if that was their preference.

**Comment by mikebe11** [comment]
@kylemeier Your note was passed on and word came down to remap the 1f604 ascii patterns to 1f642, slight smile. You'll see the change in this latest release.
Thanks.

**Comment by kylemeier** [comment]
Great to hear! Thanks.
