### ISSUE TITLE
Color of hear-no-evil monkey's hands (U+1f649)

### ISSUE THREAD

**Issue by miguelsousa** [Ranks/emojione#192]
The hands of `hear-no-evil monkey` &#x1f649; are darker than `see-no-evil monkey` &#x1f648; and `speak-no-evil monkey` &#x1f64a;.

**Comment by JohnCoates** [comment]
Good eye. I'm adding this screenshot as a quick reference.
![screen shot 2016-02-03 at 8 31 27 am](https://cloud.githubusercontent.com/assets/967800/12788956/9bbdb03a-ca50-11e5-99ab-c45a2d66c1d8.png)

**Comment by eosrei** [comment]
Just noticed, the top of the head is not aligned across the first four. I confirmed it in the source.

![topofhead](https://cloud.githubusercontent.com/assets/195061/13365635/03be6ab6-dc8b-11e5-9821-2e73319644a3.png)

**Comment by thinkrick** [comment]
Good stuff!  We'll make sure both are corrected in next big update... set to release later this month.  :)
