### ISSUE TITLE
Having a hard time converting "traditional" emojis like :) :P ;) etc

### ISSUE THREAD

**Issue by philippeboyd** [Ranks/emojione#194]
When I call toImage() or shortnameToImage(), every "colon emojis" or unicode ones gets converted but no the traditional ones like ":) :D ;) :P"

Seems to work pretty well on http://git.emojione.com/demos/2.1.0/jstoimage.html when testing `Hello world! 😄 :smile: :)`

I got the latest files from https://github.com/Ranks/emojione/archive/master.zip as of today (Feb 3, version 2.1.0)

**Comment by mikebe11** [comment]
The default is not to convert ascii smileys. Have you set that to true in your implementation? The demo you referenced includes the following `emojione.ascii = true;`
http://git.emojione.com/demos/2.1.0/ascii-smileys.html

**Comment by philippeboyd** [comment]
right! I just figured it out and was about to comment on the issue and close it... Thanks :)
