### ISSUE TITLE
Need help for creating well-compressed PNGs

### ISSUE THREAD

**Issue by Naudiz** [Ranks/emojione#195]
Hello,

I need to create PNGs of EmojiOne in a resolution that is not 64, 128 or 512px.
I used Inkscape for this task and while I was really satisfied with the visual result, I noticed that the PNGs compress a lot poorer than the ones provided from EmojiOne's website. I tried different compressors like OptiPNG and pngout, but the size won't go anywhere near the regions of the website's PNGs.

To test this issue I created a 64px export of a random emoji and compared it to the native PNG. My Inkscape export didn't want to compress any more than about 200% of the native PNG...

Any hints for me?
Which tools were used to render the PNGs that are for download on the website?

**Comment by rodrigopolo** [comment]
Here is what I do in OS X, firstm having Home Brew installed I install this programs:
```
brew install optipng pngquant advancecomp
```

Then I optimize the PNGs like this:
```
pngquant --verbose --speed=1 --quality=0-100 INPUT.png -o OUPUT.png
optipng -o7 FILE.png
advpng -z -4 FILE.png
advdef -z -4 FILE.png
```

Notice that `pngquant` needs an input and output, and the rest don't.
Also, notice that this tools are available on other platforms like Windows and Linux, just google the names to know where to get them, they work on the terminal or command prompt just like the example above.

**Comment by Naudiz** [comment]
Thank you! That's more or less what I did, but it didn't help. I think this has something to do with the way how the PNGs are exported in the first place.

See the difference in optipng's output on the website's file:
```
** Processing: 1f1e9-1f1ea.png
64x64 pixels, 4x8 bits/pixel, RGB+alpha
Reducing image to 8 bits/pixel, 44 colors (41 transparent) in palette
Input IDAT size = 442 bytes
Input file size = 499 bytes

Trying:
  zc = 9  zm = 9  zs = 0  f = 0         IDAT size = 350
  zc = 9  zm = 8  zs = 0  f = 0         IDAT size = 350

1f1e9-1f1ea.png is already optimized.
```

Compared to the one I exported from Inkscape:
```
** Processing: 1f1e9-1f1ea_inkscape.png
64x64 pixels, 8 bits/pixel, 176 colors (173 transparent) in palette
Input IDAT size = 485 bytes
Input file size = 1340 bytes

Trying:
  zc = 9  zm = 9  zs = 0  f = 0         IDAT size = 517
  zc = 9  zm = 8  zs = 0  f = 0         IDAT size = 517
  zc = 8  zm = 9  zs = 0  f = 0         IDAT size = 517
  zc = 8  zm = 8  zs = 0  f = 0         IDAT size = 517
  zc = 9  zm = 9  zs = 3  f = 0         IDAT size = 485
  zc = 9  zm = 8  zs = 3  f = 0         IDAT size = 485

1f1e9-1f1ea_inkscape.png is already optimized.
```

As you can see, my file has 176 colors while the original needs only 44, so there was clearly  a more optimized way of exporting used, but how?

**Comment by mikebe11** [comment]
Technically we don't compress but optimize with ImageOptim. It's the only tool used. I believe it's only available for the Mac. Initial PNGs are made with Illustrator. If you're on a Mac ImageAlpha works well for lossy compression.

**Comment by rodrigopolo** [comment]
@Naudiz Try running this command, notice that we are using 4 different apps to optimize the file, first one is `pngquant` which reduce the number of colors in the palette, then, `optipng`, and then `advpng` with `advdef` just to make sure there 100% optimized.

```
pngquant --verbose --speed=1 --quality=0-100 input.png -o output.png && optipng -o7 output.png && advpng -z -4 output.png && advdef -z -4 output.png
```

**Comment by Naudiz** [comment]
Thank you guys!
I now have at least some hints in the direction which I ave to go. I think the crucial part lies in the creation of the inital PNGs. At the moment it's the only reason I see atm, why the same image in the same resolution from the repository has 44 unique colors, while the export from inkscape has 176.
It's not surprising that a 44-color-png compresses better than a 176-colors-png.

Rodrigo, thanks for the suggestion with pngquand, unfortunately it didn't do much. My PNG has still too many colors compared to the repo-PNG and still compresses much worse.

I think I will now try to make an export with Illustrator and see if I receive better results...

**Comment by Naudiz** [comment]
I have now installed a trial version of Illustrator, and it seems that PNGs exported by that are really better to compress/optimize.
But now I'm encountering a new problem: Illustrator opens all emojis with a wrong aspect ratio, something that looks more like a sheet of paper than the required 1:1 ratio (and also exports this ratio to PNG).... I'm starting to get frustrated by this task :(

**Comment by mikebe11** [comment]
@Naudiz Closing this issue. Activity has died down and we've provided all the info on PNG generation that we have.
