### ISSUE TITLE
Documentation on using unicode with tones

### ISSUE THREAD

**Issue by tim-peterson** [Ranks/emojione#198]
This is a great library, thanks! I'm trying to use the tones with unicode and when you use shortnames with `_toneX` in them, e.g., `:haircut_tone4:` two unicodes are rendered (see image). How to fix this? 
![image](https://cloud.githubusercontent.com/assets/1173307/13037118/845464de-d347-11e5-8652-1fa0bc554ad4.png)

**Comment by mikebe11** [comment]
Thanks for the compliment. We appreciate it. As for your issue, would you please post some code or details on your working environment. There's not enough info for us to determine what might be happening here.

**Comment by tim-peterson** [comment]
Mac OS X 10.11 (El Capitan) is the OS. 

For example, `:haircut_tone4:` works as expected showing a dark complected woman *without* the tone swatch on Safari 9 and Firefox 43. Unfortunately, the dominant browser, Chrome (v48 in my case) is what shows the tone swatch along side the light complected woman as shown in my image above.

Seems like others are noticing this browser difference: https://twitter.com/GetEmoji/status/696806598853808128

**Comment by mikebe11** [comment]
From what you've explained the issue you're seeing is not with our library and we don't have a fix for it. Once you convert to unicode code points (using `shortnameToUnicode()`) that display is out of our control. What's seen is dependent on the platform and environment. Your experience with Chrome is typical, although undesirable.
Let me know if I'm missing something here but I've checked the results and our library is returning the correct code points for the skin tone shortnames.

**Comment by mikebe11** [comment]
@tim-peterson  Going to close this. The issue you've mentioned is not fixable by us. It's up to some browser developers to change how they handle certain code point combinations.
