### ISSUE TITLE
I can't convert some emojis from emojione's database to images (.toImage(str))

### ISSUE THREAD

**Issue by NerosTie** [Ranks/emojione#202]
I'll show you an example of my issue, the `airplane`.

This is the airplane in your database: ✈ 
(http://apps.timwhitlock.info/unicode/inspect?s=%E2%9C%88)
This is an other airplaine: ✈️ 
(http://apps.timwhitlock.info/unicode/inspect?s=%E2%9C%88%EF%B8%8F)

They are not the same, the second one has 2 codes and unfortunately, this is the only one who work with .toImage(str).

You can try the 2 airplanes here: http://git.emojione.com/demos/2.1.0/jstoimage.html

You will see only one will work and this is not the airplaine in your database (http://emoji.codes or with the new add-on on Chrome).

![emojione](https://cloud.githubusercontent.com/assets/4572452/13168963/107a9c6a-d6e2-11e5-85c7-325bad575ef0.png)

**Comment by NerosTie** [comment]
In fact, it's the same issue for every emojis coded like `:anchor:':["2693-fe0f","2693"]` in `lib/js/emojione.js`

**Comment by mikebe11** [comment]
We'll get the variables updated to capture those characters without the variation code.

**Comment by mikebe11** [comment]
@NerosTie We've updated the javascript file. Those with or without the modifier should be working now. Thanks for bringing it to our attention.

**Comment by NerosTie** [comment]
Thanks! :airplane:
