### ISSUE TITLE
Emojione Picker

### ISSUE THREAD

**Issue by mroftalp** [Ranks/emojione#206]
Is there a emojione picker I can use? Particularly in javascript.

**Comment by mikebe11** [comment]
There's this React picker:  https://github.com/tommoor/emojione-picker

**Comment by mroftalp** [comment]
@mikebe11 is there a way I can integrate this in meteor? that picker really looks good but just don't know how I would integrate it

**Comment by mikebe11** [comment]
@mroftalp I'm afraid I can't help there. I've never used meteor myself. I'll leave this issue open a bit to see if someone comes along who can help with that.

**Comment by mikebe11** [comment]
We gave this one a little time and unfortunately no other suggestions came through and we've provided the only suggestion we know of. If you haven't asked tommoor about his React picker and Meteor yet I'd recommend doing that.
