### ISSUE TITLE
PNG sprite doesn't align correctly in Chrome 49+

### ISSUE THREAD

**Issue by andrewchilds** [Ranks/emojione#208]
Hello!

The Emoji One PNG sprite doesn't align correctly in Chrome 49 and 50.

Here is what http://git.emojione.com/demos/2.1.0/sprites-png.html looks like in 48, 49 and 50 at 100% zoom:

Chrome 48 (48.0.2564.116):
<img width="394" alt="emojione-bug-chrome48" src="https://cloud.githubusercontent.com/assets/352089/13362645/a9fd973c-dc93-11e5-8531-088ffba808d3.png">

Chrome 49 (49.0.2623.63 beta):
![emojione-bug-chrome49](https://cloud.githubusercontent.com/assets/352089/13362516/0b621b98-dc93-11e5-92d8-db3003bb4d51.png)

Chrome 50 (50.0.2660.3 canary):
![emojione-bug-chrome50](https://cloud.githubusercontent.com/assets/352089/13362521/14b2f514-dc93-11e5-9ca1-bb2e1d8b0a65.png)

Cheers,
Andrew

**Comment by andrewchilds** [comment]
Here is a possibly related Chromium bug report: https://bugs.chromium.org/p/chromium/issues/detail?id=582417

**Comment by webfella** [comment]
I'm seeing the same issue

**Comment by mikebe11** [comment]
Hopefully, as a bug, this is taken seriously and addressed by Chrome. We have no solution or workaround for this at this time.

**Comment by andrewchilds** [comment]
Not sure if this is the problem, but Slack's emoji implementation works in Chrome 49+ and uses a square 2624x2624 sprite sheet and `background-size: 4100%` (vs. Emoji One's 2624x2560 sprite sheet + `4100% 4000%`). Just mentioning it in case there are no leads.

Chrome 49 is scheduled to hit stable channel this week, according to https://www.chromium.org/developers/calendar.

**Comment by mikebe11** [comment]
Thanks for the tip. We can take a look at that but not sure even Slack is safe, at least at 110% zoom.
![screen_shot_2016-03-09_at_15 58 59](https://cloud.githubusercontent.com/assets/9707818/13654963/cba652b2-e610-11e5-8607-23eed2f92c04.png)

**Comment by mikebe11** [comment]
@andrewchilds We've made a somewhat big change to the PNG sheet css to get the emoji to render without issue. Overall it looks good here. Hopefully the devs for Chrome still put some time into restoring the background-position percentage option.
I'm gonna be optimistic and close this issue. If the new sheet & css don't work for you just reopen it.
Thanks.

**Comment by webfella** [comment]
Nice work @mikebe11, thanks.

**Comment by andrewchilds** [comment]
Agreed - thanks @mikebe11!
