### ISSUE TITLE
I can't select emojis as text with the chrome extension

### ISSUE THREAD

**Issue by NerosTie** [Ranks/emojione#209]
With the Chrome extension, I can't select emojis as text. So, it's a little bit painful to copy-paste texts with emojis inside.

However, a website using the js library and `.toImage(str)`, it works.

**Comment by mikebe11** [comment]
Going to close this issue. This issue forum is reserved for issues related to the repository contents. For items not included here, like the chrome extension, please submit all bugs/questions/suggestions through the contact form on our site, http://emojione.com/contact

I'll copy your comment and pass it along to the extension developer. Feel free to also resubmit your comment through our form if you'd like.
