### ISSUE TITLE
BOY and GIRL pictures are a bit creepy

### ISSUE THREAD

**Issue by salty-horse** [Ranks/emojione#210]
The images for:
- 👦  BOY (U+1F466)
- 👧  GIRL (U+1F467)

have white circles for eyes, circles for irises, and circles for pupils.
These make them look a bit creepy (especially when converted to black and white using external tools).

Please consider shaping the white area of the eyes to look a bit more realistic, similar to:
- 👨  MAN (U+1F468)
- 👩  WOMAN (U+1F469)

**Comment by eosrei** [comment]
Add the baby to the list. O_O haha!

![and the baby too](https://cloud.githubusercontent.com/assets/195061/13506177/b252a7c2-e131-11e5-9615-fa8b7f9d389e.png)

**Comment by Crissov** [comment]
![Boy](https://raw.githubusercontent.com/Ranks/emojione/master/assets/png/1f466-1f3ff.png) ![Girl](https://raw.githubusercontent.com/Ranks/emojione/master/assets/png/1f467-1f3fe.png) ![Baby](https://raw.githubusercontent.com/Ranks/emojione/master/assets/png/1f476-1f3fd.png) ![Man](https://raw.githubusercontent.com/Ranks/emojione/master/assets/png/1f468-1f3fc.png) ![Woman](https://raw.githubusercontent.com/Ranks/emojione/master/assets/png/1f469-1f3fb.png) ![Family](https://raw.githubusercontent.com/Ranks/emojione/master/assets/png/1f46a.png)
Note that the family/group images are not affected.

**Comment by Tymewalk** [comment]
I don't think they're that creepy, but I do think that all the eyes should be one style.
