### ISSUE TITLE
Update for meteor

### ISSUE THREAD

**Issue by mroftalp** [Ranks/emojione#212]
There are emojis that are not converted yet in meteor like :v_tone1:, etc.

**Comment by mikebe11** [comment]
@engelgabriel or @marceloschmidt , can you confirm this and would you have any insight into why this is happening?

**Comment by engelgabriel** [comment]
:v_tone1: works in Rocket.Chat

**Comment by mroftalp** [comment]
![screen shot 2016-03-09 at 12 14 15 pm](https://cloud.githubusercontent.com/assets/6789191/13625247/832eb74c-e5f0-11e5-8280-e51a63beb828.png)

**Comment by mroftalp** [comment]
version emojione:emojione@2.1.1

**Comment by mroftalp** [comment]
emojione.ascii = true;
emojione.unicodeAlt = false;
emojione.imageType = 'png';
emojione.sprites = true;

here are the settings if that would help.

**Comment by engelgabriel** [comment]
@marceloschmidt can you test this?

**Comment by engelgabriel** [comment]
After updating to 2.1.1 `:v_tone1:` stop working on Rocket.Chat too.

**Comment by engelgabriel** [comment]
But `:thumbsup_tone4:` still works... strange.

**Comment by engelgabriel** [comment]
I've opened an issue https://github.com/RocketChat/Rocket.Chat/issues/2458 to track this

**Comment by mikebe11** [comment]
@engelgabriel Just remembered a recent commit for #205  https://github.com/Ranks/emojione/commit/c55da2e1b59dcf070b6f44337a840682a524a756
The latest meteor package probably doesn't have it. It possible to republish a meteor package?

**Comment by engelgabriel** [comment]
I don't think you can republish the same version, you may have to increment the last digit.

**Comment by engelgabriel** [comment]
Make it `2.1.2` to fix the issue #212 :)

**Comment by mikebe11** [comment]
Gonna wait until tomorrow for this. Someone here may have a workaround for issue #208. If it's one they decide to implement I don't want to bump the version now and then do it again tomorrow.

**Comment by engelgabriel** [comment]
OK! Just let us know when to test it again.

**Comment by mroftalp** [comment]
Yeah. Thanks @mikebe11

**Comment by mikebe11** [comment]
@engelgabriel Ready to test. Got my fingers crossed.

**Comment by engelgabriel** [comment]
It worked!

**Comment by mikebe11** [comment]
Excellent. I'll close this. If you still have a problem @mroftalp just reopen this issue. Thanks.
