### ISSUE TITLE
Emoji problem using iPhone 6 

### ISSUE THREAD

**Issue by Leinad4Mind** [Ranks/emojione#213]
Hi take printscreens from all icons of iphone 6, in the last iOS version: http://imgur.com/a/GLzcY

As we can see some icons has a problem when sending through iOS... from Android all is fine.

Cheers

**Comment by mikebe11** [comment]
Not sure where to start here. Can you provide some more details about how you generated all of the icons? JS or PHP library? What function/s were used?

**Comment by mikebe11** [comment]
@Leinad4Mind Following up to see if you have any more details on the setup that generated your images? We don't know where to begin looking to see if this is an issue with one of our files.

**Comment by Leinad4Mind** [comment]
I'm using this //cdn.jsdelivr.net/emojione/assets/svg/ to load all the SVG
And if the server doesnt respond I'm using local SVG
I've a JS file that loads all the SVG images from those places.

**Comment by mikebe11** [comment]
Hmm, checked the CDN and it's serving the correct images. Are you using our JS file or your own? Is it `unicodeToImage` or `shortnameToImage` that appears to be giving you problems?

**Comment by mikebe11** [comment]
@Leinad4Mind I was finally able to run a test on an iPhone 6 using both `unicodeToImage` and `shortnameToImage` functions. All of the emoji rendered fine.
I'm gonna close this issue but if you have some code to share that you think will show where our library is failing feel free to reopen this and include that.
