### ISSUE TITLE
<span>::shortcode::</span>

### ISSUE THREAD

**Issue by dsovino-alma** [Ranks/emojione#214]
Hi.

Found a possible bug on parsing strings with html span tag, (o maybe I missed some documentation?)

To test it out:

[http://git.emojione.com/demos/2.1.2/jstoimage.html]

Test String:
`<span>:relaxed::high_heel::watch::mans_shoe::lipstick::beginner:</span>`

Then change `<span></span>` for `<p></p>` or whatever you want.

Cheers!

**Comment by mikebe11** [comment]
Double checked it and it looks ok. The library's regular expressions don't allow for conversion of data within `<object></object>` and `<span></span>`. 

`ns.regShortNames = new RegExp("<object[^>]*>.*?<\/object>|<span[^>]*>.*?<\/span>|<(?:object|embed|svg|img|div|span|p|a)[^>]*>|("+ns.shortnames+")", "gi");`

Many of our conversions are into those tags. Try the demo with anything else and it should convert fine. If you need your implementation to convert what's in those tags all you need to do is to change the regular expression variables.

**Comment by dsovino-alma** [comment]
So I was missing documentation then, since i never saw anything warning that objects and spans were meant to be excluded. If it is that the case, i guess i can close this. I applied a fix for this on my own implementation.

Thanks for the time.
