### ISSUE TITLE
Squirrel 1f43f has three undefined path fills

### ISSUE THREAD

**Issue by eosrei** [Ranks/emojione#215]
There are missing fill colors on three paths in: https://github.com/Ranks/emojione/blob/6a17f05781837b5379a4c02e81c674c47b199cce/assets/svg/1f43f.svg

The paths are identified in Inkscape as *path42*, *path26* and *path6*. I assume they should be set to #000000.

![missing fills](https://cloud.githubusercontent.com/assets/195061/13856686/99226442-ec33-11e5-8887-7c96eb0fd832.png)

Causes https://github.com/eosrei/emojione-color-font/issues/21

**Comment by mikebe11** [comment]
Won't be difficult to add that attribute. Might not be pushed till the next art update. In the meantime you can try this file to see if it fixes your issue. I quickly added the fills in a text editor.
[1f43f.svg.zip](https://github.com/Ranks/emojione/files/178618/1f43f.svg.zip)

**Comment by eosrei** [comment]
Hmm.. That makes the file valid in Inkscape, although it doesn't fix the glyph selection weirdness. I've changed the `#000000` to `#010101` and that stopped it. Apparently Firefox inverts all `#000000` black on selection that must be the defining factor. I checked a number of other animal eyes. They are `#3e4347`, `#000000` probably isn't right to "fit" in with Emoji One graphics.

**Comment by mikebe11** [comment]
I see the cow face, 1f42e, also has unfilled paths in the eyes and eyelids. You didn't have the color inversion issue with that one?

**Comment by eosrei** [comment]
The cow is filled by the group `<g fill="#3e4347">`: https://raw.githubusercontent.com/Ranks/emojione/6a17f05781837b5379a4c02e81c674c47b199cce/assets/svg/1f42e.svg It's fine.

![cow_fill](https://cloud.githubusercontent.com/assets/195061/13867948/6b711608-ec81-11e5-9265-e2b2991c4014.png)

**Comment by mikebe11** [comment]
Got it. I was selecting them individually.

**Comment by mikebe11** [comment]
@eosrei This issue ready to be closed or is there anything else we might want to consider with the SVGs?

**Comment by eosrei** [comment]
I figure the issue would be closed by a PR fixing the issue. I'd fix it, but been caught up with a few things. Can we leave it for a PR?

**Comment by mikebe11** [comment]
We'll have to think on this. It's not quite an issue except with font building. According to the W3C spec default color for fill is black so it appears the SVG is technically valid. 
https://www.w3.org/TR/SVG/painting.html#FillProperty
If that's the case we may consider the required fill for fonts an edge case that's of lower importance and just make note of it in the font readme.
If we do add the fill it'll be included it in the next quarterly art update. Due to copyright we won't accept a PR for it, even for something this minor.

**Comment by eosrei** [comment]
Yes, I understand after looking at this further that the SVG is technically valid, but the eye color is inconsistent with the rest of the Emoji One set. That's actually the primary *minor* issue. The squirrel eyes should be `#3e4347`. I wasn't even worried about when I first noticed it and only opened this issue because a font user created an issue on my queue about it. I've already closed that issue stating it will be fixed when fixed in the source.

Side Note: I do think it's interesting for SVGinOT font builders to be aware that selecting text causes only `#000000` to change. No other colors do. I'll be making a note of this in my build system docs.

> If we do add the fill it'll be included it in the next quarterly art update. Due to copyright we won't accept a PR for it, even for something this minor.

This really surprises me. A CLA is standard practice when there are copyright ownership concerns.  I've already signed the Google CLA for my work on Kubernetes for example:  https://cla.developers.google.com/about/google-individual?csw=1 Would you consider creating a CLA?

**Comment by mikebe11** [comment]
Definitely a good idea to make note of the change of `#000000`in your docs.

My initial thought is that a CLA wouldn't be desired here but that's just my assumption. Moving in that direction isn't my decision. I'll pass the idea along to those who would consider that.

I'm told this issue can be closed. The chipmunk has been worked on for the next release. I checked it out and it looked the same. Perhaps the visual changes are minor or just some layering of the paths were altered. It looks like the design team has decided to keep the eye and stripe black.

**Comment by eosrei** [comment]
I didn't realize graphic change PRs weren't accepted for this project, but I see it's listed here: https://github.com/Ranks/emojione/blob/a3321d7d22ea482aa229269e02fa081beb889d28/CONTRIBUTING.md#emoji-art-png--svg

:+1: for a CLA.
