### ISSUE TITLE
aliases for :custard: 

### ISSUE THREAD

**Issue by mcfiredrill** [Ranks/emojione#216]
In Japan, people would usually call this "pudding", in other parts of the world "flan".
Can we consider adding aliases for this emoji?

**Comment by mikebe11** [comment]
We can certainly consider it. I’ll pass your request along. If it’s approved you’ll be notified that it’s been done or is in progress. Thanks

**Comment by mikebe11** [comment]
@mcfiredrill The "pudding" and "flan" aliases have been approved. They'll eventually be added. Thanks for the suggestion.

**Comment by mcfiredrill** [comment]
@mikebe11 Thanks! :custard: :raised_hands:

**Comment by tymscar** [comment]
:custard:

**Comment by mikebe11** [comment]
@mcfiredrill Custard aliases added in commit 91172baff56057774c625a8c0c61135924fee6eb

**Comment by mcfiredrill** [comment]
:raised_hands: :custard: :custard: :custard: :custard: :custard: :raised_hands:
