### ISSUE TITLE
CLBC table has mismatching ppem x and y fields leading to glyph overlap

### ISSUE THREAD

**Issue by fdwr** [Ranks/emojione#218]
The CBLC table (in the Android export) has ppem fields set to 106 when the actual bitmap assets are 128x128. This leads to glyph overlap when rendering because the em box from the head table is 1000, and the advances from the hmtx table are 1000, but when displayed at 128 ppem, you get 1.2x overscaling (128 / 106).

![emojionecblctableppemvalues](https://cloud.githubusercontent.com/assets/1809166/13939880/f7f6e2ee-ef95-11e5-8d6c-61fe605e9d84.png)

Assets:

![emojionepngassets](https://cloud.githubusercontent.com/assets/1809166/13939989/0adc2ba2-ef97-11e5-99f1-4ef5664991c6.png)

Top row is the sbix font (looks good). The bottom row is the CBDT font, with glyph overlap: 

![emojionecbdtoverlap](https://cloud.githubusercontent.com/assets/1809166/13939654/2517d6d6-ef94-11e5-8476-316028aa93b1.png)

Changing the bitmap size table ppem fields to 128 fixes the issue:

![emojionecbdtoverlapfixed](https://cloud.githubusercontent.com/assets/1809166/13939920/65766538-ef96-11e5-9562-3f06e34da2c6.png)

*Interestingly there are some differences between the latest available sbix vs latest CBDT font, including the hair color of the boy in the boat and the penguin's eye size, but I assume that one file is just newer than the other.

**Comment by miguelsousa** [comment]
The font uses 106 instead of 128 because of issue #166.

Where is this overlapping happening?

The differences between the Android and the Apple fonts is because the former has been updated with the 2016 Q1 changes (#193) whereas the latter has not.

**Comment by mikebe11** [comment]
closing this based on the merge of PR #225

**Comment by Jolg42** [comment]
Hi @fdwr,
I can see you used 010 Editor with an "OpenTypeTemplate.bt" but I can't find it… Is it available somewhere? 😉

**Comment by fdwr** [comment]
Joël, you are welcome to use it. http://pikensoft.com/programs/OpenTypeTemplate.bt

(I never bothered uploading it anywhere until just now because it was mainly useful to me).

**Comment by Jolg42** [comment]
Thank you @fdwr 🙏  I think that can help more people who are also manipulating OpenType fonts!   

Ping: @fdb @fpirsch @brawer @moyogo @Pomax @miguelsousa @davelab6 @graphicore @louisremi @FranzPoize @ghenania

Here is 010 Editor website : http://www.sweetscape.com/010editor/
With the OpenTypeTemplate.bt from @fdwr in the precedent comment it's really easy read & write in binary directly now :)

**Comment by FranzPoize** [comment]
Fuck yeah that is awesome. Thanks!
