### ISSUE TITLE
Why is this line necessary?

### ISSUE THREAD

**Issue by nikgraf** [Ranks/emojione#219]
I was wondering why you execute the Regex here: https://github.com/Ranks/emojione/blob/master/lib/js/emojione.js#L15

**Comment by mikebe11** [comment]
That line was to fix #143.  The + in shortname `:+1:` would otherwise become a quantifier in a later regular expression.

**Comment by nikgraf** [comment]
ahh, thx

**Comment by mikebe11** [comment]
welcome
