### ISSUE TITLE
How to resize emoji when using PNG sprites

### ISSUE THREAD

**Issue by sampaiodiego** [Ranks/emojione#220]
The [demo page](http://git.emojione.com/demos/2.1.2/sprites-png.html) shows a 64x64 size emoji at the top of the page.

How can I use these sprites to show a 32x32 size emoji for example?

The `transform: scale()` recommended pattern does not resize the element, just the visual of the emoji and does not allow a precise size control.

**Comment by mikebe11** [comment]
Don't have a simple answer for that. You could create a new sheet in the preferred size. You could revert back to our previous PNG sprite setup that used % for background position and seemed to allow for more flexibility in sizing. But in taking that route you'll go back to having the issue with Chrome that we had a while back.
Sorry, but the current setup was the best option we found for now. If you discover a better setup please do let us know.

**Comment by sampaiodiego** [comment]
Ok, thought I was missing something :smile: 
Chrome 49 is already released and I do not see the problems mentioned on the issue, so I'll give it a try.
Thanks

**Comment by engelgabriel** [comment]
@mikebe11 could you guys still support the CSS that uses % positions? Is there a way to generate both CSS files and let people decide what to use?

**Comment by mikebe11** [comment]
@engelgabriel I don't think we'd want to expand the offerings in that way. We want to provide something that's most compatible. For now, with the current Chrome issue, that's pixel position. Including an option for something that's currently buggy just means more content to update and more potential for confusion for users and issues to address. Plus, many people aren't that familiar with sprite sheets so all together adding another layer on that doesn't seem like a good choice for us.
If the Chrome developers attend to the issue with PNG sprite sheets I would be in favor of returning to the % positions. Personally, I think it's more flexible. Hopefully they look at it soon.

**Comment by liudanking** [comment]
@sampaiodiego how did you solve the white space (e.g., scale to 32px, makes 16px white space in both left and right) after using scale method?

**Comment by sampaiodiego** [comment]
@liudanking I'm using [this mustache file](https://github.com/RocketChat/Rocket.Chat/blob/develop/packages/rocketchat-emoji-emojione/emojione.sprites.mustache) to regenerate the old percentage style CSS, so I can use it in any size I want (currently only 22px and 44px)

**Comment by liudanking** [comment]
@sampaiodiego many thanks. It's a pretty nice resource.
