### ISSUE TITLE
<div> tag become undefined

### ISSUE THREAD

**Issue by hcw2175** [Ranks/emojione#230]
i get the element html content like `<div><br/></div><div><br/></div>`, 

when i use method  `emojione.toShort(str)`,

 i get the str is `undefined<br></div>undefined<br></div>`.

how can i fix this?

**Comment by mikebe11** [comment]
This was found recently. Waiting on confirmation about a fix. You can check it out here and try it out in the meantime. https://github.com/Ranks/emojione/pull/53#issuecomment-203644972

**Comment by mikebe11** [comment]
fixed with 91172baff56057774c625a8c0c61135924fee6eb

**Comment by mroftalp** [comment]
@mikebe11 is there a way to update this package with Meteor 1.2?

**Comment by mikebe11** [comment]
I'll have to manually publish. Meteor is supposed to auto publish when there's a new release.

**Comment by mroftalp** [comment]
I was trying to meteor update emojione:emojione but I wouldn't let me it says top-level dependencies incompatible?

**Comment by mikebe11** [comment]
@mroftalp We didn't set up Meteor and I don't know it so I'm afraid I can't help you there.
@engelgabriel @marceloschmidt any thoughts on the top-level dependencies incompatible error here?

**Comment by engelgabriel** [comment]
@sampaiodiego ideas?

**Comment by sampaiodiego** [comment]
@mroftalp try updating the package again.. I just ran `meteor update emojione:emojione` and got the new 2.1.4 version with the fix..

**Comment by mroftalp** [comment]
@sampaiodiego Thanks it worked! :)
