### ISSUE TITLE
Add tools used to generate fonts to repo

### ISSUE THREAD

**Issue by hadess** [Ranks/emojione#233]
The fonts at:
https://github.com/Ranks/emojione/tree/master/assets/fonts
don't seem to have any ways to reproduce them from the original sources.

(or I can't find them)

**Comment by mikebe11** [comment]
The fonts we offer are built and provided by generous users with font experience. We offer them for those who would like to play with our emoji in a font but we don't do any work on them ourselves. We already rely on those users to update and provide support for small font issues. We won't be adding any tools for font building at this time. We cannot add more items that offer potential for repo issues that we cannot provide support for.

We appreciate the suggestion but anyone looking to get into building fonts will have to look outside this repo for any items, besides emoji, needed to do so.

There may be some useful resources for font building here: https://github.com/eosrei/emojione-color-font

**Comment by hadess** [comment]
I would hope that @miguelsousa could instead tell me which tool he uses to generate the fonts.

The upstream repo only contains the tools to build the SVG-in-OTF fonts (compatible with Adobe tools and Firefox), not what's implemented in FreeType and usable on Linux and Android.

FWIW, Google uses scripts to build their Noto emoji fonts:
https://github.com/googlei18n/noto-emoji

And if Miguel uses the same tools, then we could all contribute :)

**Comment by mikebe11** [comment]
We still won't add the tools but if you'd like to change the title and use this issue to solicit advice and tool suggestions we can reopen it and leave it open for a little bit.

@miguelsousa has been very helpful with the fonts and may have some advice to share.

**Comment by miguelsousa** [comment]
@hadess first I build a TrueType font using the [FDK](http://www.adobe.com/devnet/opentype/afdko.html), and then I post-process it with customized versions of the scripts found in this repo https://github.com/behdad/color-emoji/

**Comment by hadess** [comment]
@miguelsousa could you make those available?

**Comment by miguelsousa** [comment]
@hadess I'd rather not because they aren't ready for public consumption, and I don't want to have yet another project that people bug me about.

**Comment by hadess** [comment]
Even privately? We're interested in supporting emojis in GNOME, and we would have a couple of fonts people looking at the tooling, and quite a few artists who could then contribute with an immediate effect to the upstream emoji one font.

It would also mean that this repo can focus on its core goal, delivering software for web developers.

**Comment by miguelsousa** [comment]
@hadess if you're really commit to that effort use the scripts that I pointed you at. They're your best start.

**Comment by hadess** [comment]
Disappointing, but I'll live with it. FWIW, we're likely going to use the noto-emoji build system instead:
https://github.com/googlei18n/noto-emoji/issues/9

**Comment by kq01526** [comment]
> @hadess wrote:
> 
> [...] We're interested in supporting emojis in GNOME [...]
> 
> [...] we're likely going to use the noto-emoji build system instead:
googlei18n/noto-emoji#9

If you want to properly support color Emojis in GNOME, you probably would first have to look at the following issue:

https://github.com/googlei18n/noto-emoji/issues/9

:wink:

**Comment by eosrei** [comment]
FWIW I plan to add CBDT/CBLC and SBIX font output to the [build system](https://github.com/eosrei/scfbuild) used to make: https://github.com/eosrei/emojione-color-font
