### ISSUE TITLE
Faint narrow contrasting border for Emojis to keep them visually distinct from a similarly colored background (as recommended by UTR 51)?

### ISSUE THREAD

**Issue by kq01526** [Ranks/emojione#234]
Hello,

today Microsoft showed their brand new Emojis, see:

https://blogs.windows.com/windowsexperience/2016/04/06/announcing-windows-10-insider-preview-build-14316/

In the blog post they say:

> the two-pixel outline allows for emoji to appear on any color background without loss of fidelity.

IMHO this looks very good and makes a lot of sense.

Actually even the [Unicode Technical Report 51](http://www.unicode.org/reports/tr51/) recommends to give Emojis a faint, narrow contrasting border to keep them visually distinct from a similarly colored background.

Wouldn't it be a good idea to apply this to Emoji One as well?

[Looks like this was also suggested for Twemoji.](https://github.com/twitter/twemoji/issues/62)

**Comment by mikebe11** [comment]
Thank you for the suggestion. It was also suggested for our previous collection, #60.
The designers have been aware of the narrow border recommendation for many months. While they do appreciate the Unicode specs and recommendations they've decided not to adopt that border in the current set.
