### ISSUE TITLE
Potentially sensitive emoji naming

### ISSUE THREAD

**Issue by szhuge** [Ranks/emojione#236]
Hi!  We use emojione and directly take the naming from the emojione code base.

We've noticed one of the emoji is called "white smiling face" (http://emojipedia.org/white-smiling-face/) which takes from the pre-Unicode white-black naming convention between hollow and filled-out emoji.

Is there any thought on updating the emoji naming to just "smiling face", given that the white-black distinction is obsolete, and could be confused for "white" in the racial sense?

Thanks!

**Comment by Naudiz** [comment]
You are requesting this from the wrong people.
The names of emojis are defined by the Unicode standard. There's nothing EmojiOne can do about it. If you want any changes done to the standard, you should address the Unicode Consortium.
However, I highly doubt that anyone will accept your request, as the distinction between characters U+263A (white smiling face) and U+263B (black smiling face) is still relevant for all purposes outside the scope of emojis, like simple B/W-fonts.

**Comment by mikebe11** [comment]
@szhuge Thanks for the question but we won't be changing the name unless it's changed by the Unicode Consortium. We certainly don't intend to be racially insensitive here but Unicode sets the standard and we follow that with our data.
Hopefully people take the time to find out the meanings used by Unicode within the context of emoji,

> Similarly, in other symbols such as the hands U+261A BLACK LEFT POINTING INDEX and U+261C WHITE LEFT POINTING INDEX, the words “white” and “black” also refer to outlined versus filled, and do not indicate skin color.

*http://www.unicode.org/reports/tr51/index.html*
