### ISSUE TITLE
Error on trying to compile. [grunt]

### ISSUE THREAD

**Issue by NavyCo** [Ranks/emojione#237]
```
grunt
Running "jshint:files" (jshint) task
>> 2 files lint free.

Running "jsonlint:files" (jsonlint) task
>> 2 files lint free.

Running "sprite:pngsprites" (sprite) task
Files "assets/sprites/emojione.sprites.css", "assets/sprites/emojione.sprites.png" created.

Running "sass:dist" (sass) task

Running "svgstore:default" (svgstore) task
File assets/sprites/emojione.sprites.svg created.

Running "uglify:dist" (uglify) task
>> 1 file created.

Running "cssmin:target" (cssmin) task
>> 2 files created. 100.18 kB → 86.82 kB

Running "imageoptim:pngs" (imageoptim) task
Fatal error: ImageOptim-CLI exited with a failure status
```

**Comment by NavyCo** [comment]
Got the majority of it to work, but the sprites.svg aren't working correctly

**Comment by mikebe11** [comment]
I've always optimized manually so I've never tried or looked closely at that grunt task. Turns out it automates the Mac app. To do so ImageOptim needs to already be installed. The task ran fine for me so my guess is ImageOptim-CLI went looking for ImageOptim and didn't find it so it exited with the failure status. Did you already have ImageOptim installed when you ran grunt?

**Comment by NavyCo** [comment]
No, I'm running using a Windows OS.

**Comment by NavyCo** [comment]
Works perfect without the ImageOptim, now another error to address:
```This page contains the following errors:
error on line 1 at column 5812: Namespace prefix rdf on RDF is not defined
Below is a rendering of the page up to the first error.``` That is referencing to ```<rdf:RDF> <cc:Work rdf:about=""> <dc:format>image/svg+xml</dc:format> <dc:type rdf:resource="http://purl.org/dc/dcmitype/StillImage"/> </cc:Work> </rdf:RDF>```

**Comment by mikebe11** [comment]
We'll probably extract ImageOptim from the default task list and put it into it's own so other PC users don't get stuck in that spot.
What's running that's generating that new error? Is that also during grunt's execution?
