### ISSUE TITLE
[Planning] Restructuring PHP Conversion

### ISSUE THREAD

**Issue by Art4** [Ranks/emojione#24]
:+1: for 29442383ec0cf9f78f2826e47ed9773f53847554.

Like I said in #23 it would be great if we have a better integration in other frameworks, so this is my plan to restructure the PHP conversion.

# Moving to namespace Emojione

First I would recommend to move the class inside the namespace ```Emojione```. This can be done now and asap to reduce the work for developers in future. All PHP demos must be changed to ```Emojione\Emojione```.

# Split the class

Then It would be easy to split the class into 3(+1) Parts:

1. **Emojione\Ruleset** This class implement ```RulesetInterface``` and is generated by the database. It should have a big notice on top not to modify the file.
2. **Emojione\Config** This class implements the ```ConfigInterface```. It requires a ```RulesetInterface``` and has methods to extend and get the rules.
3. **Emojione\Client** This class does the main work. It requires a ```ConfigInterface``` and has all existing methods ```toShort()```, ```shortnameToImage() ```, ```toImage($str) ```, etc.

This would allow to build a client with fully customizable configuration:

```php
// Default or custom ruleset
$ruleset = new Emojione\Ruleset;
$ruleset = new My\Own\Ruleset;

// Default or custom configuration ...
$config = new Emojione\Config($ruleset);
$config = new My\Own\Config($ruleset);
$config->useSprites(true);
// ... with extra shortcodes
$config->addShortcode(':youtube:', 'icon_youtube.png');

// client usage
$emojione = new Emojione\Client($config);
$emojione->toShort('Hello world! 😄');
// returns "Hello world! :smile:"
```

+1. **Emojione\Emojione** This is a static flyweight. It provides the simple [PHP Conversion](http://git.emojione.com/demos/index.html#php) like the current ```Emolione.class.php``` but works with the client behind the scene. This will also be need for backward compatibility.

```php
// behind the scene: inside Emojione\Emojione
public static toShort($str)
{
    $ruleset = new Ruleset;
    $config = new Config($ruleset);
    $client = new Client($config);

    return $client->toShort($str);
}

// usage
Emojione\Emojione::toShort('Hello world! 😄');
// returns "Hello world! :smile:"
```

# Planning the Interfaces

First we need to know which parts of ```Emolione.class.php``` are generated by database.

## Emojione\RulesetInterface

The generated parts will be the default ruleset in **Emojione\Ruleset** and will form ```Emojione\RulesetInterface```. I assume this parameters:

- $ignoredRegexp
- $unicodeRegexp
- $shortcode_replace
- $ascii_replace
- $unicode_replace
- $asciiRegexp

## Emojione\ConfigInterface

All other parameters will be set in **Emojione\Config**:
- protected $ascii = false; // convert ascii smileys?
- protected $unicodeAlt = true; // use the unicode char as the alt attribute (makes copy and pasting the resulting text better)
- protected $imageType = 'png';
- protected $sprites = false;
- protected $imagePathPNG = '//cdn.jsdelivr.net/emojione/assets/png/';
- protected $imagePathSVG = '//cdn.jsdelivr.net/emojione/assets/svg/';
- protected $imagePathSVGSprites = './../assets/sprites/emojione.sprites.svg';
- protected $unicode_replaceWith = false;
- protected $shortcodeRegexp = ':([-+\\w]+):';

**Comment by emitstop** [comment]
We are gonna close this issue for now as there hasn't been activity on it for awhile, but we can reopen it again later if you want. Thanks for your contributions, always appreciated. :)

**Comment by Art4** [comment]
Ok. :-) Unfortunately I don't have the time to contribute atm. I'll work on it later.

**Comment by Art4** [comment]
Ok, we're getting closer to use Emojione in our project and I will take the time to refactor the code. I put some thoughts and the above comments together and create this updated plan:

# Writing tests

To make sure that the refactored code works as expected, we need some tests.

# Split the class

Then It would be easy to split the class into 2(+1) Parts:

1. **Emojione\Ruleset** This class implements ```RulesetInterface``` and is generated by the database. It should have a big notice on top not to modify the file.
2. **Emojione\Client** This class does the main work and implements ```Emojione\ClientInterface``. It requires a ```RulesetInterface``` object and has the configuration and all existing methods like ```toShort()```, ```shortnameToImage() ```, ```toImage($str) ```, etc.

This would allow to build a client with fully customizable configuration:

```php
// Default or custom ruleset
$ruleset = new Emojione\Ruleset;
$ruleset = new My\Own\Ruleset;

// load the emojione client
$client = new Emojione\Client($ruleset);
// or use your own client
$client = new My\Own\Client($ruleset);

// client configuration
$client->useSprites(true);
$client->addShortcode(':youtube:', 'icon_youtube.png');

// client usage
$client->toShort('Hello world! 😄');
// returns "Hello world! :smile:"
```

+1. **Emojione\Emojione** This is a static flyweight. It provides the simple [PHP Conversion](http://git.emojione.com/demos/index.html#php) like the current ```Emolione.php``` but works with the client behind the scene. This will also be need for backward compatibility.

```php
// behind the scene: inside Emojione\Emojione
public static toShort($str)
{
    $ruleset = new Ruleset;
    $client = new Client($ruleset);

    return $client->toShort($str);
}

// usage
Emojione\Emojione::toShort('Hello world! 😄');
// returns "Hello world! :smile:"
```

## Emojione\Ruleset

The generated parts will be the default ruleset in **Emojione\Ruleset** and will implement ```Emojione\RulesetInterface```. It will have a big notice on top like "*Autogenerated. Do not edit this file*".

It has this parameters:

- $shortcode_replace
- $ascii_replace
- $unicode_replace
- $asciiRegexp

## Emojione\Client

All other parameters will be set in **Emojione\Client**`:
- protected $ascii = false; // convert ascii smileys?
- protected $unicodeAlt = true; // use the unicode char as the alt attribute (makes copy and pasting the resulting text better)
- protected $imageType = 'png';
- protected $sprites = false;
- protected $imagePathPNG = '//cdn.jsdelivr.net/emojione/assets/png/';
- protected $imagePathSVG = '//cdn.jsdelivr.net/emojione/assets/svg/';
- protected $imagePathSVGSprites = './../assets/sprites/emojione.sprites.svg';
- protected $unicode_replaceWith = false;
- protected $shortcodeRegexp = ':([-+\\w]+):';
- protected $ignoredRegexp = '<object[^>]*>.*?<\/object>|<span...';
- protected $unicodeRegexp = '([#0-9](?>\\xEF\\xB8\\x8F)?\\xE2...';
