### ISSUE TITLE
:heart: ❤ not rendering properly

### ISSUE THREAD

**Issue by bryan-jowers** [Ranks/emojione#241]
We're using emojione. the normal heart is not converting from ios to web. all other hearts do render properly sent from iOS. 

![screen shot 2016-05-03 at 5 27 38 pm](https://cloud.githubusercontent.com/assets/4181898/15002281/672ac6fa-1154-11e6-8055-230a3d34883d.png)

**Comment by caseyahenson** [comment]
@bryan-jowers can you provide a little more information about your implementation? We're unable to re-create the issue on our end. I assume you're using shortnameToImage?
