### ISSUE TITLE
shortnameToImage can convert :dolphin: but not :flipper:

### ISSUE THREAD

**Issue by kngchn** [Ranks/emojione#242]
My colleague use other lib to convert unicode to shortname on ios, now i can't convert it back by using shortnameToImage prived by emojione. Seems like they are alternatives. How to solve it?

**Comment by caseyahenson** [comment]
@kngchn You can alter the "ns.emojioneList" and add a new property for shortname "flipper".  For example: 

`":dolphin:":{"unicode":["1f42c"],"isCanonical":` true},":flipper:":{"unicode":["1f42c"],"isCanonical": false},":mouse:":{"unicode":["1f42d"],"isCanonical": true},`

or if you use the CDN you can add this to your code:

`emojione.emojioneList[":flipper:"] = {"unicode":["1f42c"],"isCanonical": false};`
`emojione.shortnames += "|:flipper:";`
`emojione.regShortNames = new RegExp("<object[^>]*>.*?<\/object>|<span[^>]*>.*?<\/span>|<(?:object|embed|svg|img|div|span|p|a)[^>]*>|("+emojione.shortnames+")", "gi");`

**Comment by kngchn** [comment]
I try it. It works with some modification with your CDN code.
`emojione.emojioneList[":flipper:"] = ["1f42c"];`
Thank you for the solution.
