### ISSUE TITLE
How to scale the spritesheet?

### ISSUE THREAD

**Issue by tleunen** [Ranks/emojione#243]
Now that the spritesheet is in fixed position, how are we supposed to scale it?

**Comment by caseyahenson** [comment]
@tleunen you have a couple of options with the sprites update. You could use the css transform:scale property, or (although not as widely supported) the zoom property, either one should get you where you need to be. 

If you'd prefer, you can also revert to using the % mustache file from a previous commit and then remake the png sheet and css. Hope that helps!

**Comment by emitstop** [comment]
Unfortunately neither of those two solutions are very workable. The zoom property is non-standard and doesn't work in firefox, and transform scale is just a visual scaling, the icons will still take up 64px of space in the content, so if you were to shrink the icons down to a diameter of 16px that would create 24px of empty space around the icon.

The one thing I think could be improved is that 64x64 seems a bit too large for practical use, setting them to 32x32 or 24x24 by default might be a better compromise and minimize the spacing issues for those who now need to use transform scaling.

**Comment by tleunen** [comment]
If I understand, the reason why you changed for a pixel based sheet instead of a percentage based is because of a chrome issue...

But do we know if they plan to fix it? Or maybe it's already resolved?
What do you think of having both the percentage and pixel based sheet in the project?

**Comment by caseyahenson** [comment]
@emitstop thanks for the input! @tleunen we've definitely thought a lot about what makes the most sense as a solution to this problem and we're hoping to see a Chrome update in the near future that will allow us the option to revert back to percentages as a standard.

**Comment by tleunen** [comment]
So what's the good solution for that? Forking the repo? Doesn't seem right.

**Comment by tleunen** [comment]
hey @caseyahenson, can we go back to use percentage in the png spritesheet? I don't know if the issue is fixed in Chrome (haven't tested it). But Google (Hangout) and Slack for example uses png spritesheet with percentage, so I'm guessing the rendering is not bad.

**Comment by caseyahenson** [comment]
I'll revisit this issue within the next couple of weeks. Chrome is advancing pretty quickly and I haven't checked into this in some time.

**Comment by MerlinBB** [comment]
This would be super useful for the emojione picker project - https://github.com/mervick/emojionearea - currently has to load 1600 pngs 😬

**Comment by vgavro** [comment]
Maybe it would be useful to link related ticket on chrome bugtracker? is this chrome issue already closed?
