### ISSUE TITLE
Comment on eyes

### ISSUE THREAD

**Issue by PascalPencil** [Ranks/emojione#245]
All the smiley emoji have simple black circles for eyes, this flat style matches with the rest of the style of your set.
In the recent update you removed the white in the eyes of the bug, turtle, but added white into the eyes of the monkeys, hamster, cow.
I believe that you should move to whites in the eyes only with humans since it creates contrast in darker skintones, but leave all animals with simple black ovals or circles for their eyes, it fits your set's style better.

**Comment by caseyahenson** [comment]
@PascalPencil great feedback on all of these issues, thank you! We have an artwork update coming out soon that will address many of the inconsistencies you mention in this and susequent issues. Any that aren't addressed in this update will be analyzed in future updates. Thanks again!

**Comment by PascalPencil** [comment]
I'd be happy to contribute if you like, keep up the good work
