### ISSUE TITLE
Undefined ASCII shortname

### ISSUE THREAD

**Issue by veneliniliev** [Ranks/emojione#253]
**ERROR:**
ErrorException in Client.php line 283:
Undefined index: &lt;3

`$unicode = $ascii_replace[$shortname];`

**Comment by Venko007** [comment]
`if(empty($ascii_replace[$shortname])){
                return $m[2];
            }`

this code fix error.

**Comment by caseyahenson** [comment]
Fixed in upcoming patch 3.0.1.
