### ISSUE TITLE
No properly converts number emojis from unicode

### ISSUE THREAD

**Issue by mervick** [Ranks/emojione#254]
Below screenshot:
![bug](https://cloud.githubusercontent.com/assets/2429298/15610439/ee77461a-242d-11e6-8dad-1943d3f2eeea.png)
At the top - converts from unicode;
At the bottom properly converts from shortnames.

I tested, in js, and the same result got from php client.

**Comment by caseyahenson** [comment]
@mervick I'll look into this as soon as possible, thanks for pointing that out!

**Comment by caseyahenson** [comment]
@mervick Can you test this issue out again and see if you're getting better results?

**Comment by mervick** [comment]
Not it doesn't fixed yet, 
I found the solution and if you don't mind I can create a pull request

**Comment by mervick** [comment]
Yes it fixed!

**Comment by mervick** [comment]
Sorry, it still doesn't work in php
