### ISSUE TITLE
Minor glitch in SVG path in the glyph 1f917.svg

### ISSUE THREAD

**Issue by jfkthame** [Ranks/emojione#255]
There's an odd glitch in one of the paths that makes up 1f917.svg. This can be seen as an unexpected vertical line across part of the gray outline of the hand, dropping down from the red-highlighted control point in the attached screenshot.

Dragging that point slightly left in Inkscape reveals that the outline dips down and then up again in a thin (zero-width?) "spike".

This doesn't result in any visible problems when I view the SVG graphic, but it interferes with import of the SVG outlines into fontforge for conversion purposes; it would be very helpful if this could be cleaned up.

(There seem to be other redundant points on this outline, too, particularly at the junction between the thumb and forefinger. But this is the one that seems to be causing particular problems.)

<img width="1440" alt="screen shot 2016-05-27 at 21 07 25" src="https://cloud.githubusercontent.com/assets/1706499/15619925/255c8db8-244f-11e6-9879-683746ac6420.png">

**Comment by caseyahenson** [comment]
@jfkthame Great catch, thank you for pointing that out! We'll look into cleaning this up right away. It may have even been resolved in our 2.2 update (coming soon!), but I'll double check on that and keep you posted.

**Comment by jfkthame** [comment]
Looks like this glyph has been re-drawn for the 2.2 update, and I'm no longer seeing this problem.
