### ISSUE TITLE
Emojione with Meteor

### ISSUE THREAD

**Issue by sangyoo91** [Ranks/emojione#256]
The package won't work with the latest version of Meteor.

Also, when I try 
```
emojione.toImage(':)')
```
it will output as :) rather than an emoji on my project.

However,

```
emojione.toImage(':smile:')
```

will work.

Am I doing something wrong?

**Comment by caseyahenson** [comment]
@sangyoo91 I'll check into what's going on with Meteor and get back to you ASAP.

As for the smiley conversion, toImage() is intended to convert both Unicode and our :shortname: formats to emoji and by default does not handle ASCII. For ASCII conversion you'll need to set emojione.ascii = true as in: http://git.emojione.com/demos/2.2.0/ascii-smileys.html. Hopefully that resolves it for you.

**Comment by caseyahenson** [comment]
@sangyoo91 Please check your Meteor installation again and let me know if the issue is addressed.
