### ISSUE TITLE
v2.2.0 assets missing the skin modifiers 1f3fb - 1f3ff

### ISSUE THREAD

**Issue by Naudiz** [Ranks/emojione#259]
In the latest SVG and PNG download pack there are no longer the skintone icons, which were present in 2.0 and 2.1. Unicode codes are:
1f3fb
1f3fc
1f3fd
1f3fe
1f3ff

These icons are used whenever you receive an emoji with a skintone modifier which isn't supported on your device.

**Comment by caseyahenson** [comment]
@Naudiz Thanks for pointing that out. We'll be publishing v2.2.2 within a week or so that addresses the missing modifiers.

**Comment by caseyahenson** [comment]
v2.2.2 has been released which includes these modifiers.
