### ISSUE TITLE
Report: "Browse all 1834 emoji in 9 categories", instesd this is pnly 1619

### ISSUE THREAD

**Issue by laltroweb** [Ranks/emojione#261]
I've make folder like categories in my desktop, and - with downthemall - i've download svg from homepage: http://emojione.com/
but this report 1834, instead all files in homepage are only 1619 (and isn't a problem of downthemall: i've count every category "11x* and total count is exactly 1619").
my idea is to download from here with categories and convert to png with ImageMagick or Inkscape.
I've see categories is present in json, but i don't have found a valid way to use :/

thanks in advance,
S.N.

**Comment by caseyahenson** [comment]
@laltroweb We've pre-released artwork for Unicode9 in the v2.2.0 release. We'll be officially releasing data sets for UC9 artwork that will account for the missing data in emoji.json within the next couple of weeks. Hopefully this answers your question.
