### ISSUE TITLE
family emojis should have their ZWJ form as the default

### ISSUE THREAD

**Issue by salty-horse** [Ranks/emojione#268]
The group of "family" emojis in `emoji.json` has the canonical ZERO WIDTH JOINER form in the `unicode_alternates` field. The default `unicode` field just has a series of faces that I don't think any client renders as a single image.

For example, "family_wwgg" appears in the JSON as such:

``` json
"family_wwgg": {
    "unicode": "1F469-1F469-1F467-1F467",
    "unicode_alternates": [ "1F469-200D-1F469-200D-1F467-200D-1F467" ]
}
```

I propose the current "alternate" form should be the default, and the non-ZWJ form should be removed, as it is not very useful.

This is also relevant for the "kiss_" and "couple_" emojis.

**Comment by caseyahenson** [comment]
@salty-horse we've restructured the emoji.json file to make code points much more user-friendly. The 3.0 update fixes this concern.
