### ISSUE TITLE
Firefox extension?

### ISSUE THREAD

**Issue by ck-on** [Ranks/emojione#270]
Back in January 2016 a firefox extension was annouced.

The chrome extension shipped but no sign of firefox.

Is this delayed or never coming?

**Comment by caseyahenson** [comment]
We have plans to release a Firefox extension in the near future!

**Comment by mganss** [comment]
FWIW, I've made a [Thunderbird extension](https://addons.mozilla.org/thunderbird/addon/emojiaddin/). Code at https://github.com/mganss/EmojiAddIn.

**Comment by eosrei** [comment]
If you just want these to show in Firefox, you can use my font: https://github.com/eosrei/emojione-color-font

**Comment by caseyahenson** [comment]
@ck-on we just released our Firefox addon! You can install it here: https://addons.mozilla.org/en-US/firefox/addon/emoji-keyboard-by-emojione/. We'd love to hear your feedback once you have a chance to use it.
