### ISSUE TITLE
Unicode 9 is not included in lib/js/emojione.js

### ISSUE THREAD

**Issue by ping** [Ranks/emojione#271]
I could be mistaken but I don't think you have included the new emojis in the js lib. Parsing doesn't render any of the new emojis properly, e.g. :rofl:

Edit to add jsfiddle example: https://jsfiddle.net/axsgxyoq/

**Comment by caseyahenson** [comment]
Hi @ping, you're correct, the libraries didn't get updated properly in 2.2.3. I've tested the 2.2.4 release in your fiddle and the uc9 characters populate as expected. Let me know if you're still seeing issues.

**Comment by ping** [comment]
@caseyahenson The fix looks incomplete, the function .shortnameToImage() works but not .unicodeToImage()

Updated jsfiddle to include .unicodeToImage() https://jsfiddle.net/axsgxyoq/1/

**Comment by wilddeer** [comment]
I can confirm that `unicodeToImage` doesn’t work for me either, `ns.unicodeRegexp` is missing uc9 characters.

**Comment by caseyahenson** [comment]
Thanks for pointing that out! We'll be cleaning up a few more things such as this and publishing a release within the next few days.
