### ISSUE TITLE
Duplicate keywords in emoji.json

### ISSUE THREAD

**Issue by salty-horse** [Ranks/emojione#272]
662 of the "keywords" lists in emoji.json in the 2.2.2 release have duplicate entries.

Here are a few examples:
- mouse ["animal", "animal"]
- pouting_cat ["cat", "cat", "animal", "animal"]
- 100 ["symbol", "wow", "wow", "win", "win", "perfect", "perfect", "parties", "parties"]

**Comment by caseyahenson** [comment]
Hi @salty-horse, thanks for pointing that out! We'll be addressing this in a future release.

**Comment by caseyahenson** [comment]
The new emoji.json and emoji_strategy.json files reflect consolidated (non-duplicated) keywords. We'll be drafting a release with this update and others very soon.
