### ISSUE TITLE
unicode_alternates is no longer a list - rename to unicode_alternate?

### ISSUE THREAD

**Issue by salty-horse** [Ranks/emojione#273]
In emoji.json version 2.2.2, the unicode_alternates key is no longer a list, and now contains a single string.

Perhaps its name should be renamed to "unicode_alternate" as it only ever includes a single alternative character sequence.

This is also a breaking change - would be nice to have it documented somewhere.

**Comment by jonathanwiesel** [comment]
+1

**Comment by salty-horse** [comment]
The value used to be a list of strings (although every instance always had a a single string, or an empty list). Now it's a single string.

For example, for "family_wwg", the old value was:
```"unicode_alternates": [ "1F469-200D-1F469-200D-1F467" ]```

and the new value is:
```"unicode_alternates": "1f469-200d-1f469-200d-1f467"```

Since it's no longer a list, it can't contain more than one alternate value. I argue that the key's name should be changed, as the type change already breaks backward compatibility (which I don't think you worry about, and I'm not arguing for/against it).

This example shows another (AFAICT undocumented) change: The hex values are now lower-case (also in the "main" `unicode` key).

**Comment by caseyahenson** [comment]
I see what you mean. The unicode alternates have been in string format for around a year now. We'll definitely consider the impact of this and whether renaming or reverting to a list format is something that should happen.

To your observation on the lowercase unicode and hex values, certainly documentation of these changes is something we'll be improving upon as time goes on.

**Comment by caseyahenson** [comment]
To resolve this, "unicode_alternates" has been renamed to "unicode_alt". A new release will be drafted soon with release notes on this breaking change.
