### ISSUE TITLE
gay_pride_flag

### ISSUE THREAD

**Issue by freshlogic** [Ranks/emojione#274]
I'm certainly not trying to make a political statement, but the JSON files `emoji.json` and `emoji_strategy.json` contain an entry for `gay_pride_flag` with the Unicode 9.0 update but there doesn't appear to be an image for it and it doesn't appear to be part of the Unicode 9.0 set: http://www.unicode.org/emoji/charts/emoji-released.html

Should we add an image for it or remove the references?

**Comment by caseyahenson** [comment]
@freshlogic You're right that it's not a part of the Unicode set, however we will be releasing this emoji very soon. It will of course be of limited use as most libraries will render it as a flag + a rainbow, but it will be available for anybody using our Chrome Extension or updated libraries.
