### ISSUE TITLE
Hair color for generic skin tone

### ISSUE THREAD

**Issue by Randl** [Ranks/emojione#275]
Unicode [recommends](http://www.unicode.org/reports/tr51/#Diversity) dark hair for generic skin color, since dark hair tends to be more neutral, because people of every skin tone can have black (or very dark brown) hair. 

Current color of hair makes image feel flat, for it hard to distinguish between hair and skin itself, especially when the size of emoji is small e.g. smartphone screen. 

So I propose to replace color hair for generic skin color with brown or black, for example:
![Current](http://i.imgur.com/3H64zEv.png)![Proposed](http://i.imgur.com/m4GpQUo.png)

**Comment by caseyahenson** [comment]
@Randl thanks for the input! We do have plans to adjust the default hair and skin colors in an upcoming release which will nudge them in that direction.
