### ISSUE TITLE
emoji.json missing emoji

### ISSUE THREAD

**Issue by SoftCreatR** [Ranks/emojione#277]
While categorizing all images, i just noticed, that 46 images / emoji are not listed in emoji.json:

```
1f1e6
1f1e7
1f1e8
1f1e9
1f1ea
1f1eb
1f1ec
1f1ed
1f1ee
1f1ef
1f1f0
1f1f1
1f1f2
1f1f3
1f1f4
1f1f5
1f1f6
1f1f7
1f1f8
1f1f9
1f1fa
1f1fb
1f1fc
1f1fd
1f1fe
1f1ff
1f3fb
1f3fc
1f3fd
1f3fe
1f3ff
1f5e8
1f373
002a
0023
23cf
0030
0031
0032
0033
0034
0035
0036
0037
0038
0039
```

If they are no longer used, i would recommend to delete the corresponding image files. But i would prefer to have them included in the whole lib.

**Comment by caseyahenson** [comment]
There are a few of these (23cf, 1f5e8, and 1f373) that will be included in the upcoming bug-fix release. The others are regional indicators and numeric indicators, both of which exist in our assets primarily for the purpose of font building. However, I believe we'll be adding these to the libraries within the coming weeks.Thanks for catching this!
