### ISSUE TITLE
Missing graphic

### ISSUE THREAD

**Issue by SoftCreatR** [Ranks/emojione#278]
The graphic for 1f93b (Modern Pentathlon) is missing.

**Comment by SoftCreatR** [comment]
Okay, just saw the info, that it has been removed along with the rifle emoji.

However, it's still referenced in emoji.json

**Comment by caseyahenson** [comment]
This will be cleared up in the upcoming release.

**Comment by Crissov** [comment]
You’re free to keep them, though, or even add graphics for additional code points without a truish `Emoji` property.
