### ISSUE TITLE
Generate font name

### ISSUE THREAD

**Issue by raulriera** [Ranks/emojione#279]
Hi,

Is there a way to generate the ttf fonts with custom names? So that the they don't clash with the official ones and can be used separately?

Thanks

**Comment by miguelsousa** [comment]
There are many tools out there that enable you to modify the names.
Two that come to mind:
* [ttx](https://github.com/behdad/fonttools/tree/master/Tools) — command-line tool
* [DTL OTMaster](http://www.fontmaster.nl/english/OTMaster.html) — GUI tool

**Comment by raulriera** [comment]
I ended up using TTX after the ticket, but I was wondering if this "generation" should happen on the repo. But never mind, I am closing this! thanks :)
