### ISSUE TITLE
Using regular png emoji (not using sprite), the title attribute is missing

### ISSUE THREAD

**Issue by charford** [Ranks/emojione#280]
The png based emoji does not include a title attribute. There is an 'alt' attribute, but it's missing the title attribute. The title attribute is useful for when you don't know what an emoji means. You can hover your mouse over the emoji, and see a description. The alt attribute alone does not trigger the tooltip on mouse hover (I am using chrome).

**Comment by caseyahenson** [comment]
The title tag has been added to images via the new JS and PHP libraries, see the comment to your pull request. Thanks for your input!
