### ISSUE TITLE
"0" has no shortname defined, no image assets in path

### ISSUE THREAD

**Issue by derekmooney** [Ranks/emojione#282]
It appears that emoji.json has at least one entry that has no shortname, and no image asset in the path. Is there a preferential way to determine that this icon is not ready for use? My project parses the data and utilizes it for my own emoji processing, but I either need to explicitly skip this entry, or detect that it's not actually ready. Is an empty shortname the preferred way to skip it?

**Comment by jonathanwiesel** [comment]
According to emojipedia, it should be this one:
http://emojipedia.org/modern-pentathlon/
Also `"0"` seems like a bit vague key to me

**Comment by caseyahenson** [comment]
Thanks for catching this. We'll clean it up with the update to uc9 coming soon.
