### ISSUE TITLE
shortname :egg: was changed from u+1f373 to unicode9 u+1f95a?

### ISSUE THREAD

**Issue by kngchn** [Ranks/emojione#284]
Maybe "cooking" not suit shortname ":egg:", but it exists for 6 years.
Since shortname is not for human reading but a solution for saving emoji.
For backward compatibility, I think giving "egg" a new shortname and keeping the shortname to "cooking" is a better idea .

**Comment by caseyahenson** [comment]
Hi @kngchn thanks for pointing this out! There is some back on this and forth but it is officially named "cooking", whereas the introduction of "egg" in unicode 9 seems to have conflicted with some of our recent naming conventions of this. We'll be releasing an updated unicode 9 library soon with 1f373 short named ":cooking:".
