### ISSUE TITLE
Using file:// breaks the link to //cdn.jsdelivr.net

### ISSUE THREAD

**Issue by gabrielstuff** [Ranks/emojione#285]
Hello,

This is a really great set of emoji and a fantastic framework. Unfortunately, while using through Electron or simply from file:// protocole, the loading of images fail. 

See the css asking for `//` and tying to reach `file://cdn.jsdelivr.net`

https://github.com/Ranks/emojione/blob/c3fea224479cea82e87125f41a097d52a58d281b/assets/css/emojione-awesome.css#L43

Any idea on how to overcome this ? I do not see any method to specify the image path : 

`imagePathPNG` use here: https://github.com/Ranks/emojione/blob/master/lib/js/emojione.js#L150

Thanks a lot !

**Comment by caseyahenson** [comment]
Hi @gabrielstuff, when serving from jsdelivr you'll need to use the http: or https: protocol rather than the file: protocol, which is the indication of the file path prefixes, "//". It appears that Electron may have some caveats when handling unspecified protocols. Try following this thread here: https://github.com/electron/electron/issues/1747 and see if that can lead you in the right direction. 

Please keep us updated on your findings.

**Comment by gabrielstuff** [comment]
Well, any solution for loading local asset ? instead of delivr ?

**Comment by caseyahenson** [comment]
This documentation from Electron may be what you're looking for: https://github.com/electron/electron/blob/master/docs/api/protocol.md. 

If that doesn't work for you, you could try a couple of things. Either point lines 150 and 151 of emojione.js directly to http or to the location of the assets in your project, both of which should explicitly define a protocol and I believe that would satisfy the Electron framework. You'd need to perform the same action in the emojione-awesome.css file. 

If you could define the protocol globally it would certainly be the ideal solution to handle future EmojiOne asset updates.

**Comment by gabrielstuff** [comment]
wouldn't be cleaner to be able to choose at init to load remote asset and depends on delivr or local assets ?

Thanks @caseyahenson

**Comment by gabrielstuff** [comment]
Also, even if I certainly need to find a more general solution, why do you choose to keep the `//` instead of enforcing `https` ? Like said here: http://www.paulirish.com/2010/the-protocol-relative-url/ (anti-pattern)
