### ISSUE TITLE
Unicode 9 emoji categories

### ISSUE THREAD

**Issue by mganss** [Ranks/emojione#287]
In 2.2.5 the new Unicode 9 emoji have a wide range of new categories instead of the standard 8. What's the reasoning behind this?

**Comment by caseyahenson** [comment]
These will most likely be integrated into the same categorization as unicode 8 and below.

**Comment by jonathanwiesel** [comment]
+1

**Comment by connorshea** [comment]
Does 514552bbe5dc95814172abf0cfa07067b6b976ea solve this @caseyahenson, or is it only part of the problem?

**Comment by caseyahenson** [comment]
Yes that commit was intended to resolve this issue. There will still be a category for "regional" which is not a supported category, but intended to complete the dataset for regional indicator symbols.

**Comment by connorshea** [comment]
@caseyahenson I hadn't heard of the regional emoji before, and they're not in the Unicode 9 list on [EmojiOne.com](http://emojione.com/releases/2.2.4/), are they part of the Unicode spec?

**Comment by caseyahenson** [comment]
Flags are composed of regional indicator symbols, A-Z. Although they aren't individually listed in the Unicode emoji chart at http://unicode.org/emoji/charts/full-emoji-list.html, the symbols are included in our library as a fallback for situations where the flag emoji may not exist.
