### ISSUE TITLE
Adding a condition to include alt attribute in unicodeToImage method.

### ISSUE THREAD

**Issue by venugopp** [Ranks/emojione#288]
By using the function unicodeToImage(javascript) we are trying to remove the emoji character. But as it is again added in the alt attribute, we are not able to use the library. Please provide an option to include the alt attribute. so that on conditional basis it can be included in the img tag.

I am looking for an image tag similar to this without **alt** attribute.
`<img src="//cdn.jsdelivr.net/emojione/assets/png/270c.png?v=2.2.5" class="emojione">`

**Comment by pradeepvenugopal** [comment]
This is already implemented. Sorry I did not pay more attention to it.
