### ISSUE TITLE
Javascript library .toShort(str) converts non-emoji symbols to codes as of v2.2.5

### ISSUE THREAD

**Issue by suprMax** [Ranks/emojione#289]
Hello!

In previous versions it was pretty safe to use emojione alongside markdown, and use `.toShort` to convert text for editing, whilst keeping unicode in the DB (because why not)

With the current version however, you get somewhat unexpected results.

Input: `*123*`
Output:  `:asterisk_symbol::digit_one::digit_two::digit_three::asterisk_symbol:`

Although there are emojis for numbers and such, this behavior change is somewhat unexpected. I think it would be nice to have a `.toShort` method equivalent that converts only characters that are of actual emoji range

v2.2.4 works ok, so I assume the problem lies in latest addition of `00xx` chars

**Comment by caseyahenson** [comment]
Good point, those non-keycap characters were recently added to the dataset for the sake of completion but I can see how they're potentially problematic as demonstrated above. We'll definitely prioritize a solution for this.

**Comment by caseyahenson** [comment]
This should be resolved in the 2.2.6 release today.
