### ISSUE TITLE
Incorrect categories for a number of emoji

### ISSUE THREAD

**Issue by connorshea** [Ranks/emojione#293]
The following should be `objects`, but are listed as `people`:
- `athletic_shoe`
- `bikini`
- `boot`
- `briefcase`
- `dark_sunglasses`
- `dolls`
- `dress`
- `high_heel`
- `jeans`
- `closed_umbrella`
- `eyeglasses`
- `necktie`
- `mans_shoe`
- `kimono`
- `footprints`
- `handbag`
- `mortar_board`

**Comment by connorshea** [comment]
Okay, based on Apple's emoji categories some of these are actually correct. That was my bad. If we want parity with Apple's categories a few of these do need changes, though.

**Comment by caseyahenson** [comment]
@connorshea Thanks for doing the legwork in looking into this! We'll be improving categorization in the upcoming summer release for anything that needs adjusting.

**Comment by caseyahenson** [comment]
Categorization has been cleaned up in our most recent emoji.json and emoji_strategy.json files.
