### ISSUE TITLE
Nerd face is missing buck teeth

### ISSUE THREAD

**Issue by bmintz** [Ranks/emojione#298]
According to Emojipedia, [every emoji set except Emojione's has buck teeth on the nerd face emoji](http://emojipedia.org/nerd-face). I suggest adding it back in.

**Comment by maddrag0n** [comment]
Imho the current Emojione nerd face emoji is the most appealing one on that list. Plus it displays better in smaller sizes without added details like buck teeth.

**Comment by caseyahenson** [comment]
@bmitz thanks for the input! @maddrag0n we have made a significant effort to reduce some details of the emoji, in part for the purpose of rendering at a smaller size as you suggested.
