### ISSUE TITLE
Some emojis and categories no longer exist in emoji.json

### ISSUE THREAD

**Issue by jonathanwiesel** [Ranks/emojione#299]
I noticed that in the last release update the definitions on `emoji.json` for `objects_symbols` and `travel_places` categories have been removed, definitions such as:

```
[travel_places]
fire_engine_oncoming
jet_up
train_diesel
...

[objects_symbols]
calculator
cartridge
crossbones
...
```

Were they removed for a particular reason?

**Comment by caseyahenson** [comment]
@jonathanwiesel We've been moving toward a more terse categorization over the last year or so in an effort to keep categorization more consistent, compatible, and easily manageable.

**Comment by jonathanwiesel** [comment]
@caseyahenson I understand about the categorization. But how about the emoji in those categories? It seems they just been removed.

**Comment by caseyahenson** [comment]
I see what you're asking now. You'll see variations of some of those emoji (e.g. crossbones is now skull_crossbones (2620)), but I'm not completely sure why they were previously included in the emoji.json list. Those emoji don't appear in the approved Unicode list, but they may have been added in the file as likely candidates, or may have been added by mistake.

**Comment by jonathanwiesel** [comment]
Thank you for the clarification @caseyahenson
