### ISSUE TITLE
Mother Christmas glasses

### ISSUE THREAD

**Issue by miguelsousa** [Ranks/emojione#302]
The glasses of Mother Christmas (&#x1f936; U+1F936) have reflexions. Its skin tone variants do not.
The glasses of 👴 and 👵 don't have reflexions either.

**Comment by caseyahenson** [comment]
Thanks for pointing this out @miguelsousa! We'll include a corrected image in the next day or so.

**Comment by miguelsousa** [comment]
@caseyahenson 9c09b51fef41e630ab5ee81282ca49340f8f2daa does **not** include a new `1f936.svg` file.

**Comment by jonathanwiesel** [comment]
Bump what @miguelsousa commented
