### ISSUE TITLE
Why are your tigers so grumpy??

### ISSUE THREAD

**Issue by JonDum** [Ranks/emojione#303]
http://emojipedia.org/tiger-face/
http://emojipedia.org/tiger/

Most other sets don't add anything to the emotion of the tiger, but this has actually caused severe communication issues between my girlfriend and I.

She would be grumpy about something and send me a grumpy tiger 
![grumpy tiger](http://emojipedia-us.s3.amazonaws.com/cache/8d/46/8d46e24a9e909fc45e30b4e58c2f27d4.png)
but I would see it as a happy tiger 
![happy tiger](http://emojipedia-us.s3.amazonaws.com/cache/a7/db/a7db79b992a6cc2545c96e960ca11fd5.png) 
so I was oblivious to her apparent grumpiness.

Please fix, for my relationship's sake.

**Comment by caseyahenson** [comment]
@JonDum Our tiger is not angry, he's inquisitive. Or, at least in deep thought. Maybe you can persuade your girlfriend to try something like the 😡  face next time...😆
