### ISSUE TITLE
Numbers are white in blue circle in android

### ISSUE THREAD

**Issue by aat-antoine** [Ranks/emojione#305]
I made an android app and when I use emojione ttf file, if string contains number so it will be converted to white with a blue circle as background.

Here is the rendering (original text 0x1f642)
![numbers](https://cloud.githubusercontent.com/assets/1374372/16842221/e934bed8-49dc-11e6-8be3-7c01f0db5c6a.png)

Is there a way to get "normal" numbers ?

I think it is a problem with ttf file but I can't open it with http://bluejamesbond.github.io/CharacterMap/

**Comment by caseyahenson** [comment]
@aat-antoine Thanks for pointing this out, we've received several messages about this. @miguelsousa is there a good workaround for this? Other reports have listed the asterisk symbol as replacing with emoji as well.

**Comment by miguelsousa** [comment]
@caseyahenson I've submitted an updated that removes the keycaps sequences, which should fix this issue.

**Comment by caseyahenson** [comment]
@miguelsousa thank you for getting that submitted!
