### ISSUE TITLE
unicodeToImage SVG Sprites - Emoji background not fit correctly 

### ISSUE THREAD

**Issue by mansouralex** [Ranks/emojione#306]
![svg-emoji](https://cloud.githubusercontent.com/assets/6759585/16865260/08f747f6-4a6c-11e6-9628-ac1094376200.png)

Please notice the single Emoji background. How we can remove it?

Thanks.

**Comment by caseyahenson** [comment]
@mansouralex we haven't seen this happen before, can you add some more information about your implementation or anything else that could help us pinpoint what's causing this?

**Comment by freimaks** [comment]
This error occurs if you use [EmojiOne Area](https://github.com/mervick/emojionearea).

At least I have.

Example:
1. Without EmojiOne Area:
![1](https://cloud.githubusercontent.com/assets/26241659/25502344/f1433bc8-2b9e-11e7-89c9-0b56712a5055.png)

2. With EmojiOne Area (emoji have a background):
![image 46](https://cloud.githubusercontent.com/assets/26241659/25502404/1b5ebf72-2b9f-11e7-9346-e4e1dd01be5d.png)  ![image](https://cloud.githubusercontent.com/assets/26241659/25502467/50676386-2b9f-11e7-939f-8463c66fdbde.png)
