### ISSUE TITLE
Gaps in emoji order

### ISSUE THREAD

**Issue by jonathanwiesel** [Ranks/emojione#309]
I noticed that there's some gaps in the `emoji_order` sequence.

From 1624 (`tone5` modifier) skips up to 10000 (`prince_tone1`).
From 10074 (`cartwheel_tone5`) skips up to 10080 (`wrestlers_tone1`).
From 10174 (`pancakes`) skips up to 10177 (`regional_indicator_z`).

**Comment by caseyahenson** [comment]
These have been cleaned up in the most recent emoji.json and emoji_strategy.json updates and a new release will be drafted soon.
