### ISSUE TITLE
Literal characters in an HTML element property.

### ISSUE THREAD

**Issue by mqsoh** [Ranks/emojione#312]
The emoji recently started breaking on twitter. They're really large and the trailing part of the markup becomes visible.

With the extension disabled, this is their markup:

    <img class="Emoji Emoji--forText" src="https://abs.twimg.com/emoji/v2/72x72/1f62d.png" draggable="false" alt="😭" title="Loudly crying face" aria-label="Emoji: Loudly crying face">

The Chrome keyboard  is replacing the `alt` contents and you end up with this all over the page.

    " title="Loudly crying face" aria-label="Emoji: Loudly crying face">

[I posted a screenshot.](http://imgur.com/a/c5gfr)

**Comment by caseyahenson** [comment]
@mqsoh We'll have an update for this published within the next few hours that addresses this issue.

**Comment by mqsoh** [comment]
Cool. :smile: Thanks a lot.
