### ISSUE TITLE
iOS 10 beta 4 includes a whole new set of emojis

### ISSUE THREAD

**Issue by raulriera** [Ranks/emojione#315]
Will emojione support all the new emojis introduced by Apple today? (several female versions of male emojis)

http://9to5mac.com/2016/08/01/ios-10-will-include-over-100-new-emoji-new-diversity-options-and-popular-emoji-redesigns/

Thanks

**Comment by raulriera** [comment]
I could take a stab at some of them 😂 <img width="310" alt="screen shot 2016-08-04 at 11 54 41" src="https://cloud.githubusercontent.com/assets/24159/17399508/483ede14-5a3a-11e6-895c-fd72c41c7455.png">

**Comment by caseyahenson** [comment]
@raulriera We will definitely support the newly-approved emojis in our summer update. We'll be releasing a launch date for that as it approaches.

**Comment by raulriera** [comment]
What is the policy on submitting artwork? I saw an issue discussing that this is not allowed, I would really like to help out on the Summer update :)

<img width="562" alt="screen shot 2016-09-15 at 23 19 26" src="https://cloud.githubusercontent.com/assets/24159/18569501/e365287c-7b9a-11e6-80c2-61aa9d348087.png">

**Comment by caseyahenson** [comment]
@raulriera Thanks for your willingness to help, your artwork looks great! We've pushed back our summer release to essentially merge with our v3 release which is coming along nicely and includes an updated color palette and lots of new emoji. Currently our in-house design team creates all artwork, and to clarify the question about artwork submissions, we do encourage feedback on existing artwork which can include reference images (be it custom-made as the set you shared, screen shots of others' work, etc) but we don't accept artwork outside of our in-house set for use in our official set.

We've been posting v3 changes on our Twitter feed if you have any interest in keeping tabs on those: https://twitter.com/emojione

**Comment by raulriera** [comment]
Thanks for the info. Great work :)
