### ISSUE TITLE
jsdelivr 0 - cdnjs 1

### ISSUE THREAD

**Issue by mjau-mjau** [Ranks/emojione#318]
Happy to see that emojione is also hosted at cdnjs #35 . Unfortunately, image files are still loaded from jsdelivr.

jsdelivr does not provide proper cache headers:
https://cdn.jsdelivr.net/emojione/assets/png/1f1eb-1f1f7.png
![screen](https://d.pr/i/14Qft+)

cdnjs does:
https://cdnjs.cloudflare.com/ajax/libs/emojione/2.2.6/assets/png/1f1eb-1f1f7.png
![screen](https://d.pr/i/197ys+)

Lack of proper cache headers penalizes performance:
![screen](https://d.pr/i/1gNEq+)

Unless jsdelivr fixes this, cdnjs seems like a much better fit for emojione defaults. Additional problem of course, is that even the cdnjs-hosted js loads images by default from jsdelivr:

``` javascript
a.imagePathPNG = "//cdn.jsdelivr.net/emojione/assets/png/"
```

This can be remedied by setting a custom path in your own JS:

``` javascript
emojione.imagePathPNG = '//cdnjs.cloudflare.com/ajax/libs/emojione/2.2.6/assets/png/';
```

In addition, the routing of jsdelivr seems inconsistent. As seen in the request, it routes my request to China, while I am close to Singapore ...

**Comment by mjau-mjau** [comment]
Might as well also disable the `cacheBustParam` when using cdnjs, since assets are stored inside version-specific folders:
```javascript
emojione.cacheBustParam = '';
```
Won't really do much except improve performance scores.

**Comment by jimaek** [comment]
We are proxying the data instead of hosting assets for every single version like cdnjs does. The default settings of the proxy is to use the headers sent by Emojione's server, which didnt contain the caching headers.

I have now fixed this. You wont see the new caching headers until the CDNs purge their cache, this will take  a while.
