### ISSUE TITLE
U+FE0F-variants missing since emojione 2.2.4

### ISSUE THREAD

**Issue by richvdh** [Ranks/emojione#320]
In release 2.2.3, for emoji which are defined to have [variation sequences](http://www.unicode.org/emoji/charts/emoji-variants.html), `emojione.js` included mappings for both the base emoji, and the U+FE0F variant:

```
$ grep 'jsEscapeMap =' lib/js/emojione.js | sed -e 's/,/,\n/g' | grep '00A9'
"\u00A9\uFE0F":"00a9",
"\u00A9":"00a9",
```

However, since c8decbb, we just have duplicate entries of the base emoji:

```
$ grep 'jsEscapeMap =' lib/js/emojione.js | sed -e 's/,/,\n/g' | grep '00A9'
"\u00A9":"00a9",
"\u00A9":"00a9",
```

It would be great if the variants could be restored.

**Comment by caseyahenson** [comment]
@richvdh look for some updates to this, hopefully within the next week or so.

**Comment by caseyahenson** [comment]
These should be restored as of 2.2.7, let us know if you're seeing otherwise.
