### ISSUE TITLE
It does not replace smiles

### ISSUE THREAD

**Issue by tweaker** [Ranks/emojione#321]
It does not replace these smilies:
![2016-08-05 18-50-44 fav love -](https://cloud.githubusercontent.com/assets/3106164/17434563/21eee418-5b46-11e6-996d-6d4eb2b9b7b9.png)

How can I solve this problem?

**Comment by caseyahenson** [comment]
@tweaker Are you using an emojione library (js, php, other) or is it the Chrome extension that's not replacing properly?

**Comment by tweaker** [comment]
js library

**Comment by caseyahenson** [comment]
@tweaker I assume you're using the unicodeToImage function? Can you provide a few more relevant details like your platform, which version of the EmojiOne library you're using, etc?

**Comment by tweaker** [comment]
Exactly. Version 2.2.6 is used.
OS MacOS El Capitan. It is shown in all browsers.

```
$smilesList.find('a.emoji').each(function () {
    var $this = $(this);
    var $text = emojione.toImage($this.text());
    $this.html($text);
});
```

**Comment by caseyahenson** [comment]
Updating to the 2.2.7 release should resolve this.
