### ISSUE TITLE
Rename gay_pride_flag as pride_flag

### ISSUE THREAD

**Issue by BackIsBachus** [Ranks/emojione#323]
Hello,

As you may have figured out this is not a technical issue only a naming concern.

The new rainbow flag has been introduced in the new update and that's super cool, however I would suggest naming it `pride_flag` or `lgbt_pride_flag` instead of `gay_pride_flag` as it is the flag of all the LGBTQIA community and not just the G part.

I don't know if renaming is possible or if it would break some kind of backward compatibility so maybe adding an alias or setting `pride_flag` (or `lgbt_pride_flag`) as the main name and `gay_pride_flag` as an alias could be done.

I'd be happy to discuss this further is anyone wants to.

Thanks!

**Comment by romair** [comment]
Hey like the idea,
but why not simply `rainbow_flag` like in the unicode document, that describes it:
http://www.unicode.org/L2/L2016/16183-rainbow-flag.pdf

**Comment by BackIsBachus** [comment]
Agreed`rainbow_flag` would be more logical in term of specification by the Unicode Consortium.

In term of aliases (as I guess they don't have specifications) I would suggest, if possible, not to keep `gay_pride_flag` or at least to add other aliases (like those I suggested) for more inclusions.
This is indeed similar to #319 but I think it differs a bit because it includes a discussion about the possible aliases (and what message they can carry).

Although if you think it would be best to merge this discussion with #319 to deal with all the issues related with name and aliases of this emoji I'd be happy to.

**Comment by romair** [comment]
I'm :+1: on changing the name to `rainbow_flag` and adding something like the proposed `pride_flag` alias.

Slack uses `:pride:` as `rainbow_flag` shortname. So we're in good company if we decide to add an `pride` or `pride_flag` alias.

I agree it differs. This would be at most some kind of subissue. I think his issue concentrates more on the false listing. So no merge needed.

**Comment by caseyahenson** [comment]
We will be renaming this to the Unicode-suggested "rainbow flag" in an upcoming release, of course with plenty of keywords and possibly the gay/lgbtqia/pride aliases to keep it searchable.

**Comment by caseyahenson** [comment]
We've updated the emoji.json and emoji_strategy.json files to reflect the name change and will be pushing a full release soon to propagate the change throughout all libraries.
