### ISSUE TITLE
i18n: Text on Images

### ISSUE THREAD

**Issue by Crissov** [Ranks/emojione#327]
Several images show English text where it’s not necessary at all.
## 📧 U+1F4E7 Email Symbol

![&#x1F4E7;](https://rawgit.com/Ranks/emojione/2.2.7/assets/png/1f4e7.png) 

Unicode suggests to use an at-sign `@` instead of a letter `E`. Apple makes the same mistake.
## 📪 📫 U+1F4EA/B Mailbox Symbols

![&#x1F4EA;](https://rawgit.com/Ranks/emojione/2.2.7/assets/png/1f4ea.png) ![&#x1F4EB;](https://rawgit.com/Ranks/emojione/2.2.7/assets/png/1f4eb.png)

These show `MAIL` which is just unnecessary.
## 📅 📆 🗓 U+1F4C5/6/1F5D3 Calendar Symbols

![&#x1F4C5;](https://rawgit.com/Ranks/emojione/2.2.7/assets/png/1f4c5.png) ![&#x1F4C6;](https://rawgit.com/Ranks/emojione/2.2.7/assets/png/1f4c6.png) ![&#x1F4D3;](https://rawgit.com/Ranks/emojione/2.2.7/assets/png/1f5d3.png)

These show `JULY` in English and `JUL` (abbreviation in several languages). Apple only has `JUL`, but very small.
## 🎟🎫 U+1F39F/AB Tickets

![&#x1F39F; Admission Ticket](https://rawgit.com/Ranks/emojione/2.2.7/assets/png/1f39f.png) ![&#x1F3AB; Ticket](https://rawgit.com/Ranks/emojione/2.2.7/assets/png/1f3ab.png)

The former shows `ADMIT ONE` in English. The name on the latter is okayish.
## 🚍🚖🚚 U+1F68D/96/9A Vehicles

![&#x1F68D; Oncoming Bus](https://rawgit.com/Ranks/emojione/2.2.7/assets/png/1f68d.png) ![&#x1F696; Oncoming Taxis](https://rawgit.com/Ranks/emojione/2.2.7/assets/png/1f696.png) ![&#x1F69A; Delivery Truck](https://rawgit.com/Ranks/emojione/2.2.7/assets/png/1f69a.png)

The latter shows `DELIVERY` in English. `TAXI` and the self-promo `EMOJIONE` may be okay.
## 📟 U+1F4DF Pager

![&#x1F4DF;](https://rawgit.com/Ranks/emojione/2.2.7/assets/png/1f4df.png)

Okayish, shows `-O-N-E-`. Apple: `555-3215` (US fake number).
## 🗳 U+1F5F3 Ballot Box

![&#x1F5F3;](https://rawgit.com/Ranks/emojione/2.2.7/assets/png/1f5f3.png)

Shows `VOTE` in English.
## 📰 U+1F4F0 Newspaper

![&#x1F4F0;](https://rawgit.com/Ranks/emojione/2.2.7/assets/png/1f4f0.png)

Shows `NEWS` in English.
## 📛 U+1F4DB Name Tag

![&#x1F4DB;](https://rawgit.com/Ranks/emojione/2.2.7/assets/png/1f4db.png)

Shows `HELLO My name is …` in English, but its meaning is easier to recognize by Westerners than Apple’s Japanese design.
## 🏤🏨🏫🏬 U+1F3E4/8/B/C Buildings

![&#x1F3E4;](https://rawgit.com/Ranks/emojione/2.2.7/assets/png/1f3e4.png) ![&#x1F3E8;](https://rawgit.com/Ranks/emojione/2.2.7/assets/png/1f3e8.png) ![&#x1F3EB;](https://rawgit.com/Ranks/emojione/2.2.7/assets/png/1f3eb.png) ![&#x1F3EC;](https://rawgit.com/Ranks/emojione/2.2.7/assets/png/1f3ec.png)

These show `POST`, `HOTEL`, `SCHOOL` and  `SHOP` respectively. The `24` for the Convenience Store and `$` for the Bank seem okayish. _Post_ and _hotel_ or close cognates are used in many European languages.
## 🏧 U+1F3E7 Automated Teller Machine

![&#x1F3E7;](https://rawgit.com/Ranks/emojione/2.2.7/assets/png/1f3e7.png)

Shows `ATM` in English, but unlike Apple has at least a representation of an actual ATM.

Note, this emoji is sometimes used to mean _at the moment_ or _ass to mouth_ in English.
## 📢 U+1F4E3 Megaphone

![&#x1F4E3;](https://rawgit.com/Ranks/emojione/2.2.7/assets/png/1f4e3.png)

Shows `GO TEAM!` in English.
## 📴 U+1F4F4 Phone Off

![&#x1F4F4;](https://rawgit.com/Ranks/emojione/2.2.7/assets/png/1f4f4.png)

Shows `OFF` in English, although there are international standard symbols for _power off_.
## Mandatory Letters and Text

Some emojis canonically show Latin letters (🆔🆚🅰️🅱️🆎🆑🅾️🆘Ⓜ️🚾🅿️🆖🆗🆙🆒🆕🆓🔤🔡🔠🔚🔙🔛🔝🔜©️®️™️) or East-Asian syllabograms or logograms. These are not subject to further internationalization.

**Comment by caseyahenson** [comment]
@Crissov great points, we've already adopted some of your requests in our artwork for the summer release. Where it's reasonable, we'll be moving toward symbolism without text.

**Comment by Crissov** [comment]
### Version 3
![&#x1F4E7;](https://rawgit.com/Ranks/emojione-assets/master/png/64/1f4e7.png) 
![&#x1F4EA;](https://rawgit.com/Ranks/emojione-assets/master/png/64/1f4ea.png) ![&#x1F4EB;](https://rawgit.com/Ranks/emojione-assets/master/png/64/1f4eb.png)
![&#x1F4C5;](https://rawgit.com/Ranks/emojione-assets/master/png/64/1f4c5.png) ![&#x1F4C6;](https://rawgit.com/Ranks/emojione-assets/master/png/64/1f4c6.png) ![&#x1F4D3;](https://rawgit.com/Ranks/emojione-assets/master/png/64/1f5d3.png)
![&#x1F39F; Admission Ticket](https://rawgit.com/Ranks/emojione-assets/master/png/64/1f39f.png) ![&#x1F3AB; Ticket](https://rawgit.com/Ranks/emojione-assets/master/png/64/1f3ab.png)
![&#x1F68D; Oncoming Bus](https://rawgit.com/Ranks/emojione-assets/master/png/64/1f68d.png) ![&#x1F696; Oncoming Taxis](https://rawgit.com/Ranks/emojione-assets/master/png/64/1f696.png) ![&#x1F69A; Delivery Truck](https://rawgit.com/Ranks/emojione-assets/master/png/64/1f69a.png)
![&#x1F4DF;](https://rawgit.com/Ranks/emojione-assets/master/png/64/1f4df.png)
![&#x1F5F3;](https://rawgit.com/Ranks/emojione-assets/master/png/64/1f5f3.png)
![&#x1F4F0;](https://rawgit.com/Ranks/emojione-assets/master/png/64/1f4f0.png)
![&#x1F4DB;](https://rawgit.com/Ranks/emojione-assets/master/png/64/1f4db.png)
![&#x1F3E4;](https://rawgit.com/Ranks/emojione-assets/master/png/64/1f3e4.png) ![&#x1F3E8;](https://rawgit.com/Ranks/emojione-assets/master/png/64/1f3e8.png) ![&#x1F3EB;](https://rawgit.com/Ranks/emojione-assets/master/png/64/1f3eb.png) ![&#x1F3EC;](https://rawgit.com/Ranks/emojione-assets/master/png/64/1f3ec.png)
![&#x1F3E7;](https://rawgit.com/Ranks/emojione-assets/master/png/64/1f3e7.png)
![&#x1F4E3;](https://rawgit.com/Ranks/emojione-assets/master/png/64/1f4e3.png)
![&#x1F4F4;](https://rawgit.com/Ranks/emojione-assets/master/png/64/1f4f4.png)
