### ISSUE TITLE
[js] Add category in ns.emojioneList

### ISSUE THREAD

**Issue by tleunen** [Ranks/emojione#328]
Hi,

I'm using emojione and the package takes 16% of my project because I have to require both the JS file, and the emoji.json file.

The json file is required because it's the only file which contains the list of emoji with their category. If the category was also available in the list of `ns.emojioneList`. It would allow me to remove my dependency on the json file and reduce the size of emojione in my build.

Would it be possible to add the category info in `ns.emojioneList`?

Thanks.

**Comment by caseyahenson** [comment]
@tleunen I don't think that's an unreasonable request. We are working to make it more streamlined to map categories and I think your suggestion is right on par with our efforts.

**Comment by caseyahenson** [comment]
@tleunen ns.emojioneList does now contain a category attribute. Please note that the data is now keyed by filename (aka base code point).
