### ISSUE TITLE
‘Family’ 👪 U+1F46A should not show (just) a son

### ISSUE THREAD

**Issue by Crissov** [Ranks/emojione#331]
![👪 U+1F46A](https://rawgit.com/Ranks/emojione/2.2.7/assets/png/1f46a.png) ![:man:&zwj;:woman:&zwj;:boy: U+1F468-200D-1F469-200D-1F466](https://rawgit.com/Ranks/emojione/2.2.7/assets/png/1f468-1f469-1f466.png) ![:woman:&zwj;:man:&zwj;:boy: U+1F469-200D-1F468-200D-1F466](https://rawgit.com/Ranks/emojione/2.2.7/assets/png/1f469-1f468-1f466.png) ![:man:&zwj;:woman:&zwj;:girl: U+1F468-200D-1F469-200D-1F467](https://rawgit.com/Ranks/emojione/2.2.7/assets/png/1f468-1f469-1f467.png) ![:woman:&zwj;:man:&zwj;:girl: U+1F469-200D-1F468-200D-1F467](https://rawgit.com/Ranks/emojione/2.2.7/assets/png/1f469-1f468-1f467.png)

The child in `1f46a.svg` has the same hair style as the father and a bluish shirt, so it’ll be interpreted as a son, not a generic child, i.e. it would be the same as either of the non-existing `1f468-1f469-1f466.svg` or  `1f469-1f468-1f466.svg`.

Facebook, Emojidex and Google show two children (i.e. son and daughter), although Android Nougat seems to be adopting the single-kid paradigm, too. HTC currently has the most neutral 3-person family emoji.

I don’t care whether the solution is to have the composed glyph show a generic child or two children (or more).
- http://emojipedia.org/family/
- http://emojipedia.org/family-man-woman-boy/

Also, Windows 10 now supports single parents, infant children and Fitzpatrick modifiers – might be worth following suit and perhaps also add grandparents, pets (i.e. animal faces) and siblings without parents if this can be done in an efficient automated manner.

**Comment by caseyahenson** [comment]
@Crissov androgyny has been a challenge since people emojis have existed and a distinction between male and female (as well as non-gendered) is something we consistently work to achieve. As far as adding emoji outside of the approved Unicode emoji, I don't see us doing so but I think a lot will be changing as finding solutions for representing appropriate age, sex, and skin tone continue to be of importance.

**Comment by Crissov** [comment]
Additional ZWJ sequences for groups and families are so straightforward that they can’t really be considered “outside of the approved Unicode emoji”.

**Comment by Crissov** [comment]
### Version 3
![:family: U+1F46A](https://rawgit.com/Ranks/emojione-assets/master/png/64/1f46a.png) ![:man:&zwj;:woman:&zwj;:boy: U+1F468-200D-1F469-200D-1F466](https://rawgit.com/Ranks/emojione-assets/master/png/64/1f468-1f469-1f466.png) ![:woman:&zwj;:man:&zwj;:boy: U+1F469-200D-1F468-200D-1F466](https://rawgit.com/Ranks/emojione-assets/master/png/64/1f469-1f468-1f466.png) ![:man:&zwj;:woman:&zwj;:girl: U+1F468-200D-1F469-200D-1F467](https://rawgit.com/Ranks/emojione-assets/master/png/64/1f468-1f469-1f467.png) ![:woman:&zwj;:man:&zwj;:girl: U+1F469-200D-1F468-200D-1F467](https://rawgit.com/Ranks/emojione-assets/master/png/64/1f469-1f468-1f467.png) ![:man:&zwj;:woman:&zwj;:child: U+1F468-200D-1F469-200D-1F9D2](https://rawgit.com/Ranks/emojione-assets/master/png/64/1f468-1f469-1f9d2.png) ![:woman:&zwj;:man:&zwj;:child: U+1F469-200D-1F468-200D-1F9D2](https://rawgit.com/Ranks/emojione-assets/master/png/64/1f469-1f468-1f9d2.png)
