### ISSUE TITLE
The heart is not converted when using <3

### ISSUE THREAD

**Issue by Huseriato** [Ranks/emojione#332]
I've found this by random. I turned `emojion.ascii` to `true`. I convert all smilies to unicode before storing to database: `_emoji.shortnameToUnicode(value)` - after that it's converted to image: `_emoji.unicodeToImage(value)`

Using `:heart:` will work as expected, but <3 will not (shows default icon and is not catched by the `unicodeToImage` function). May be there is another unicode used for <3 than for `:heart:` ?

**Comment by Crissov** [comment]
Possibly related to #321, #320 and #310 if the issue is U+2764 vs. U+2764-FE0F (VS-16).

* [JSFiddle](https://jsfiddle.net/545jt38n/8/)

**Comment by briska** [comment]
@caseyahenson maybe you're just missing the key in jsEscapeMap? emojione.jsEscapeMap['❤️'] returns undefined

**Comment by caseyahenson** [comment]
This issue should be resolved in the 2.2.7 release.

**Comment by mroftalp** [comment]
@caseyahenson have the same problem in version 3.0.3
