### ISSUE TITLE
Add animated emojis.

### ISSUE THREAD

**Issue by whimsicaldreamer** [Ranks/emojione#334]
It would be nice if there were some animated gif's too in the package. It would spice up things too.

**Comment by hotgeart** [comment]
No. It's emojis not an "emoticon pack".

**Comment by whimsicaldreamer** [comment]
Definitely I know that. But I was asking it would be good if there were options of selecting a gif set which would be animated. Something like we see on skype.

**Comment by whimsicaldreamer** [comment]
On skype we can send animated emojis plus native emojis too. So I was thinking if something like that could be done with these sets.

**Comment by caseyahenson** [comment]
@whimsicaldreamer thus far we've been [almost 😉 ] completely compliant with Unicode standards for our publicly available emoji set. Vendors are of course free to add to their sets but we do love our Unicode standards!

**Comment by whimsicaldreamer** [comment]
I love them too...☺

**Comment by caseyahenson** [comment]
@whimsicaldreamer If you use Android, you might check out an app called Mood Messenger that contains around 70 animated EmojiOne emojis.
