### ISSUE TITLE
Browser performance for svg

### ISSUE THREAD

**Issue by mervick** [Ranks/emojione#338]
When `imageType` is `svg` then `object` tag used and it loads svg files everytime without browser caching.
I don't see any reason to use `object` except the using fallback image (which currently doesn't).

So maybe it better to use `img` tag instead of `object`?

**Comment by caseyahenson** [comment]
@mervick thanks for the suggestion! We'll be making some updates in an upcoming release, I'll evaluate this and I'll let you know the results, hopefully we can squeeze it in.

**Comment by caseyahenson** [comment]
@mervick this issue is no longer relevant with the release of 3.0.
