### ISSUE TITLE
Remove facial expression from animals

### ISSUE THREAD

**Issue by hotgeart** [Ranks/emojione#339]
The emojis must be neutral. For example : http://emojipedia.org/bear-face/

Why the bear look mad ?

Same for tiger, gorilla, camel, ...

**Comment by Crissov** [comment]
Animal heads for easy reference (U+1F42D–F, 1F430–2/4–C, 1F981/4/5/A):

![U+1F42D 🐭](https://raw.githubusercontent.com/Ranks/emojione/master/assets/png/1f42d.png) ![U+1F42E 🐮](https://raw.githubusercontent.com/Ranks/emojione/master/assets/png/1f42e.png) ![U+1F42F 🐯](https://raw.githubusercontent.com/Ranks/emojione/master/assets/png/1f42f.png) ![U+1F430 🐰](https://raw.githubusercontent.com/Ranks/emojione/master/assets/png/1f430.png) ![U+1F431 🐱](https://raw.githubusercontent.com/Ranks/emojione/master/assets/png/1f431.png) ![U+1F432 🐲](https://raw.githubusercontent.com/Ranks/emojione/master/assets/png/1f432.png) ![U+1F434 🐴](https://raw.githubusercontent.com/Ranks/emojione/master/assets/png/1f434.png) ![U+1F435 🐵](https://raw.githubusercontent.com/Ranks/emojione/master/assets/png/1f435.png) ![U+1F436 🐶](https://raw.githubusercontent.com/Ranks/emojione/master/assets/png/1f436.png) ![U+1F437 🐷](https://raw.githubusercontent.com/Ranks/emojione/master/assets/png/1f437.png) ![U+1F438 🐸](https://raw.githubusercontent.com/Ranks/emojione/master/assets/png/1f438.png) ![U+1F439 🐹](https://raw.githubusercontent.com/Ranks/emojione/master/assets/png/1f439.png) ![U+1F43A 🐺](https://raw.githubusercontent.com/Ranks/emojione/master/assets/png/1f43a.png) ![U+1F43B 🐻](https://raw.githubusercontent.com/Ranks/emojione/master/assets/png/1f43b.png) ![U+1F43C 🐼](https://raw.githubusercontent.com/Ranks/emojione/master/assets/png/1f43c.png) ![U+1F981 🦁](https://raw.githubusercontent.com/Ranks/emojione/master/assets/png/1f981.png) ![U+1F984 🦄](https://raw.githubusercontent.com/Ranks/emojione/master/assets/png/1f984.png) ![U+1F985 🦅](https://raw.githubusercontent.com/Ranks/emojione/master/assets/png/1f985.png) ![U+1F98A 🦊](https://raw.githubusercontent.com/Ranks/emojione/master/assets/png/1f98a.png)

These should have bodies (U+1F417/2A, 1F98C/D/F):

![U+1F417 🐗](https://raw.githubusercontent.com/Ranks/emojione/master/assets/png/1f417.png) ![U+1F42A 🐪](https://raw.githubusercontent.com/Ranks/emojione/master/assets/png/1f42a.png) ![U+1F98C 🦌](https://raw.githubusercontent.com/Ranks/emojione/master/assets/png/1f98c.png) ![U+1F98D 🦍](https://raw.githubusercontent.com/Ranks/emojione/master/assets/png/1f98d.png) ![U+1F98F 🦏](https://raw.githubusercontent.com/Ranks/emojione/master/assets/png/1f98f.png)

**Comment by caseyahenson** [comment]
@hotgeart @Crissov thanks for the info and suggestions. We'll be moving in a much more universally accepted direction in coming updates.

**Comment by Crissov** [comment]
### Version 3
![U+1F42D 🐭](https://rawgit.com/Ranks/emojione-assets/master/png/64/1f42d.png) ![U+1F42E 🐮](https://rawgit.com/Ranks/emojione-assets/master/png/64/1f42e.png) ![U+1F42F 🐯](https://rawgit.com/Ranks/emojione-assets/master/png/64/1f42f.png) ![U+1F430 🐰](https://rawgit.com/Ranks/emojione-assets/master/png/64/1f430.png) ![U+1F431 🐱](https://rawgit.com/Ranks/emojione-assets/master/png/64/1f431.png) ![U+1F432 🐲](https://rawgit.com/Ranks/emojione-assets/master/png/64/1f432.png) ![U+1F434 🐴](https://rawgit.com/Ranks/emojione-assets/master/png/64/1f434.png) ![U+1F435 🐵](https://rawgit.com/Ranks/emojione-assets/master/png/64/1f435.png) ![U+1F436 🐶](https://rawgit.com/Ranks/emojione-assets/master/png/64/1f436.png) ![U+1F437 🐷](https://rawgit.com/Ranks/emojione-assets/master/png/64/1f437.png) ![U+1F438 🐸](https://rawgit.com/Ranks/emojione-assets/master/png/64/1f438.png) ![U+1F439 🐹](https://rawgit.com/Ranks/emojione-assets/master/png/64/1f439.png) ![U+1F43A 🐺](https://rawgit.com/Ranks/emojione-assets/master/png/64/1f43a.png) ![U+1F43B 🐻](https://rawgit.com/Ranks/emojione-assets/master/png/64/1f43b.png) ![U+1F43C 🐼](https://rawgit.com/Ranks/emojione-assets/master/png/64/1f43c.png) ![U+1F981 🦁](https://rawgit.com/Ranks/emojione-assets/master/png/64/1f981.png) ![U+1F984 🦄](https://rawgit.com/Ranks/emojione-assets/master/png/64/1f984.png) ![U+1F985 🦅](https://rawgit.com/Ranks/emojione-assets/master/png/64/1f985.png) ![U+1F98A 🦊](https://rawgit.com/Ranks/emojione-assets/master/png/64/1f98a.png)
![U+1F417 🐗](https://rawgit.com/Ranks/emojione-assets/master/png/64/1f417.png) ![U+1F42A 🐪](https://rawgit.com/Ranks/emojione-assets/master/png/64/1f42a.png) ![U+1F98C 🦌](https://rawgit.com/Ranks/emojione-assets/master/png/64/1f98c.png) ![U+1F98D 🦍](https://rawgit.com/Ranks/emojione-assets/master/png/64/1f98d.png) ![U+1F98F 🦏](https://rawgit.com/Ranks/emojione-assets/master/png/64/1f98f.png)

**Comment by aphextwins** [comment]
why is the monkey happy? HUH??? IT MUST BE NEUTRAL!!!! REEEEEEEEEEEEE
ALSO THE GOD DAMN FROG!!!!!! its pepe the frog, and its a symbol of hate speech. REMOVE IT OR YOU EMPOWER WHITE SUPREMACISTS
