### ISSUE TITLE
space removed for ascii emoticons

### ISSUE THREAD

**Issue by dgrad** [Ranks/emojione#34]
One space in front of ascii emoticons is removed when converting to image.

e.g. something like "I <3 you" will be replaced by "I:heart: you" instead of "I :heart: you"

**Comment by dgrad** [comment]
any update on this issue?

**Comment by kevinranks** [comment]
I apologize for the delay. We had it fixed but were waiting for some new emoji art before we did another release. We'll get things squared away ASAP and get it released. You can view a forked demo using the latest emojione.js and see that the issue is resolved here: http://jsfiddle.net/2n00vtmw/

**Comment by dgrad** [comment]
thank you! just wanted to know if it's on the list. I'll be waiting for the next release.
