### ISSUE TITLE
Update emojiStrategy

### ISSUE THREAD

**Issue by mroftalp** [Ranks/emojione#340]
Can update the emoji strategy? Cause searching egg it returns the cooking image -> 🍳

**Comment by caseyahenson** [comment]
@mroftalp there is a keyword "egg" in the :cooking: record which is intentional, are you seeing the cooking emoji returned for shortname :egg: as well?

**Comment by mroftalp** [comment]
Yes even here in github it should be :cooking: right
![screen shot 2016-08-25 at 5 24 13 am](https://cloud.githubusercontent.com/assets/6789191/17948629/2d3f6ae8-6a84-11e6-9840-8a29a5d05c1b.png)

**Comment by caseyahenson** [comment]
As of now our :egg: (1f95a) is the single egg and :cooking: (1f373) is a skillet with an egg as shown in the first result of your example, both in emoji.json and emoji_strategy.json. Shortname auto replace is still showing artwork for 1f373 in GitHub so that will need to be updated on their end.
