### ISSUE TITLE
//cdn.jsdelivr.net doesn't work with file: protocol

### ISSUE THREAD

**Issue by laitedliang** [Ranks/emojione#347]
Hi,

I am developing an Android project using [IonicFramework](http://ionicframework.com/), which uses `file:` protocol, and it produces the following error when loading the images

> GET file://cdn.jsdelivr.net/emojione/assets/png/1f391.png?v=2.2.6 net::ERR_FILE_NOT_FOUND

I am well aware of the issue #285, but the solution does not apply for IonicFramework. 
Is it possible to check the protocol first and if the current protocol is not http: or https: then use https:?

````javascript
// emojione.js line 150
var protocol = window.location.protocol === 'http:' || window.location.protocol === 'https:' ? window.location.protocol : 'https:';
ns.imagePathPNG = protocol + '//cdn.jsdelivr.net/emojione/assets/png/';
ns.imagePathSVG = protocol + '//cdn.jsdelivr.net/emojione/assets/svg/';
```

Thanks!

**Comment by Daniel15** [comment]
Rather than checking `window.location.protocol`, it's safe to always use `https`.
