### ISSUE TITLE
Clarify how to modify and redistribute

### ISSUE THREAD

**Issue by bignose-debian** [Ranks/emojione#350]
The Contributing document says, in part:

> We unfortunately cannot accept submissions for emoji art revisions. Due to the copyright of the art and the potential for it's licensing in different situations this isn't possible.

No further explanation is given.

What does that imply about the recipient's freedom to make modification and redistribute? What exactly is the reader to understand is not possible “due to the copyright of the art”?

Please explain in the document and resolve the apparent conflict between the copyright license (CC By-SA explicitly permits any recipient to redistribute derived works), and the statement above that “the copyright of the art” prevents revisions.

**Comment by caseyahenson** [comment]
@bignose-debian The indication here is only that we cannot distribute the specific artwork of others (as it's the only way to ensure that the artwork we distribute is not otherwise protected), not to say that others cannot modify and distribute the artwork which we provide under the CC license.

Does this help to clarify? I'll update the document once I'm sure that we've resolved the confusion.

**Comment by bignose-debian** [comment]
> we cannot distribute the specific artwork of others (as it's the only way to ensure that the artwork we distribute is not otherwise protected)

Could you accept contributions if they are accompanied by a Certificate of Origin? http://developercertificate.org/

If a contribution's copyright status is known, and license is granted to all recipients under the same conditions as Emoji One, that seems to be exactly what you would need. Yes?

So perhaps adding an initial section to the Contributing document:

```
### Certificate and License

We need to know what freedom we have in your contribution. Please include,
in the file or the commit message, the following text:

    This work was created in whole or part by me, <your name here>.
    This is free culture: I hereby grant to all recipients of this
    work the freedom to perform, modify, and/or redistribute this work
    under the terms of the <license name here> license.

Replace “<your name here>” with your legal name, so that we can know
the copyright origin of the contribution.

Replace “<license name here>” with either “Creative Commons
Attribution 4.0 International” or “MIT”, as described in `LICENSE.md`.
```

**Comment by caseyahenson** [comment]
@bignose-debian We're always happy to accept input on our artwork, and accompanying input with example images can certainly help to explain the suggestion. At this time, though, we don't have plans to redistribute artwork submitted by others.

**Comment by bignose-debian** [comment]
On 22-Nov-2016, Casey A Henson wrote:
> We're always happy to accept input on our artwork, and accompanying
> input with example images can certainly help to explain the
> suggestion. At this time, though, we don't have plans to
> redistribute artwork submitted by others.

Thanks for that statement.

The existing text in the Contributing document, then, says something
quite at odds with that; it's what raised this issue in the first
place :-)

I think we're agreed (?) that the existing text quoted in the initial
report is not accurate, and appears to say something quite different
from what you say above.

To resolve this issue I'd ask that the text be replaced with something
much more like the statement you give above.

-- 
 \     “Anyone can do any amount of work provided it isn't the work he |
  `\          is supposed to be doing at the moment.” —Robert Benchley |
_o__)                                                                  |
Ben Finney <ben@benfinney.id.au>

**Comment by caseyahenson** [comment]
@bignose-debian we've attempted to clarify our position on artwork submissions with the release of 3.0.

**Comment by bignose-debian** [comment]
> we've attempted to clarify our position on artwork submissions with the release of 3.0.

The Contributing document does not appear to have changed. What should I be looking at?
