### ISSUE TITLE
Inkscape not displaying correctly

### ISSUE THREAD

**Issue by thielj** [Ranks/emojione#353]
Hi. I noticed that some emojis (e.g. the lonely island and the beach) are not displaying correctly in Inkscape - some paths seem to be missing. I didn't investigate any further and am not blaming anyone here - just thought I would let you know!

Inkscape 0.91 r13725

![1f3d6](https://cloud.githubusercontent.com/assets/3942997/18294310/325f69cc-7490-11e6-848e-1ec022080fc9.png)
![1f3dd](https://cloud.githubusercontent.com/assets/3942997/18294311/32618518-7490-11e6-973e-c8a053b83708.png)

**Comment by thielj** [comment]
Addition: They display correctly when using the emojione-master download from github. I did a quick diff and there are various differences.

**Comment by caseyahenson** [comment]
@thielj Please take a look at this thread: https://github.com/Ranks/emojione/issues/313. We use an SVG cleaner on our assets before loading them into the repo, and certain versions of Inkscape have had issues with the rendering of these when converting from the vector format.
