### ISSUE TITLE
Missing ZWJ sequence: Family: MAN, WOMAN, BOY

### ISSUE THREAD

**Issue by JoshyPHP** [Ranks/emojione#354]
Emoji One supports almost all of [Unicode's Emoji ZWJ sequences v3.0](http://www.unicode.org/Public/emoji/3.0/emoji-zwj-sequences.txt), except for one: `1F468 200D 1F469 200D 1F466`. The image already exists for U+1F46A but it would be nice to support the canonical sequence for completeness.

Relevant excerpt, with an additional sequence for illustration:

```
1F468 200D 1F469 200D 1F466                 ; Emoji_ZWJ_Sequence  # 6.0  [1] (👨‍👩‍👦)     Family: MAN, WOMAN, BOY
1F468 200D 1F469 200D 1F466 200D 1F466      ; Emoji_ZWJ_Sequence  # 6.0  [1] (👨‍👩‍👦‍👦)    Family: MAN, WOMAN, BOY, BOY
```

Tangentially related to https://github.com/Ranks/emojione/issues/331

**Comment by afmenez** [comment]
This seems to be working now, can't this issue be closed?
