### ISSUE TITLE
:poop: emoji style issue

### ISSUE THREAD

**Issue by brainscript** [Ranks/emojione#356]
![Poop emojiOne](http://cdn.jsdelivr.net/emojione/assets/png/1f4a9.png?v=2.2.6)
The `:poop:` emoji's color variation of the "poop layers" :smile: is way too bright/white at the top. That makes it look too shiny in my opinion (almost like the Apple emojis) and it just doesn't fit into the emojiOne style:
![emojis-screenshot](https://cloud.githubusercontent.com/assets/8706734/18416666/e0fc7b68-781a-11e6-9cbe-0a32ce9d08e4.JPG)
And although I hate the Apple emojis, their `:hankey:` emoji looks way better in my opinion ...
![Poop Apple emoji](https://assets-cdn.github.com/images/icons/emoji/unicode/1f4a9.png)
... because the colors are darker and there's less contrast between them.

**Comment by caseyahenson** [comment]
@brainscript thanks for your suggestion! We're making some updates to the pile of poo emoji in our upcoming summer release that I think you'll enjoy 😄
