### ISSUE TITLE
Make DROMEDARY CAMEL's hump visible instead of a face

### ISSUE THREAD

**Issue by salty-horse** [Ranks/emojione#357]
Somewhat related to #339, but this is specific to camels.

[All vendors except EmojiOne](http://emojipedia.org/dromedary-camel/) display U+1F42A DROMEDARY CAMEL as a camel seen from the side, such that its lovely camel hump is visible, and helps distinguish it from U+1F42B BACTRIAN CAMEL.

EmojiOne displays it as a face. It is impossible to tell if it's a dromedary or bactrian camel.
Please conform to Unicode's description, and to all other vendors.

**Comment by mike-fabian** [comment]
Yes, I also saw this and didn’t like that one cannot tell from the face whether it is a bactrian camel.

**Comment by caseyahenson** [comment]
@salty-horse @mike-fabian thanks for the suggestions! We have plans to update the dromedary camel to a full-body side view in our upcoming summer release.
