### ISSUE TITLE
Support for new emojis defined in Unicode emoji 4.0

### ISSUE THREAD

**Issue by emilhauk** [Ranks/emojione#358]
Do you have a roadmap for supporting the new emojis that comes with http://www.unicode.org/Public/emoji/4.0 ?

Examples of new emojis are:
1F486 200D 2642 FE0F                       ; keyboard  # 💆‍♂️ Man getting face massage
1F486 200D 2640 FE0F                       ; keyboard  # 💆‍♀️ Woman getting face massage
1F487 200D 2642 FE0F                       ; keyboard  # 💇‍♂️ Man getting haircut
1F487 200D 2640 FE0F                       ; keyboard  # 💇‍♀️ Woman getting haircut

The mentioned emojis and more are going to be shipped with iOS 10.

Thanks for your efforts!

**Comment by caseyahenson** [comment]
@emilhauk we'll certainly be supporting these. Look for the release at some point this fall.

**Comment by caseyahenson** [comment]
The release of 3.0 includes full support for Emoji 4.0.
