### ISSUE TITLE
🍬 U+1F36C Candy looks like a Svastika

### ISSUE THREAD

**Issue by Crissov** [Ranks/emojione#359]
![🍬 U+1F36C Candy](https://rawgit.com/Ranks/emojione/2.2.7/assets/png/1f36c.png)

With small font sizes on light backgrounds, the Candy emoji 🍬 U+1F36C unintentionally resembles a red Svastika.

**Comment by Tymewalk** [comment]
I suggest to fix this, 3 red spokes are used instead of 4.

**Comment by caseyahenson** [comment]
We've been through a few iterations of this using variations in the stripe in recent weeks. I'll keep you informed of how it evolves.

**Comment by Crissov** [comment]
![🍬 U+1F36C Candy](https://rawgit.com/Ranks/emojione-assets/master/png/64/1f36c.png)

Fixed in version 3.0.
