### ISSUE TITLE
Safety Improvements to 🚴 Cyclist and 🚲 Bike

### ISSUE THREAD

**Issue by Crissov** [Ranks/emojione#362]
![🚴 U+1F6B4 Bicyclist](https://rawgit.com/Ranks/emojione/2.2.7/assets/png/1f6b4.png) ![🚲 U+1F6B2 Bicycle](https://rawgit.com/Ranks/emojione/2.2.7/assets/png/1f6b2.png) ![🚵 U+1F6B5 Mountain Biker](https://rawgit.com/Ranks/emojione/2.2.7/assets/png/1f6b5.png) ![🚳 U+1F6B3 No Bikes](https://rawgit.com/Ranks/emojione/2.2.7/assets/png/1f6b3.png)

The mountain biker is wearing a helmet, the normal bicyclist is not. The street bikes also don’t show front and rear lights which are required in many jurisdictions to participate in general traffic.

**Comment by caseyahenson** [comment]
@Crissov Thanks for the input! I passed these along and we'll try to work them in to our next update.

**Comment by Crissov** [comment]
On further thought, the normal bicyclist does not require lights, because 🚴🚵🏇 are Activity (_-ing, -er_, i.e. hobby, sports) emojis and 🚲🐎 are the respective Transport emojis. For motorcycles, 🏍 is ambiguous, because its name suggests Activity, but it’s usually sorted with Transport vehicle emojis.

![🏍 U+1F3CD Racing Motorcycle](https://raw.githubusercontent.com/Ranks/emojione/master/assets/png/1f3cd.png)

**Comment by spacehobo** [comment]
The helmet is not required for riding on the road except in Australia and a few other places where cycling has been pushed away from general transport.  The lights would be a welcome addition on both 🚲 and 🚴 if there is room for them.

It would perhaps be best to put the normal cyclist in a more upright posture to match the kind of bicycle depicted in 🚲.  Also it would be nice if it were depicted using a female figure unless there are supported ZWJ tricks for that codepoint.

I would request that you kindly not put a helmet on 🚴, as it gives the impression of danger for an activity that is quite safe.  If there comes a codepoint specifically for racing cycling, then perhaps some specialist sport gear would make sense for that.  Until then I hope you continue to show cycling as the everyday activity it is.

**Comment by Crissov** [comment]
## Version 3.0
![🚴 U+1F6B4 Bicyclist](https://rawgit.com/Ranks/emojione-assets/master/png/64/1f6b4.png) ![🚲 U+1F6B2 Bicycle](https://rawgit.com/Ranks/emojione-assets/master/png/64/1f6b2.png) ![🚵 U+1F6B5 Mountain Biker](https://rawgit.com/Ranks/emojione-assets/master/png/64/1f6b5.png) ![🚳 U+1F6B3 No Bikes](https://rawgit.com/Ranks/emojione-assets/master/png/64/1f6b3.png)
![🏍 U+1F3CD Racing Motorcycle](https://rawgit.com/Ranks/emojione-assets/master/png/64/1f3cd.png) ![🏇 U+1F3C7 Horse Racing](https://rawgit.com/Ranks/emojione-assets/master/png/64/1f3c7.png) ![🐎 U+1F40E Horse](https://rawgit.com/Ranks/emojione-assets/master/png/64/1f40e.png)

The cyclist is now wearing a helmet, but also sports-wear, for both kinds of bike. The bike has become simpler and less safe; still without lights. The only real difference between a bike and a mountain bike in Emojione 3.0 is the mountain in the background. :disappointed:

**Comment by spacehobo** [comment]
This is highly disappointing.  Please return the cyclist to everyday clothes.

**Comment by aphextwins** [comment]
I love how everything needs to be politically correct now a days. Negroids with ginger hair. doesn't even exist wtf
