### ISSUE TITLE
Inconsistent circle shortnames

### ISSUE THREAD

**Issue by GIider** [Ranks/emojione#366]
So there's :white_circle:, :black_circle:, :red_circle: and then :large_blue_circle:

Why does only blue have the prefix "large"? Is there any rhyme or reason behind it?

**Comment by caseyahenson** [comment]
@GIider thanks for pointing this out. We'll be pushing an update out this month that will clean up the naming convention of the circles.

**Comment by caseyahenson** [comment]
These have been updated in the most recent commit to the emoji.json and emoji_strategy.json files and a release will be drafted soon containing these updates.
