### ISSUE TITLE
Remove Christian imagery from U+26B0 COFFIN

### ISSUE THREAD

**Issue by salty-horse** [Ranks/emojione#367]
The picture for U+26B0 COFFIN includes a Christian cross.

Coffins burial is practiced in non-Christian cultures, and by seculars. There's no reason to have a cross over the coffin.

Besides EmojiOne, only LG and emojidex's versions currently feature a cross (or any religious insignia for that matter).
http://emojipedia.org/coffin/

**Comment by caseyahenson** [comment]
Hi @salty-horse, we'll have a big update coming out this fall that will address this concern. Thanks for your input!
