### ISSUE TITLE
Wrong filenames for black and white assets (svg and png)

### ISSUE THREAD

**Issue by klaas** [Ranks/emojione#372]
e.g. the emoji "`PERSON PLAYING WATER POLO`" is found in `svg_bw/1f93e.svg`, but should be in `svg_bw/1f93d.svg`.

It seems to be a work in progress. Would a full list be helpful?

**Comment by caseyahenson** [comment]
@klaas if you provided diffs for those that would definitely be helpful!

**Comment by klaas** [comment]
A quick image diff shows, that these have wrong images:

U+1F93A - PERSON FENCING
U+1F93C - PEOPLE WRESTLING
U+1F93D - PERSON PLAYING WATER POLO
U+1F93E - PERSON PLAYING HANDBALL
U+1F43F - CHIPMUNK (slightly shifted up!)

The images in these files are missing at their correct position: e.g. "1f93A.png" should be "1f941.png".

**Comment by caseyahenson** [comment]
Thanks for your input and doing the legwork on this, the files have been renamed.
