### ISSUE TITLE
shortnameToUnicode and toShort gone wrong

### ISSUE THREAD

**Issue by adebayu39** [Ranks/emojione#375]
i was try to encode my shortname to unicode use shortnameToUnicode function and save it to database, and i check in my database it show escaped unicode,
and then when i try to decode it, my data was decoded to native unicode in the end.
in different case, i try to encode my unicode escaped to shortname use toShort function, but it gone wrong in database, so how about my first case? that have rellations in my first and second case.
any advice?

**Comment by caseyahenson** [comment]
@adebayu39 I definitely understand what you're saying here, but it would be very helpful if you could include a specific example or two of what you're seeing so that we can recreate it and test some solutions to help you overcome the issue.

**Comment by adebayu39** [comment]
for example i've try to encode my shortname emoji use shortnameToUnicode() and it saved correctly to my database to unicode (\u****), but when i try to decode it use toShort() i found theres come to character or symbolic but i need my shortname emoji comes back to my php apps. any way to solve it?
for my second question i'll send my example after it solved, i think if this case solved my second question will follow it. are my words confusing you? cause have a little bit problem with my English. Thanks.

**Comment by caseyahenson** [comment]
@adebayu39 can you revisit this issue with 3.0 and compare your results? I think you may be experiencing an issue related to your environment's ability to properly store utf8-mb4 data. If you're seeing the same thing I can give you some troubleshooting tips.
