### ISSUE TITLE
How to know which emoji belong to which category and the sequence of emojis

### ISSUE THREAD

**Issue by iamsaksham** [Ranks/emojione#377]
I want to integrate EmojiOne in my React.js app. I'll create category tabs and will render emoji images in their respective tabs and in their correct order.
So how to know order and category of the emoji? i.e how to know the correct place of an emoji

**Comment by caseyahenson** [comment]
@iamsaksham the emoji.json file in the project's root directory contains category data as well as emoji_order data, which can be used to order the emojis within their respective categories.
