### ISSUE TITLE
Gender are not supported

### ISSUE THREAD

**Issue by Jeanmilost** [Ranks/emojione#378]
Hello,

On several devices like e.g. iPhone (with iOS 10), some emojis exist in both male and female versions, e.g. the U+1f481 symbol. In this case, the emoji is built as follow:
[d83d dc81 d83c dffd 200d 2640 fe0f]
where:
[d83d dc81] = the emoji symbol U+1f481
[d83c dffd] = the Fitzpatrick tone
[200d] = joiner char
[2640] = female symbol (or modifier)
[fe0f] = should be drawn as emoji
So, to support the gender, some additional symbols are required, e.g. for the U+1f481:
1f481-2640 = INFORMATION DESK PERSON, default, female version
1f481-2642 = INFORMATION DESK PERSON, default, male version
... (for all Fitzpatrick tone values)
1f481-1f3fd-2640 = INFORMATION DESK PERSON, light brown tone, female version
1f481-1f3fd-2642 = INFORMATION DESK PERSON, light brown tone, male version

Can you add these symbols?

Regards

**Comment by caseyahenson** [comment]
@Jeanmilost we'll have a major update this fall which will include complete support for gendered roles, all of which will be coded with gender-specific code points.

**Comment by Jop-V** [comment]
Will there be neutral versions as well?
