### ISSUE TITLE
Monoparental families are not supported

### ISSUE THREAD

**Issue by Jeanmilost** [Ranks/emojione#379]
Hello,

All the monoparental families, as e.g. one father or mother and one/two boys or girls, are missing. Can you add them please?

For info, monoparental families are built as follow:
[d83d dc69 200d d83d dc66]
where:
[d83d dc69] = a single mother symbol (or may be a single father too)
[200d] = joiner char
[d83d dc66] = a single boy symbol (or may be a single girl too)
[optional] another single boy or girl preceded by a joiner char
=> So in this case the final symbol should be named: 1f469-1f468, and should contain a mother with his son

Regards

**Comment by caseyahenson** [comment]
@Jeanmilost eventually you'll see a lot more support from vendors, including EmojiOne, for zero width joiner emoji sequences which are not yet included in the "approved" Unicode list @ http://unicode.org/emoji/charts/full-emoji-list.html. Families are one example of how additional ZWJ support could be used to create any combination of parent/child. I don't see EmojiOne supporting ZWJ sequence at that level within the next few months, but that could certainly change.

**Comment by Jeanmilost** [comment]
Hi Caseyahenson,

Thank you for your reply.

However, I saw that a large set of families already exist in the library, as e.g. the "1f468-1f469-1f467-1f466.svg", that shows a mother/father/girl/boy family. For that reason, why not also supporting single parental families?

Regards

**Comment by Crissov** [comment]
If it may be supported in the future (to be compatible with other implementations), why are you already closing the issue, @caseyahenson?
