### ISSUE TITLE
toImageSrc

### ISSUE THREAD

**Issue by Wikunia** [Ranks/emojione#384]
I would like to get only the `src` attribute and not the whole image tag. 
Is that possible?

**Comment by caseyahenson** [comment]
@Wikunia there's currently no direct method to retrieve this data, however there are a few workarounds that you could try. For example, in your project you could retrieve the path to a singular image using a map like this:

``emojione.imagePathPNG + emojione.emojioneList[':taco:'].unicode[emojione.emojioneList[':taco:'].unicode.length-1] + '.png'``

You can then employ any of the toShortname methods (for singular inputs) to convert, say, a unicode character to shortname, and plug that shortname into the string above. With enough demand we could always consider including a function or set of functions to achieve something similar.

**Comment by Druux** [comment]
@caseyahenson are there any further plans to achieve this?
