### ISSUE TITLE
Re-add Keycaps to Android font

### ISSUE THREAD

**Issue by Naudiz** [Ranks/emojione#388]
The following items need to be re-added to Android TTF:
u0023
u002A
u0030
u0031
u0032
u0033
u0034
u0035
u0036
u0037
u0038
u0039
u0023_20E3
u002A_20E3
u0030_20E3
u0031_20E3
u0032_20E3
u0033_20E3
u0034_20E3
u0035_20E3
u0036_20E3
u0037_20E3
u0038_20E3
u0039_20E3

I have explained in #385 how app-developers need to make sure they have a non-emoji font in their app to be adressed before Emoji TTF for numbers from 0-9, #-sign or asterisk. It's the same way how Android handles it on a system level.

**Comment by miguelsousa** [comment]
@caseyahenson I've submitted a PR that fixes this.

**Comment by caseyahenson** [comment]
@miguelsousa and @Naudiz nice work! The new font is merged, thanks for all the work.
