### ISSUE TITLE
unicodeToImage not converting some characters

### ISSUE THREAD

**Issue by dpogue** [Ranks/emojione#392]
Specifically, this seems to be characters that can use the `\uFE0F` & `\uFE0E` variants.

I'm testing this on http://git.emojione.com/demos/latest/jsunicodetoimage.html

My test string is 
```
⚪️⚫️🔴🔵⭕️🔘💢⛽️🚀
```

My output is
<img width="223" alt="screen shot 2016-11-17 at 11 26 22" src="https://cloud.githubusercontent.com/assets/241708/20404198/bd0c4e40-acb8-11e6-8f2c-0ce774747f27.png">

**Comment by caseyahenson** [comment]
This issue should be resolved in the 2.2.7 release. Let us know if you're still seeing issues!
