### ISSUE TITLE
Add mouse on-hover pop-up showing the original text that was made into an emoji

### ISSUE THREAD

**Issue by hachre** [Ranks/emojione#396]
When I have it translate ":)" into an Emoji via `emojione.toImage(":)");` it would be cool to have a feature that enables a pop up when hovering with the mouse over the resulting Emoji image. The pop up would read ":)". This can be done by adding an alt attribute to an img tag for example.

Equally, if for example "laughing" was emojified via `emojione.toImage(":laughing:");`, the pop up should display "laughing" in the alt description. (I've removed the : signs because Github translates them in this message, but they are supposed to wrap the "laughing" string of course.)

Thanks for the consideration.

**Comment by caseyahenson** [comment]
@hachre we added this functionality in 2.2.7 via the title attribute in img tags. You'll just need to be sure that imageTitleTag variable is 'true', the imageType variable is set to 'png', and of course that the sprites variable is set to 'false'. The title is either the shortname, or in the case of ASCII replacement, the ASCII string. Try it out and let us know what you think!
