### ISSUE TITLE
HTML js integration doesn't work.. 

### ISSUE THREAD

**Issue by jaubut** [Ranks/emojione#397]
Hi, I've try to had the html "plugin" with the css class... but nothing was working.. even on the demo the render wasnt showing the emoji but the short name.. On the demo page Ive drop down to version 2.1.0 and it work but not on my site.. please help me..

**Comment by caseyahenson** [comment]
@jaubut it turns out there were some bad reference paths in the demo script for this: http://git.emojione.com/demos/latest/class-convert.html which have been repaired and will be merged into the repo soon. 

On your site, are you seeing any errors come through, or simply no replacements being made?
