### ISSUE TITLE
Consider adding diversity flag

### ISSUE THREAD

**Issue by flide** [Ranks/emojione#408]
In the emoji.json, it would be really helpful if emoji's are somehow indicated to have diversity alternatives.

Since there already exists the "modifier" category of emoji's that just need to be appended to the emoji's that support diversity, adding a diversity flag to supporting emoji's will also help in reducing the size of the "emoji.json"

**Comment by flide** [comment]
Since there already exists the "modifier" category of emoji's that just need to be appended to the emoji's that support diversity, adding a flag will also help in reducing the size of the "emoji.json"

**Comment by caseyahenson** [comment]
@flide the emoji.json file for 3.0 now contains a 'diversity' attribute, where 'null' indicates that the emoji is not diverse, and diverse emoji contain the primary key of their diversity code point (Fitzpatrick Modifier). 

The data also contains a 'diversities' attribute which is an empty array for diversity emoji as well as emoji without diversity alternatives available, and is an array of diversity code points for non-diverse emoji having diversity alternatives available.
