### ISSUE TITLE
Update the flag of Switzerland, or Vatican City, or both.

### ISSUE THREAD

**Issue by Zegnat** [Ranks/emojione#41]
There are 2 square (1:1) national flags currently in use, Switzerland’s and Vatican City’s. Emoji One forces all flags into a 16:11 ratio but doesn’t do this consistently. Switzerland’s flag is put on an off-white background while Vatican City’s is modified to fill the full space:

![Emoji One FLAG OF SWITZERLAND icon](https://raw.githubusercontent.com/Ranks/emojione/a30dedc06ec39a6757b5f31ec6a8737e64545356/assets/png/1F1E8-1F1ED.png) vs ![Emoji One FLAG OF VATICAN CITY icon](https://raw.githubusercontent.com/Ranks/emojione/a30dedc06ec39a6757b5f31ec6a8737e64545356/assets/png/1F1FB-1F1E6.png)

For consistency either the Swiss flag needs to be changed to fill the complete space or the Vatican flag needs to be a square on an off-white background.

Alternatively Emoji One should support proper square (and other, in [the case of Nepal](https://en.wikipedia.org/wiki/Flag_of_Nepal) especially) flags. It is problematic to overlay flags on an off-white background the way it is now done for Switzerland and Nepal because the user is unable to tell if the flag should be this way (white rectangle with 2 triangles on the hoist side?) or not (the white expresses transparency?).

**Comment by mikebe11** [comment]
Thanks for the suggestion. We reviewed it and have decided to modify the Swiss flag to fill the whole space. It will represent the more "informal" version that is often used. It will be included in a release in the near future.
