### ISSUE TITLE
Category icons do not match with declared categories

### ISSUE THREAD

**Issue by rubengees** [Ranks/emojione#412]
I am currently writing a script which uses information from the `emoji.json`.
Sadly the categories of the emoji declared there do not match with the available icons in the `assets/other/category_icons` folder. (There is no "regional" icon while there is such a category; The icon is called "foods" while the category is called "food")
Am I missing someplace where matching icons are located or anything else?

**Comment by caseyahenson** [comment]
@rubengees The misnamed icon has been fixed. The icons that we provide are meant to be for our public categories as shown in the new categories.json file in the repo's main directory. Hopefully this helps to clarify!
