### ISSUE TITLE
"diversity" keyword missing in Emoji.json

### ISSUE THREAD

**Issue by flide** [Ranks/emojione#414]
The following emojis are missing "diversity" in their keyword list even though diversity types are available for them : 

mother christmas
man in tuxedo
pregnant woman
face palm
shrug
man dancing
selfie
hand with first and index finger crossed
call me hand
left-facing fist
right-facing fist
raised back of hand
handshake
prince
juggling
horse_racing
handball
water_polo
wrestlers
cartwheel

**Comment by caseyahenson** [comment]
This is resolved using the diversity and diversities attributes in the emoji.json file as explained in issue #408. Keywords should not be used to identify diversity code points.
