### ISSUE TITLE
What about :memo:?

### ISSUE THREAD

**Issue by math2001** [Ranks/emojione#439]
Hi!

Why isn't 📝 (`:memo:`) supported? Is it intentional, or just forgotten?

Thanks anyway all those beautiful emojis! 🥇 

Matt

**Comment by caseyahenson** [comment]
Matt, looks like that shortname may need to be updated. Thanks for pointing that out!

**Comment by caseyahenson** [comment]
@math2001 You'll now find `:memo:` supported as an alternate shortname for 📝. In the future we may consider setting that as the primary shortname. Thanks again.
