### ISSUE TITLE
The emoji “🤼” (U+1F93C) and “🤝” (U+1F91D) should not have skin tone modifiers

### ISSUE THREAD

**Issue by mike-fabian** [Ranks/emojione#443]
The emoji “🤼” (U+1F93C) and “🤝” (U+1F91D) have skin tone
modifiers in emoji.json, i.e. emoji.json contains stuff like:

"wrestlers_tone1":{"unicode":"1f93c-1f3fb","unicode_alt":"","code_decimal":"&#129340;&#127995;","name":"wrestlers tone 1","shortname":":wrestlers_tone1:","category":"activity","emoji_order":"947","aliases":[":wrestling_tone1:"],"aliases_ascii":[],"keywords":[]}

and

"handshake_tone1":{"unicode":"1f91d-1f3fb","unicode_alt":"","code_decimal":"&#129309;&#127995;","name":"handshake tone 1","shortname":":handshake_tone1:","category":"people","emoji_order":"1255","aliases":[":shaking_hands_tone1:"],"aliases_ascii":[],"keywords":[]}

But they do not have the “Emoji_Modifier_Base” property in emoji-data.txt from unicode.org:

http://www.unicode.org/Public/emoji/4.0/emoji-data.txt

Not in the draft 5.0 version either:

http://www.unicode.org/Public/emoji/5.0/emoji-data.txt

I guess these  do not have skin  tone modifiers because two people are involved in each
of these emoji. And they could have different skin tones.

So I think the data in emoji.json is wrong, these emoji  should not have skin tone modifiers.

**Comment by Crissov** [comment]
Yes, they were Emoji Modifier Bases in a previous draft of Emoji 4.0, but got removed because there was no way to specify skin tones for both human characters individually.

**Comment by caseyahenson** [comment]
These no longer carry the emoji modifier base property and diversity has been removed as of the 3.0 release.
