### ISSUE TITLE
Some emoji which have skin tones in emoji-data.txt from unicode.org lack skin tones in emojione

### ISSUE THREAD

**Issue by mike-fabian** [Ranks/emojione#444]
(The reverse bug of https://github.com/Ranks/emojione/issues/443)

Bugs in emoji.json compared to Emoji 4.0 *and* Emoji 5.0:

http://www.unicode.org/Public/emoji/4.0/emoji-data.txt
http://www.unicode.org/Public/emoji/5.0/emoji-data.txt

emoji “🏂” (U+1F3C2) has the property Emoji_Modifier_Base in emoji-data.txt but no skin tones in emojione.
emoji “🏌” (U+1F3CC) has the property Emoji_Modifier_Base in emoji-data.txt but no skin tones in emojione.
emoji “🕴” (U+1F574) has the property Emoji_Modifier_Base in emoji-data.txt but no skin tones in emojione.
emoji “🛌” (U+1F6CC) has the property Emoji_Modifier_Base in emoji-data.txt but no skin tones in emojione.

Bugs in emoji.json only when compared to Emoji 5.0 (stuff which is new in Emoji 5.0):
http://www.unicode.org/Public/emoji/5.0/emoji-data.txt

emoji “🤟” (U+1F91F) has the property Emoji_Modifier_Base in emoji-data.txt but no skin tones in emojione.
emoji “🤱” (U+1F931) has the property Emoji_Modifier_Base in emoji-data.txt but no skin tones in emojione.
emoji “🤲” (U+1F932) has the property Emoji_Modifier_Base in emoji-data.txt but no skin tones in emojione.
emoji “🧑” (U+1F9D1) has the property Emoji_Modifier_Base in emoji-data.txt but no skin tones in emojione.
emoji “🧒” (U+1F9D2) has the property Emoji_Modifier_Base in emoji-data.txt but no skin tones in emojione.
emoji “🧓” (U+1F9D3) has the property Emoji_Modifier_Base in emoji-data.txt but no skin tones in emojione.
emoji “🧔” (U+1F9D4) has the property Emoji_Modifier_Base in emoji-data.txt but no skin tones in emojione.
emoji “🧕” (U+1F9D5) has the property Emoji_Modifier_Base in emoji-data.txt but no skin tones in emojione.
emoji “🧖” (U+1F9D6) has the property Emoji_Modifier_Base in emoji-data.txt but no skin tones in emojione.
emoji “🧗” (U+1F9D7) has the property Emoji_Modifier_Base in emoji-data.txt but no skin tones in emojione.
emoji “🧘” (U+1F9D8) has the property Emoji_Modifier_Base in emoji-data.txt but no skin tones in emojione.
emoji “🧙” (U+1F9D9) has the property Emoji_Modifier_Base in emoji-data.txt but no skin tones in emojione.
emoji “🧚” (U+1F9DA) has the property Emoji_Modifier_Base in emoji-data.txt but no skin tones in emojione.
emoji “🧛” (U+1F9DB) has the property Emoji_Modifier_Base in emoji-data.txt but no skin tones in emojione.
emoji “🧜” (U+1F9DC) has the property Emoji_Modifier_Base in emoji-data.txt but no skin tones in emojione.
emoji “🧝” (U+1F9DD) has the property Emoji_Modifier_Base in emoji-data.txt but no skin tones in emojione.

**Comment by caseyahenson** [comment]
Hi @mike-fabian the 3.0 release brings this project up to Emoji 4.0 compatibility, but we won't be releasing an Emoji 5.0 compatible data set until later this year. I'm going to close this since it's a bit preemptive, however, I added the Emoji 5.0 label so we can reference this when the time comes.
