### ISSUE TITLE
npm package is 90MB download

### ISSUE THREAD

**Issue by dtinth** [Ranks/emojione#448]
We noticed that our `yarn install` is becoming very slow (takes 20 minutes to run). Upon further investigation, it appears that the EmojiOne tarball on `npm` (https://registry.yarnpkg.com/emojione/-/emojione-2.2.7.tgz) is very large, 90MB. (This is an increase from `v2.2.6` which is 54MB.)

This is because the `npm` package also contains all the assets (unpacked 128M), as well as libraries for other languages (which is probably unused when downloaded from npm).

Since the JavaScript library already refers to the assets in the CDN, downloading a 90MB tarball to use a 355KB JavaScript file seems like an overkill. Therefore, my suggestion is to only include the JavaScript file in the npm distribution. If the assets are desired, maybe they can be published separately as another npm package.

**Comment by Crissov** [comment]
Also see #446 for the suggestion to split the repository, not just the package.

**Comment by caseyahenson** [comment]
@dtinth based on feedback like yours and that of @Crissov, we've now split the repository and the npm package into libraries (emojione) and assets (emojione-assets). Hopefully this helps to alleviate the problems you were finding.

**Comment by iwonapiasecka** [comment]
iwcia263811@gmail.com
