### ISSUE TITLE
Keycap numbers 0-7 are broken

### ISSUE THREAD

**Issue by FlorianDr** [Ranks/emojione#449]
I use ``toImage`` with the following short names:

:keycap_digit_zero:
:keycap_digit_one:
:keycap_digit_two:
:keycap_digit_three:
:keycap_digit_four:
:keycap_digit_five:
:keycap_digit_six:
:keycap_digit_seven:

Not a single one is replaced.

Any browser
v2.2.7

**Comment by caseyahenson** [comment]
@FlorianDr you'll want to reference the keycap emoji using simple the name of the digit, e.g. `:one:` rather than `:keycap_digit_one:`. Digits can be referenced using the digit prefix like `:digit_one:`, for example.

**Comment by FlorianDr** [comment]
@caseyahenson thanks for your message. I have some inconsistency here, since seven, eight and so are replaced.
