### ISSUE TITLE
Consider implementing "modern" (led/cfl) light bulbs as U+1F4A1's ZWJ variants

### ISSUE THREAD

**Issue by Artoria2e5** [Ranks/emojione#454]
[Most implementations of](http://emojipedia.org/electric-light-bulb/) the ELECTRIC LIGHT BULB (U+1F4A1), including emojione, involve an illustration of a conventional incandescent light bulb. This is getting increasing out of touch from reality as governments worldwide has been [phasing out incandescent light bulbs](https://en.wikipedia.org/wiki/Phase-out_of_incandescent_light_bulbs). Halogen light bulbs will also be dead in the United States by 2020 and in the EU by 2018. It may be a good idea for Twemoji to offer ZWJ sequences for more current types of household light bulbs, namely [CFL](https://en.wikipedia.org/wiki/Compact_fluorescent_lamp) and [LED](LED_lamp). 

CFL light bulbs has been seen in place of tungsten bulbs for showing that someone got a good idea, especially an energy-saving one. (See "[Good for the environment idea](http://www.chrismadden.co.uk/cartoons/environment-cartoons/fuel-source-cartoons/page/energy-efficient-lightbulb-idea-cartoon.html)", "[Bright Ideas: Then and Now](https://www.cartoonstock.com/cartoonview.asp?catref=mtun609)", "[Eco Ideas](https://www.cartoonstock.com/cartoonview.asp?catref=wda0045)", and "[How cartoons are helping the environment](https://www.cartoonstock.com/cartoonview.asp?catref=bstn431)".) Mac OS X's "Energy Saver" preference icon has also changed as lighting paradigms advance. ([This tweet](https://twitter.com/sstephenson/status/522134879316627456) summarizes it well.)

For-fun mockups are available at https://commons.wikimedia.org/wiki/File:Emojione_1F4A1_CFL.svg and
https://commons.wikimedia.org/wiki/File:Emojione_1F4A1_LED.svg. LEDs are really just making the buttom half of the bulb a white plastic ballast. Helix CFLs appear difficult to get right, so I grabbed a CC-BY tube from wikimedia commons and fused it with a modified LED ballast.

![CFL](https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/Emojione_1F4A1_CFL.svg/64px-Emojione_1F4A1_CFL.svg.png)![LED](https://upload.wikimedia.org/wikipedia/commons/4/49/Emojione_1F4A1_LED.svg)

Cross-posted from twitter/twemoji#207.

**Comment by caseyahenson** [comment]
@Artoria2e5 it sounds like you have a good starting point for a Unicode proposal on the matter. We'll certainly take your points into consideration for future artwork releases.

**Comment by Artoria2e5** [comment]
Since CFL/LED are merely variants for the light bulb character, I doubt if it would meet the selection rules. It may be considered "overly specific", for example.
