### ISSUE TITLE
The rainbow flag should be a zwj sequence

### ISSUE THREAD

**Issue by mike-fabian** [Ranks/emojione#455]
https://github.com/Ranks/emojione/blob/master/emoji.json
contains:

"rainbow_flag":{"unicode":"1f3f3-1f308","unicode_alt":"","code_decimal":"&#127987;&#127752;","name":"rainbow_flag","shortname":":rainbow_flag:","category":"objects","emoji_order":"2186","aliases":[":gay_pride_flag:"],"aliases_ascii":[],"keywords":[]},

unicode_alt is empty here.

But it should contain:

"unicode_alt":"1f3f3-200d-1f308"

Because the rainbow flag is a zwj sequence, just like eye_in_speech_bubble, which has:

"eye_in_speech_bubble":{"unicode":"1f441-1f5e8","unicode_alt":"1f441-200d-1f5e8","code_decimal":"&#128065;&#128488;","name":"eye in speech bubble","shortname":":eye_in_speech_bubble:","category":"symbols","emoji_order":"1281","aliases":[],"aliases_ascii":[],"keywords":["object","symbol","eyes","talk"]}

See: http://unicode.org/Public/emoji/5.0/emoji-zwj-sequences.txt

which contains near the end:

# Emoji ZWJ Sequence: Other

1F3F3 FE0F 200D 1F308                       ; Emoji_ZWJ_Sequence  ; rainbow flag                                                   # 7.0  [1] (🏳️‍🌈)
1F441 FE0F 200D 1F5E8 FE0F                  ; Emoji_ZWJ_Sequence  ; eye in speech bubble                                           # 7.0  [1] (👁️‍🗨️)

**Comment by caseyahenson** [comment]
@mike-fabian Thanks for pointing this out. It'll be corrected in our upcoming 3.0 release.

**Comment by caseyahenson** [comment]
@mike-fabian this issue is resolved in our most recent update, thanks again.
