### ISSUE TITLE
Not all Number Cap emojis are recognized

### ISSUE THREAD

**Issue by Waboodoo** [Ranks/emojione#459]
It seems that not all of the following emojis are recognized by the emojiOne JS library:
#⃣0⃣1⃣2⃣3⃣4⃣5⃣6⃣7⃣8⃣9⃣🔟

The numbers 8, 9 and 10 as well as the hash symbol work, but the numbers 0 - 7 are missing.

See screenshot:
![screenshot from 2017-04-03 10-27-34](https://cloud.githubusercontent.com/assets/2445563/24601201/47b08d6c-1858-11e7-92b7-b6b4ed86f788.png)

This relates to https://github.com/Ranks/emojione/issues/449.

**Comment by codefuhrer** [comment]
+1

![2017-04-18 06-52-06](https://cloud.githubusercontent.com/assets/2178368/25113927/95916978-2403-11e7-8325-bd0919364d5e.png)

**Comment by caseyahenson** [comment]
This issue is resolved with the release of 3.0.
