### ISSUE TITLE
[Violation] 'setInterval' handler took XXXms

### ISSUE THREAD

**Issue by Yobmod** [Ranks/emojione#467]
i started getting the above warning in the console a few times per second.
On chrome.  It didn't do it before today (10/04/17)

**Comment by caseyahenson** [comment]
@Yobmod can you provide some more details on what script you're running when you see this?

**Comment by Yobmod** [comment]
Hi,
The script causing the warning is:
chrome-extension://jbdenakghoccpkjaboikhbinhmopiiio/js/script-js/myScript_5.js

which is from the Green Messenger chrome extension (for WhatsAppWeb).
I didn't think it relied on emojieone to show emojis? 

It doesn't seem to affect performance to have both extensions running, but it drowns out any other console messages.

**Comment by caseyahenson** [comment]
Unless I'm missing something, this appears to be related solely to the Green Messenger extension. Are you seeing the message when the EmojiOne extension is disabled?
