### ISSUE TITLE
Cannot download PNG images from Emojione's website

### ISSUE THREAD

**Issue by reebr** [Ranks/emojione#474]
I'm trying to download some images from Emojione's site, but it I'm getting a 404 error.

**Steps to reproduce:**
* Go to http://emojione.com/
* Select any emoji on "Emoji Gallery".
* On "Download this Emoji", select ".PNG".
* 404, page not found.

Could you guys fix the links? Thank u.

– _cheers_

**Comment by caseyahenson** [comment]
@reebr we just pushed an update to the emojione.com site today. Please review that process and be sure it's working correctly for you.
