### ISSUE TITLE
In the 3.0 release, the regional indicator symbols have the wrong category ("people") in emoji.json

### ISSUE THREAD

**Issue by mike-fabian** [Ranks/emojione#476]
In the recent release https://github.com/Ranks/emojione/releases/tag/v3.0.0

the emoji.json file has the category “people” for the regional
indicator symbols, for example:

"1f1ff":{"name":"regional indicator symbol letter z","category":"people" ...

This seems quite weird, before this release the category
for these regional indicator symbols was “regional” which seems
more appropriate.

**Comment by caseyahenson** [comment]
@mike-fabian we've fixed this as well as #478 and #479 in the repo, we'll be pushing a release in the near future. Thanks for catching this!
