### ISSUE TITLE
In the emoji.json file of the 3.0 release, all keyword lists  start with an empty string

### ISSUE THREAD

**Issue by mike-fabian** [Ranks/emojione#479]
For example:

{"1f600":{"name":"grinning face","category":"people","order":1,"display":1,"shortname":":grinning:","sho
rtname_alternates":[],"ascii":[],"diversity":null,"diversities":[],"gender":null,"genders":[],"code_poin
ts":{"base":"1f600","output":"1f600","default_matches":["1f600"],"greedy_matches":["1f600"],"decimal":""
},"keywords":["","smiley","emotion","happy","thank you","smile","friend","teeth","pacman"]},"

The first keyword is always an empty string.

**Comment by CheyenneForbes** [comment]
it wasnt an empty space, it was the emoji (unicode), it should be put back in it because it can come in handy if you have an emoji search feature.
