### ISSUE TITLE
Javascript unicodeToImage method doesn't work

### ISSUE THREAD

**Issue by codefuhrer** [Ranks/emojione#480]
![2017-04-24 04-18-46](https://cloud.githubusercontent.com/assets/2178368/25319339/6ae6cf64-28a5-11e7-91b2-f4254087ca01.png)

Tested on latest Chrome and Firefox.

UPD: I'm using the library from jsdelivr: https://cdn.jsdelivr.net/emojione/3.0.0/lib/js/emojione.min.js

**Comment by caseyahenson** [comment]
@codefuhrer can you paste that Unicode here as a code snippet?

**Comment by codefuhrer** [comment]
`😉` (U+1F609)

Actually, this method doesn't work with any of Unicode emojis, not just this one.

**Comment by dbrgn** [comment]
Same problem here. It works with some, but not with others:

![2017-04-24-095129_609x78_scrot](https://cloud.githubusercontent.com/assets/105168/25327224/a70f2378-28d3-11e7-99b4-5a7bb83fd3d6.png)

Here are the two unicode characters:

- Dog (0x1F436): 🐶
- Sparkles (0x2728): ✨

**Comment by dbrgn** [comment]
I think I found the reason:

- `⁉️` (0x2049) does not work
- `⁉️` (0x2049 0xfe0f) does work

Looks like unicode characters without the variation selector 0xfe0f (http://www.fileformat.info/info/unicode/char/fe0f/index.htm) don't work, could that be?

This is the corresponding "code_points" section from your emoji.json:

```json
"code_points": {
  "base": "2049",
  "output": "2049",
  "default_matches": [
    "2049-fe0f"
  ],
  "greedy_matches": [
    "2049-fe0f"
  ],
  "decimal": ""
},
```

**Comment by caseyahenson** [comment]
Looks like there was an issue when minifying the js file. You can temporarily resolve this by referencing the js/emojione.js library file directly from the repo. We'll get a fix for this published soon.

**Comment by caseyahenson** [comment]
You'll find a fix for this in the 3.0.1 libraries. Thanks for bringing this to our attention!

**Comment by dbrgn** [comment]
There's now another problem (when using spritemaps again):

```javascript
> emojione.unicodeToImage('☹️')
"<span class="e1 e1-people _2639-fe0f" title=":frowning2:">☹️</span>"
```

The code generated is `2639-fe0f`, but the PNG in the download is called just `2639.png`. When generating spritemaps based on the name, the two don't match.

@caseyahenson should I open a separate issue for this?

**Comment by caseyahenson** [comment]
@dbrgn Yes please submit a new issue for this.
