### ISSUE TITLE
CDN 3.0 update?

### ISSUE THREAD

**Issue by milesj** [Ranks/emojione#481]
Any timeframe on when the CDN will be updated with 3.0 images?

**Comment by caseyahenson** [comment]
Hi @milesj 3.0 images are up in the CDN now. Moving forward the assets will be versioned, so for example 3.0 can be accessed using the url: `https://cdn.jsdelivr.net/emojione/assets/3.0/png/64/1f600.png`. Sizes (32px, 64px, and 128px) are specified in the url as well. 

Version 2 assets remain accessible at their existing non-versioned CDN location to help preserve backwards compatibility.

**Comment by milesj** [comment]
Ah, is that the new CDN? Was previously using this one, which only supports 2.2.7. https://cdnjs.com/libraries/emojione

Would be nice if that CDN link was present in the readme or on the website.

**Comment by milesj** [comment]
Thanks for an amazing library btw!
