### ISSUE TITLE
[PHP] &lt is ignored

### ISSUE THREAD

**Issue by koreus** [Ranks/emojione#485]
Hi,

With version 2.7, I was able to convert ascii with the < character to an image after using the htmlspecialchars function.
But with 3.0, it doesn't work anymore because &lt is ignored
I think the problem may come from the variable $asciiRegexp in Ruleset.php

**Comment by caseyahenson** [comment]
@koreus can you give a specific example of an ASCII char sequence and which function you're running it through for conversion? For example, when converting `<3` using the shortnameToImage function (https://demos.emojione.com/latest/phpshortnametoimage.php), the regex matches the sequence and attempts to return the image. 

Issue #484 points out an issue that's demonstrated here, where the heart is returned with a vs16 (fe0f) modifier attached to the file name so it doesn't properly match the image, but this will be fixed soon.

**Comment by koreus** [comment]
@caseyahenson 

`	  $client = new Client(new Ruleset());
	  $client->ascii = true;
	  $message = '<3';
          echo $client->shortnameToImage($message); // show image => OK
	  $message = htmlspecialchars($message);
          echo $client->shortnameToImage($message); // show <3 => NOK

`
I have copy/paste the old $asciiRegexp (2.2.7) in @caseyahenson  the new 3.0 code and it works.

**Comment by caseyahenson** [comment]
I see, thanks for your example. This is the issue presented in #54. Hopefully we can complete a solution for this and release it in our upcoming patch.

**Comment by caseyahenson** [comment]
@koreus this is fixed in 3.0.2, released today. The property `riskyMatchAscii` can be set to `true` to match ASCII chars with or without adjacent spaces.
