### ISSUE TITLE
Emojione v.3.0.1 doesn't recognize some unicode symbols

### ISSUE THREAD

**Issue by codefuhrer** [Ranks/emojione#487]
At least these ones:

[Heavy Exclamation Mark Symbol](http://emojipedia.org/heavy-exclamation-mark-symbol/): `❗`
[White Smiling Face](http://emojipedia.org/white-smiling-face/): `☺️`
[White Frowning Face](http://emojipedia.org/white-frowning-face/): `☹`

_UPD: there are more. Too lazy to make links:_
`✌` Victory Hand, `🖐` Raised Hand With Fingers Splayed, `✍` Writing Hand, `☝` Index Pointing Up, 
`🗻` Mount Fuji, `🏕` Camping, `🏖` Beach With Umbrella, `🏜` Desert, `🏝` Desert Island, `🏞` National Park, `🏟` Stadium, `🏛` Classical Building, `🏗` Building Construction, `🏘` House, `🏙` Cityscape, `🏚` Derelict House, and many more.

v. 2.x:
![2017-04-27 03-56-54](https://cloud.githubusercontent.com/assets/2178368/25463254/9e25209c-2afd-11e7-92de-c6bd15cffaa2.png)

v. 3.0.1:
![2017-04-27 03-58-20](https://cloud.githubusercontent.com/assets/2178368/25463276/cdfb4f12-2afd-11e7-8db1-b2667182023a.png)

**Comment by caseyahenson** [comment]
Good catch @codefuhrer! Our rules have gotten a lot more complex and strict with this new library. These are emoji defectives which currently (in v3.0.1) could be caught by turning greedyMatch to true, however in 3.0.2 they'll be properly considered and replaced without the need for greedyMatch.

**Comment by JoshyPHP** [comment]
I didn't check all of them but it looks to me like those emoji have `Emoji_Presentation=No` which means they should generally be displayed as text on plain web pages, rather than images. As far as I'm concerned, that's the correct behaviour. It is my understanding that Unicode's recommendations for emoji selectors/keyboards (I'm talking about user interfaces for selecting emoji) is to add a VS16 (U+FE0F) to indicate that the user wants the character to be displayed as an image.

 - http://unicode.org/emoji/charts/emoji-style.html
 - http://unicode.org/Public/emoji/5.0/emoji-data.txt (`Emoji_Presentation` property)
 - http://unicode.org/Public/emoji/5.0/emoji-test.txt (fully-qualified vs non-fully-qualified)

**Comment by caseyahenson** [comment]
@JoshyPHP I think an argument could be made either way on this. For example, the Unicode emoji output list at: http://unicode.org/emoji/charts/full-emoji-list.html#2639 uses the NFQ variation for this unique group of emoji, as does the iOS keyboard. Other apps and sites like Emojipedia use the fully-qualified variant when copying.

We can allow the user to turn off this feature, but I personally think that having these defectives be matched and replaced by default is the generally preferred option.

**Comment by JoshyPHP** [comment]
Sure you can choose a different default presentation mode but I wouldn't call the default presentation mode for plain web pages defective; That's misleading.

I do note that the page you linked explicitly specify to use an emoji font in its CSS.

**Comment by caseyahenson** [comment]
I'm only referring to the characters as having an emoji defective property (Emoji_Presentation=No but should sometimes be displayed as emoji even without VS16). I think it's well within the interpretation of Unicode recommendations to display those in their default presentation mode.

**Comment by Crissov** [comment]
Um, _defective_ is usually a term associated with Fitzpatrick Modifiers and RIS that make no sense to appear alone.

**Comment by caseyahenson** [comment]
@Crissov thanks for clarifying. @codefuhrer look for a solution to be pushed out for this tomorrow.

**Comment by Crissov** [comment]
The more appropriate term for that is now _Emoji Component_, though. http://www.unicode.org/L2/L2016/16238r-component.html

**Comment by caseyahenson** [comment]
@codefuhrer I just double checked that all of these are available in >= 3.0.0 by setting `emojione.greedyMatch = true`. Let me know if you see otherwise.

**Comment by codefuhrer** [comment]
@caseyahenson btw, is there a list of all emojione object options? I couldn't find it in the examples or docs.

**Comment by caseyahenson** [comment]
@codefuhrer those will be available in the USAGE.md readme later today, right now they're scattered throughout /examples and demos.
