### ISSUE TITLE
unicodeRegexp doesn't seem to match ":one:", ":two:" etc.

### ISSUE THREAD

**Issue by butchmarshall** [Ranks/emojione#490]
It looks like the unicodeRegexp does not match the ` 1️⃣` and instead only returns  `   ️⃣`

![image](https://cloud.githubusercontent.com/assets/339763/25588093/e879bf02-2e74-11e7-811e-7900b3bf75f7.png)

**Comment by caseyahenson** [comment]
@butchmarshall can you paste the exact search string that you're using as a code snipped here?

**Comment by butchmarshall** [comment]
Sure, i'm searching for the following characters:

These do not work:
`1️⃣`
` 2️⃣` 
` 3️⃣`
` 4️⃣`
` 5️⃣`
` 6️⃣`
` 7️⃣`

These two work correctly:

`8️⃣`
 `9️⃣`

**Comment by caseyahenson** [comment]
Thanks! And just to double check, are you using version 3.0.1 of the libraries?

**Comment by butchmarshall** [comment]
Using 2.2.7

3.0.1 crashes on load.

TypeError: string.replace is not a function
    at Object.ns.replaceAll (emojione.js:504)
    at Object.ns.toShort (emojione.js:351)
    at index.js:54
    at index.js:69
    at String.replace (<anonymous>)
    at index.js:49
    at NearFulfilledProxy.PSLIB.Promise.NearFulfilledProxy.when (promise.js:620)
    at Promise._message (promise.js:544)
    at Array.deliver (promise.js:436)
    at runHandlers (promise.js:502)
    at Array.<anonymous> (promise.js:469)

**Comment by butchmarshall** [comment]
Using 2.2.7, it looks like unicodeRegexp was ewmocremoved/replaced with unicodeToImage in 3.0.1?

This function seems to work except it returns an actual <img /> tag.

**Comment by caseyahenson** [comment]
`unicodeRegexp` was previously being used only to build the `regUnicode` expression with literal match. Starting in 3.0.0 `regUnicode` is now range matching Unicode (at a speed about 3x faster) so we removed `unicodeRegexp`.

`unicodeToImage` has been around for awhile but it does employ`regUnicode` to match Unicode, in 3.0.1 here: https://github.com/Ranks/emojione/blob/master/lib/js/emojione.js#L306 as you probably noticed. What are wanting to see returned from the regex?

**Comment by butchmarshall** [comment]
I'm just looking to extract all the emoji unicode characters that are supported by EmojiOne from a string.

e.g.

`😛`
`👩‍❤️‍💋‍👩`
`😛`
`😼`

**Comment by caseyahenson** [comment]
Makes sense :). With >= 3.0.0 you should be able to run `exec()` directly on `regUnicode` and accomplish the same thing you were in v2.

**Comment by butchmarshall** [comment]
regUnicode also seems to match HTML?

3.0.1
`Emojione.regUnicode.exec("wow <p>this is great</p>")`
=> `["<p>", index: 4, input: "wow <p>this is great</p>"]`

2.2.7
`new RegExp(Emojione.unicodeRegexp,'g').exec("wow <p>this is great</p>")`
=> `null`

**Comment by butchmarshall** [comment]
Great workaround!  Thanks for your time @caseyahenson !
