### ISSUE TITLE
JS .toImage has sprite error

### ISSUE THREAD

**Issue by Nickske00** [Ranks/emojione#493]
Hi,

Last days I've spent implementing your nice emoji's into a website. I decided to use the sprites (because once loaded they are way faster than individual png's). But I'm running into a problem with the javascript convertor (used in our chat module and server). When I use the toImage function I get different results for the toned emoji's.

For example (tested with the latest version atm 3.0.2):
:clap_tone5: 
JS: `<span class="emojione emojione-32-people _1f44f-1f3ff" title=":clap_tone5:">????????</span>`
PHP: `<span class="emojione emojione-32-diversity _1f44f-1f3ff" title=":clap_tone5:">👏🏿</span>`

So, the PHP parser (used on the forums) is working correctly but the javascript parser seems to have an error in his sprite list...

**Comment by caseyahenson** [comment]
This issue is fixed in the 3.0.3 release.
