### ISSUE TITLE
U+263A "white smiling face" emoji looks wrong

### ISSUE THREAD

**Issue by bjorn** [Ranks/emojione#50]
Unicode character U+263A is described as a "white smiling face". I read that the white is not meant to be taken as the color of the face, but rather that the face is outlined as opposed to filled. The native example depicts the most basic of smiley faces, and probably the one most frequently used as just ":)".

However, Emoji One has turned this emoji into a blushing face looking extremely relaxed (similar to :relaxed:). Taking the "smiling face" code point and putting this strange expression on it unfortunately leaves the basic smiling face nowhere to be found, and as such often entirely unavailable (like here on github as well as on Discourse).

Check out this page for a comparison:

http://www.emoji.codes/family

To me the following look out of place: Emoji One, Apple, Twitter, Phantom. The others all look mostly right, except for Samsung which seems to have interpreted the "white" wrongly.

I don't know who started with the blushing relaxed face, but I really hope there is still a chance to correct this so that we may also have a basic smiling face.

**Comment by Art4** [comment]
I agree. :+1: I missing it too. There should be a smiling face emoji with closed mouth and open eyes. Imho `:relaxed:` is a wrong name for a _white smiling face_ emoji.

**Comment by emitstop** [comment]
Hey guys, this is something we had taken into consideration while developing Emoji One, the reasoning behind this decision is based on the other majorly available emoji sets. While you are correct that we are not matching the unicode spec, our top priority is to ensure translatability between Emoji One and the Emoji that exist natively on people's phones. If you take a look at our family table, the other major sets use a similar icon: http://www.emoji.codes/family

As for the 'relaxed' shortcode name, these are also not a part of the unicode spec, however it is fairly standardized across many sites (including github). See here: http://www.emoji-cheat-sheet.com/

**Comment by bjorn** [comment]
Hmm, I don't buy the majority argument much since of the others only 3/9 are doing the strange blushing smiley. So you have joined the minority in conflict with the specification, which is a bit strange.

As for "standardized", I'm afraid that's reversing the causality. The reason sites like github and Discourse have the strange blushing smiley is because of sets like Emoji One using that image and not the other way around.

**Comment by emitstop** [comment]
Hmm, I count 6/9 with the exceptions being Symbola, Samsung and Windows. Windows only missing the blush. 
However, It's important to note that each set's inclusion on this table does not mean they are equally popular. I absolutely agree that these native sets should be following the unicode standard more closely, however that is not our goal with this project. Our top priority is to have an open source web replacement for the emoji users can (and inevitably will) input from their mobile devices. Which means the odd decisions made by Apple, Windows, Google, Twitter etc. take precedent. 

For the average user, they aren't looking at their iphone's emoji keyboard and wondering why U+263A doesn't match the unicode spec. But they would wonder why the :relaxed: face they inputted on their phone looks like a white outline face once submitted.

**Comment by bjorn** [comment]
I think the average user is wondering where the standard smiling face image is. And it is completely missing! And again, the "white" is not meant to be taken as an instruction to make a ghost face from it.

I don't understand how you're counting. Not counting Emoji One, here's the overview:

Native: **smiling face**
Apple: blushing face
Droid II: **smiling face**
Symbola: **smiling face**
Windows: **smiling face**
Twitter: blushing face
LG: **smiling face** (if you notice, _all_ of LG's smilies have that slight blush)
Samsung: **smiling face** (being white, but I consider that an error)
Phantom: blushing face

So out of these 9, the only blushing ones are in the Apple, Twitter and Phantom sets. I don't know where these are used, but I think it would be very hard to say for certain that these form the majority of what people use.

**Comment by emitstop** [comment]
I wasn't counting the native column, but I think you have a point. On my mac at least, it's rendering that row like this:
![outline face](http://puu.sh/fK51x/bbca3ce7aa.png)
So it seems Apple has indeed fixed the error on their end (though they've neglected to create a new design in it's place), in which case I'd assume the same is probably true on iOS, but I don't have an iPhone to test with at this moment. I'll bring this with the rest of the team, Thank you.

**Comment by bjorn** [comment]
Thanks for your consideration!

**Comment by dgrad** [comment]
any reason why 1F642 ("SLIGHTLY SMILING FACE") is not implemented? that could be an alternative codepoint for a regular smile

**Comment by mikebe11** [comment]
Good discussion and good points made here but we've decided to stick with the current design. It may not be true to the spec but it allows our set to remain more compatible with some of the "heavier hitters" in the market today who use emoji.

**Comment by bjorn** [comment]
So, the only way forward seems to be to petition Apple to fix this smiley, given that both  Emoji One and Twitter recognized this as an issue already but do not want to change it because of Apple's mistake...
