### ISSUE TITLE
Some emojis are not being parsed. (2.2.7)

### ISSUE THREAD

**Issue by mroftalp** [Ranks/emojione#503]
```
emojione.toImage(':large_blue_circle:');
:large_blue_circle:
```
Along with these other emojis:
```
:asterisk_symbol:
:pound_symbol:
:digit_nine:
:digit_eight:
:digit_seven:
:digit_six:
:digit_five:
:digit_four:
:digit_three:
:digit_two:
:digit_one:
:digit_zero:
```

**Comment by caseyahenson** [comment]
@mroftalp the digits and symbols were removed from conversion since their non-emoji form was being replaced, which is resolved in version 3. You should be able to parse `:blue_circle:`, not sure if we ever had a `large` variant of that?

**Comment by mroftalp** [comment]
@caseyahenson Ahhh, I understand. Oh okay, my bad I must have downloaded the wrong emoji strategy version. Thank you!
