### ISSUE TITLE
:tm: shortcode for Turkmenistan flag broke :tm: shortocde for ™

### ISSUE THREAD

**Issue by Coquevas** [Ranks/emojione#51]
Javascript `toShort: all emoji` test refuses to pass because the new shortcode for Turkmenistan flag overrides the ™ sign shortcode.

Taking a look to the PHP code, same thing there.

Also, this can happen with other countries flags. I did a quick review and :cl: : cl : also match Chile flag.

**Comment by Coquevas** [comment]
other conflicts: :ng:, :sa:

I just removed almost all of the test case temporary to be able to test my code.

**Comment by kevinranks** [comment]
These conflicts should be resolved now.
