### ISSUE TITLE
vaildate.yml toShort:all emojis test does't include all the existent emojis

### ISSUE THREAD

**Issue by Coquevas** [Ranks/emojione#52]
New flags weren't added. Probably because no test were run for them, producing issue #51.

**Comment by kevinranks** [comment]
Hey @Coquevas, you're right about this. We severely need to improve the [non-existent] automated testing. Ideally we'd like to setup robust tests using qunit or similar for the JS that can be ran via a grunt task before developers request a merge. Similarly we'd need to match it for the PHP library. Contributions are welcome :)

**Comment by mikebe11** [comment]
Finally complete. Split up all emojis test into individual ones. It was getting too large and hard to read errors. Next step should be more tests and grouping into a couple separate files.
