### ISSUE TITLE
Please update Emoji family tree

### ISSUE THREAD

**Issue by wp9015362** [Ranks/emojione#58]
Hello,

could you please update the Emoji familiy tree over there:

http://emoji.codes/family

?

Things I noticed:

* Generally some Emojis are not being displayed, even though they should be there (:one:, :two:, :three:, :four: etc. are msissing from the Twitter Emojis for example) 
* You still seem to be using an old version of the Google Emojis, even though there was an update to the Google Emojis, see: http://blog.emojipedia.org/android-50-emoji-changelog
* You still seem to be using an old version of the Apple Emojis, even though there was an update to the Apple Emojis, see: http://blog.emojipedia.org/apple-2015-emoji-changelog-ios-os-x

Could you please fix that?

Regards

**Comment by emitstop** [comment]
In most of these cases we don't have even really have official sources for the images, most were scraped and pulled together from various unofficial places. We would need to make significant modifications to our table for the 8.0 pigment variations in Apples set, and updating and monitoring the all the existing emoji packs for updates is not something we really have time or manpower to prioritize for right now. 

Our family table should be viewed as a quick and easy comparison of the emoji's visual style against the other popular sets, and not a definitive continually up-to-date resource. Additionally the emoji codes site is only tangentially related to this repo, as it's kind of a standalone tool. I'm going to close this issue, but thank you for keeping a vigilant eye, your contributions are always welcome!

**Comment by emitstop** [comment]
We've decided to put more focus on the emoji.codes and emojione.com sites, so we will be moving them into this repo, and decided this particular issue is definitely on our to-dos! The obstacle at the moment is we still have to find a good resource for the updated graphics from the third party sets.

**Comment by wp9015362** [comment]
Since HTC devices also seem to have their own Emoji set, see for example:

https://code.google.com/p/android/issues/detail?id=73248#c39

it would be kinda nice if you could also get that into the family tree for comparison purposes as well then.

Regards

**Comment by wp9015362** [comment]
> @emitstop wrote:
> 
> The obstacle at the moment is we still have to find a good resource for the updated graphics from the third party sets.

The SVGs for the Google "Noto Color Emoji" Emoji set are available over there:

https://code.google.com/p/noto/source/browse/?name=master#git%2Fcolor_emoji%2Fsvg

And the SVGs for the Twitter "Twemoji" Emoji set are available over there:

https://github.com/twitter/twemoji/tree/gh-pages/svg

Since both are available as SVGs, it would be nice if you could also use SVGs on:

http://emoji.codes/family

Not sure, but currently you seem to be using SVGs for the Emoji One Emojis on that page whereas for all the other Emoji sets on that page you seem to be using small bitmaps/PNGs/JPEGs or whatever.

When you zoom into the page, the Emoji One Emojis remain sharp and clear, but all the other ones become blurry.

So, since the Google and Twitter Emojis are available as SVGs, it would be nice if you could use SVGs for them on that page as well.

It would also be nice if you could move the Twitter Emojis further to the left.

Currently the "Symbola" Emojis are next to the Google "Droid II" Emojis. IMHO it would be better if the Twitter Emojis would be next to the Google "Droid II" Emojs.

And while you're at it, maybe you could also rename "Droid II" to "Google Noto Color Emoji" or simply "Google" :wink:.

Regards

**Comment by stuartpb** [comment]
Progress on this? I wouldn't mind if emoji.codes were given its own repo (and maybe emojione gets its own org).

**Comment by mikebe11** [comment]
We've fixed the missing emoji and updated the sets. We've also replaced the Twitter and Google PNGs with SVGs. Thanks for the link to the current Google set.

**Comment by wp9015362** [comment]
> @mikebe11 wrote:
> 
> We've fixed the missing emoji and updated the sets. We've also replaced the Twitter and Google PNGs with SVGs.

Thank you! Looks much better now.

> @mikebe11 wrote:
> 
> Thanks for the link to the current Google set.

Just for the record:

It has been moved from code.google.com to github.com now, see:

https://github.com/googlei18n/noto-emoji

Regards
