### ISSUE TITLE
Emoji One smiley faces and default human skin tones are orange. Please change to yellow.

### ISSUE THREAD

**Issue by wp9015362** [Ranks/emojione#59]
Hello,

the Emoji One faces are orange.

IMHO they would look better if they would be yellow.

Could you please make them yellow?

It would be much appreciated.

Regards

**Comment by waldyrious** [comment]
:+1:

**Comment by wp9015362** [comment]
PS:

Since you also seem to be working on the [skin tone modifier feature](https://github.com/Ranks/emojione/issues/69), I just want to point out that it would be nice if you could change the default skin tone of all Emoji One Emojis to yellow. Not just the smiley faces but also the human Emojis.

Because currently most Emoji One Emojis that have some form of skin use orange for their skin tone.

So, it would be nice if you could change that to yellow.

The latest Draft Unicode Technical Report 51 says:

> http://www.unicode.org/reports/tr51/#Diversity
> 
> [...] When a human emoji is not immediately followed by a emoji modifier character, it should use a generic, non-realistic skin tone—such as (RGB #FFCC22), one of the colors typically used for the smiley faces. [...]

And Apple and Google are using yellow for their smiley and human faces now, see:

http://blog.emojipedia.org/apple-2015-emoji-changelog-ios-os-x
http://blog.emojipedia.org/android-50-emoji-changelog

So it would make for a better interoperability and apart from that I personally think yellow would look better than orange :wink:.

Regards
