### ISSUE TITLE
Please give Emoji One Emojis a faint, narrow contrasting border to keep them visually distinct from a similarly colored background (as recommended by latest Draft Unicode Technical Report #51)

### ISSUE THREAD

**Issue by wp9015362** [Ranks/emojione#60]
Hello,

the Emoji One Emojis do not have a faint, narrow contrasting border to keep them visually distinct from a similarly colored background.

The latest Draft Unicode Technical Report 51:

http://www.unicode.org/reports/tr51/

recommends to give Emojis a faint, narrow contrasting border to keep the them visually distinct from a similarly colored background.

Please give the Emoji One Emojis a faint, narrow contrasting border to keep them visually distinct from a similarly colored background.

Regards

**Comment by wp9015362** [comment]
PS:

It seems like Google also is doing this for their "Noto Color Emoji" Emoji set.

If you take a look at the updated Emojis shown over there:

http://blog.emojipedia.org/android-50-emoji-changelog

then you can see that all the updated Emojis now have a faint, narrow contrasting border around them to keep them visually distinct from a similarly colored background.

It would be really nice if you could do it for the "Emoji One" Emoji set as well.

**Comment by wp9015362** [comment]
> @wp9015362 wrote:
> 
> It seems like Google also is doing this for their "Noto Color Emoji" Emoji set.

> If you take a look at the updated Emojis shown over there:

> http://blog.emojipedia.org/android-50-emoji-changelog

> then you can see that all the updated Emojis now seem to have a faint, narrow contrasting border around them to keep them visually distinct from a similarly colored background.

This probably has to be rectified.

The borders which can be seen on the Emojis over there:

http://blog.emojipedia.org/android-50-emoji-changelog

actually seem to come from a dark background. Maybe the Emojis simply were quickly cut out from a screenshot which had the Emojis shown on an Android keyboard with a dark background.

Because those borders do not seem to appear anywhere else, only in this blog post.

If you take a look at the following page:

http://www.unicode.org/Public/emoji/1.0/full-emoji-list.html

then you will see, that the Google Emojis do not have such a border.

So, please ignore [the previous post](https://github.com/Ranks/emojione/issues/60#issuecomment-90897358).

Still would be nice though if the Emoji One Emojis would get a faint, narrow contrasting border to keep them visually distinct from a similarly colored background.

Regards

**Comment by mikebe11** [comment]
Hello,
Going to close this issue since the current collection will not be revised to get a contrasting border.
The designers of the latest set have seen this suggestion. It'll be kept in mind while they are making design choices on the new set. Thank you.
