### ISSUE TITLE
Please make the red hearts which are present in various Emoji One Emojis have a more pure and vibrant red.

### ISSUE THREAD

**Issue by wp9015362** [Ranks/emojione#64]
Hello,

the red hearts which are present in various Emoji One Emojis, such as the "smiling face with heart-shaped eyes" Emoji One Emoji for example:

![Image](https://github.com/Ranks/emojione/raw/master/assets/png/1F60D.png)

all are RGB 209,56,82.

There is too much blue and green in it IMHO.

IMHO the red should be more pure and vibrant.

Could you please change that?

Regards

**Comment by wp9015362** [comment]
May I ask why this issue was solved without a comment?

Even "The 2016 Collection" suffers from this isuee, see:

https://github.com/Ranks/emojione/issues/127

Regards

**Comment by mikebe11** [comment]
Hello,
There were many requests for changes in the last revision. Sorry this one missed a closing comment. It was a suggestion that was considered and ultimately not chosen to adopt.
