### ISSUE TITLE
@jbrecht this is a great catch, thank you for pointing it out. It does appear that the gender for codepoints without `2640` are not being correctly set in the emoji.json file. Woman Astronaut should have a `gender` value of `2640` (the base code point of the female sign). We'll make the adjustments and get this published as soon as possible.

### ISSUE THREAD

**Issue by tangbuulam** [Ranks/emojione#662]
@jbrecht this is a great catch, thank you for pointing it out. It does appear that the gender for codepoints without `2640` are not being correctly set in the emoji.json file. Woman Astronaut should have a `gender` value of `2640` (the base code point of the female sign). We'll make the adjustments and get this published as soon as possible.

_Originally posted by @caseyahenson in https://github.com/joypixels/emojione/issues/654#issuecomment-484688408_

**Comment by caseyahenson** [comment]
@tangbuulam update for this is nearly complete, to be released this week!

**Comment by caseyahenson** [comment]
This is fixed in the 5.0 release https://github.com/joypixels/emoji-toolkit/releases/tag/5.0.0.
