### ISSUE TITLE
Please add Emoji category icons which are being used on Emoji One websites to the Emoji One GitHub repository

### ISSUE THREAD

**Issue by wp9015362** [Ranks/emojione#67]
Hello,

the Emoji One websites have some Emoji category icons (smiley icon / flower icon / bell icon / car icon / symbols icon) which are being used to toggle between the Emoji categories on the Emoji One websites.

Could you please add those icons to the Emoji One GitHub repository?

Regards

**Comment by mikebe11** [comment]
Revisited this request now that v2 has been posted. Current category icons are up. 
Thanks
