### ISSUE TITLE
New Unicode Emojis still missing from Emoji One

### ISSUE THREAD

**Issue by wp9015362** [Ranks/emojione#68]
Hello,

on the Emoji One homepage you are saying:

> http://emojione.com/
> 
> [...] But wait, there's more! 😯 Within the coming months, we'll release the newest emoji additions (which unicode announced in June, around 250 in all) including the ever-adorable middle finger. [...]

But they are still missing.

Could you please add the new Unicode Emojis to Emoji One?

And is there already an ETA for this?

Regards

**Comment by kevinranks** [comment]
Hey @wp9015362 ! Thanks for all of the suggestions, do you have a minute to jump on our gitter and chat with us?

**Comment by wp9015362** [comment]
@kevinranks :

May I ask what you want to talk about there which can not be talked about here?

By they way, just saying, it looks like as if Mozilla will soon have an entirely new Unicode 7.0 Emoji set with all the new Emojis (incl. middle finger etc.), see the following links for more details:

http://www.sabrinasmelko.com/portfolio/emojis/
https://bugzilla.mozilla.org/show_bug.cgi?id=1053216
https://twitter.com/SabrinaSmelko/status/586274190430511105

Regards

**Comment by kevinranks** [comment]
@wp9015362 Definitely nothing that we can't talk about here. We just had our EmojiOne team together for a meeting when you were adding these issues so we thought it could be a good chance to talk about some of them with you as well as discuss anything else you had in mind since you appear to have a lot of knowledge surrounding the Unicode emoji spec.

**Comment by kevinranks** [comment]
PS Thanks for the link the to Mozilla emoji, they look cool!

**Comment by wp9015362** [comment]
> @kevinranks wrote:
> 
> We just had our EmojiOne team together for a meeting

Some public logs would be appreciated :wink:.

> so we thought it could be a good chance to talk about some of them with you as well as discuss anything else you had in mind since you appear to have a lot of knowledge surrounding the Unicode emoji spec.

Thanks for the appraisal :smile: .

But all I know from those specs basically comes from the following video presentation from Mark Davis:

http://macchiati.blogspot.co.uk/2014/11/unicode-emoji.html

his latest Draft Unicode Technical Report 51 :

http://www.unicode.org/reports/tr51/

and some comments he makes on the AOSP issue tracker, like the following one for example:

https://code.google.com/p/android/issues/detail?id=73248#c14

:wink:

Oh, and also from sites like [emojipedia.org](http://emojipedia.org/) :wink:.

And I only came across those presentations, recommendations, comments, websites and so on because I started to become upset by the fact that there are so many different Emoji sets out there which mostly look so different from each other that they easily can get lost in translation, as described in the following article:

http://www.huffingtonpost.com/2014/06/27/emoji-meaning_n_5530638.html

So, due to that issue I became a little interested in this topic and wanted to see what this is all about, that's basically it :wink:.

So, I am basically just a user at the moment, not a designer or developer or anything like that, but maybe some of the links mentioned above might still be useful for you.

> @kevinranks wrote:
> 
> PS Thanks for the link the to Mozilla emoji, they look cool!

Well, most of the Emojis in that set seem to look quite nice.

But the faces and cat faces do not IMHO.

The faces look like little babies with ears and their expressions and their overall look is way different than any other Emoji set I know off...

And the "cat faces" are made to look like fox faces, even though they are described as cat faces in Unicode...

That all leads to the issue mentioned above, which is that Emojis can easily get lost in translation as described in the following article:

http://www.huffingtonpost.com/2014/06/27/emoji-meaning_n_5530638.html

And that sucks (IMHO).

At least Emoji One does not do such things :+1: :wink:.

Or at least not that obviously.

By the way, somehow I find it a bit sad that there soon will probably be five different open source Emoji sets.

The "Emoji One" Emoji set, the Twitter "Twemoji" Emoji set, the Google "Noto Color Emoji" Emoji set, the "Phantom Open Emoji" Emoji set and possibly that new Mozilla set.

Probably would be better if everyone would contribute to one set instead of each making their own thing.

But, well, it's probably not your fault, since you were one of the first to come out with an open source Emoji set.

Anyway, back to topic:

Did your happen to establish a ETA for the new Unicode Emojis in your team meeting :wink:?

Regards

**Comment by kevinranks** [comment]
Thanks for the kind words, and thanks for taking so much interest in the emoji community. We actually started Emojione because at the time there was no free open source emoji set (besides Phantom which is not complete). Shortly after our release Twitter released theirs and now it seems like there are some other on their way. 

It's unfortunate that we aren't all collaborating but at least emoji in general is getting more attention. That can only be a good thing for the community. We've tried hard to keep our emoji images familiar for the users.

As far as the new 7.0 Unicode, we're working on categorizing them as well as adding the new diversity changes if possibe, so I'd expect them within a few weeks. We've had the images themselves ready for a while but have lacked the time to get them out. 

We're also trying to reorganize the repo a bit better to help contributors, just in case you start developing ;)

**Comment by wp9015362** [comment]
> @kevinranks wrote:
> 
> We've tried hard to keep our emoji images familiar for the users for exactly the reasons you mentioned. In our own projects, we want our users to be able to insert emoji from their devices (apple or other) and convert them to our emoji images without causing too much confusion.

Thanks a lot! Much appreciated!

Although I think there could still be some improvements in that regard in some cases (see open issues for example) :wink:.

> @kevinranks wrote:
> 
> As far as the new 7.0 Unicode, we're working on categorizing them

Not sure exactly what you mean when you're saying that you are working on categorizing them, but, just in case:

It seems like Unicode is working on a new categorization scheme, see the "Ordering and Grouping" section over there:

http://www.unicode.org/reports/tr51/#Sorting

And Apple apparently has also introduced a new categorization scheme in it's latest OS updates, see:

> http://blog.emojipedia.org/apple-2015-emoji-changelog-ios-os-x
> 
> **Emoji Categories**
> 
> Prepare to re-learn the position of your favorite emojis,
> as they have all changed. New categories have been introduced,
> and emojis have been re-arranged within the existing categories as well.
> 
> The new categories are:
>
> 😃 People
> 🌸 Nature
> 🍔 Food & Drink
> 🎉 Celebration
> 🏃 Activity
> 🌇 Travel & Places
> 🔣 Objects & Symbols
> 
> Essentially, many emojis that were previously in the People or Objects categories
> may now be in one of the new, more-specific categories. Objects & Symbols is now
> a catch-all for the more obscure remaining characters.

So, probably would make sense to adhere to those if it's that what you're talking about.

> @kevinranks wrote:
> 
> as well as adding the new diversity changes if possibe, so I'd expect them within a few weeks. We've had the images themselves ready for a while but have lacked the time to get them out. 

That sounds awesome, very much looking forward to it!

Regards

**Comment by kevinranks** [comment]
The new categories you mentioned are exactly what we're talking about :+1:. We'll also be addressing the issues you've raised soon and making improvements where needed. 

Once again thanks for your contributions!

**Comment by mislav** [comment]
Are there any plans to include skin variations for people emoji with respect to Fitzpatrick scale modifiers that debuted in Unicode 7.0?

**Comment by wp9015362** [comment]
> @mislav wrote:
> 
> Are there any plans to include skin variations for people emoji with respect to Fitzpatrick scale modifiers that debuted in Unicode 7.0?

He already answered that two posts above yours..., see:

> @kevinranks wrote in https://github.com/Ranks/emojione/issues/68#issuecomment-93861096:
> 
> As far as the new 7.0 Unicode, we're working on categorizing them as well as adding the new diversity changes if possibe, so I'd expect them within a few weeks. 

And there also is a separate issue for the skin tone modifier feature, see:

https://github.com/Ranks/emojione/issues/69

Regards

**Comment by mandel59** [comment]
Fitzpatrick scale modifiers have not debuted as the Unicode standard yet; They are still in draft.

**Comment by wp9015362** [comment]
> @mandel59 wrote:
> 
> Fitzpatrick scale modifiers have not debuted as the Unicode standard yet; They are still in draft.

Yeah, [but Apple has already implemented it](http://blog.emojipedia.org/apple-2015-emoji-changelog-ios-os-x), so...

Anyway..., this is what the current Draft Unicode Technical Report 51 has to say about this:

> http://www.unicode.org/reports/tr51/#Diversity
> 
> [...] Five symbol modifier characters that provide for a range of skin tones for human emoji are planned for Unicode Version 8.0 (scheduled for mid-2015). These characters are based on the six tones of the Fitzpatrick scale, a recognized standard for dermatology (there are many examples of this scale online, such as FitzpatrickSkinType.pdf). The exact shades may vary between implementations. [...]

Regards

**Comment by mislav** [comment]
My apologies, I just read the spec again and found that Fitzpatrick modifiers haven't in fact debuted in Unicode 7.0 as I stated above. They are slated for 8.0.

@wp9015362 Thanks for all the suggestions and conversation you're making in both this project and twemoji as well. :bow:

**Comment by wp9015362** [comment]
Just curious:

Will the Emoji One update happen anytime soon?

Or will it take some more time?

Regards

**Comment by mikebe11** [comment]
We're working on putting things together now. With time and resources being spread out it's been longer than we'd anticipated. I'd give you a definite date if I could.
Thanks for checking in and for being patient.

**Comment by wp9015362** [comment]
Okay, thanks for the reply.

Very much looking forward to the new Emoji One update!

Regards

**Comment by chekalskiy** [comment]
Hey! Could you just update a PHP lib (maybe in branch)? Really want to use your library with emoji filenames like 1f469-200d-1f469-200d-1f466-200d-1f466.png (woman-woman-boy-boy)

**Comment by mikebe11** [comment]
Hi. Thanks for the interest in using our library. We'll have families in an upcoming release. In the meantime you're free to update the code for any particular project you have. Adding to Ruleset.php and then adding local image files is a way to update your project's copy of the library for new filenames.

**Comment by wp9015362** [comment]
WOW!

I just noticed that Emoji One actually has released the Unicode 7.0 update today, see:

http://emojione.com/
https://github.com/Ranks/emojione/commit/aa55753abfc41b64141c0f033672dc525df4671d
https://github.com/Ranks/emojione/commit/bc777cac0e495a18ac4a9b0e794be5b1a111d1ca
https://github.com/Ranks/emojione/commit/4e995d819d47908f8777237a08df4702e5ac7d01
https://github.com/Ranks/emojione/commit/45148d1a82ad377cdcdd4598963db7fe1e939512

But where is the announcement :yum:?
