### ISSUE TITLE
"Open mailbox with raised flag" Emoji One Emoji has a lowered flag

### ISSUE THREAD

**Issue by wp9015362** [Ranks/emojione#88]
Hello,

the "open mailbox with raised flag" Emoji One Emoji:

![Image](https://github.com/Ranks/emojione/raw/master/assets/png/1F4EC.png)

has a lowered flag instead of a raised flag.

The other mailbox Emoji One Emojis have it correct, see:

"Closed mailbox with raised flag":

![Image](https://github.com/Ranks/emojione/raw/master/assets/png/1F4EB.png)

"Closed mailbox with lowered flag":

![Image](https://github.com/Ranks/emojione/raw/master/assets/png/1F4EA.png)

"Open mailbox with lowered flag":

![Image](https://github.com/Ranks/emojione/raw/master/assets/png/1F4ED.png)

So, could you please fix it?

Regards

**Comment by Zegnat** [comment]
:+1: This is an actual bug.

**Comment by mikebe11** [comment]
Agreed. This one's already on the list for the next release. It'll certainly be fixed.
