### ISSUE TITLE
"French fries" could be better (explanation inside)

### ISSUE THREAD

**Issue by wp9015362** [Ranks/emojione#94]
Hello,

okay, I could imagine that this might sound a little funny to some now, but:

IMHO the french fries in the "french fries" Emoji One Emoji:

![Image](https://github.com/Ranks/emojione/raw/master/assets/png/1F35F.png)

are a little bit too thin, too long and too orange, which makes them look a bit more like some "strange orange sticks" rather than french fries.

It would be nice if you could make them a bit shorter, a bit thicker and also make them more yellow and maybe even put some more french fries in the box.

Regard

**Comment by Thunderpig72** [comment]
Maybe some salt on them too?

**Comment by mikebe11** [comment]
Thank you very much for the design suggestions. In the last update some suggestions were implemented and others didn't make the cut. This one was one of the latter. Updates for this collection have been closed so we're also going to close this issue.
Some great news to add, we're in the process of replacing the entire set (up to unicode 8.0) with all new art. This will most likely be the next design update posted. Thank you again for your input.

**Comment by metavida** [comment]
A sneak peek at the new french fries

![csuzot5wcaahjed](https://cloud.githubusercontent.com/assets/1933/10810445/50e6aeba-7dbe-11e5-9d9b-67627f381c78.png)

via https://twitter.com/emojione/status/658989241960108033
